'use strict';
const assert=require('assert'),fs=require('fs'),os=require('os'),path=require('path');
const {fieldExplanation,timingProblems,connectedCode,diagnosticProblems}=require('../src/attack_workspace_model');
assert.match(fieldExplanation({suffix:'firstActiveElement',category:'Animation timing'}),/element/i);
assert.match(fieldExplanation({suffix:'custom',category:'Project-specific'}),/project-defined/i);
const move={prefix:'normal.sLP',values:{moveID:200,firstActiveElement:2,idleElement:4,hitPauseAnimateStartElement:2,hitPauseFreezeElement:3},timeline:{state:'ready',frames:[{clsn1:[]},{clsn1:[[0,0,1,1]]},{clsn1:[]},{clsn1:[]}]}};
const timing=timingProblems(move);assert(timing.some(item=>item.level==='likely'&&/without Clsn1/.test(item.title)));assert(!timing.some(item=>/duration/i.test(item.title)),'AIR/state duration differences must not be treated as errors');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'attack-workspace-')),character=path.join(root,'chars','Example'),template=path.join(root,'chars','template'),states=path.join(template,'normals.zss'),shared=path.join(template,'shared.zss');
fs.mkdirSync(character,{recursive:true});fs.mkdirSync(template,{recursive:true});
fs.writeFileSync(states,'[StateDef 200]\ntype: S;\nanim: 200;\nhitDef { damage: normal.sLP.damage; }\ncall SharedAttack();\nchangeState { value: 0; }\n[StateDef 210]\ncall Other();\n');
fs.writeFileSync(shared,'[Function SharedAttack]\nmapSet { map: "x"; value: 1; }\n');
const sections=connectedCode({code:[states,shared],constants:path.join(character,'constants.cns'),folder:character,defPath:path.join(character,'Example.def')},move,[]);
assert(sections.some(item=>item.kind==='move-state'&&item.controllers.includes('hitDef')&&item.shared),'a StateDef assigned from the template must be identified as shared');
assert(sections.some(item=>item.kind==='function'&&item.shared));
const lint=diagnosticProblems([{filename:states,line:3,severity:1,message:'Review damage',source:'test'}],sections);assert.strictEqual(lint[0].sectionId,sections.find(item=>item.kind==='move-state').id);
const local=path.join(character,'normals.zss');fs.writeFileSync(local,'[StateDef 200]\ntype: S;\nanim: 200;\n');
const localSections=connectedCode({code:[local],constants:path.join(character,'constants.cns'),folder:character,defPath:path.join(character,'Example.def')},move,[]);
assert(localSections.some(item=>item.kind==='move-state'&&!item.shared),'a character-local StateDef must not be identified as shared');
fs.rmSync(root,{recursive:true,force:true});
console.log('Attack workspace analysis, uncertainty and connected-code isolation tests passed');
