'use strict';
const assert=require('assert'),vm=require('vm');
const {commandValues,findCommand,clientScript}=require('../src/command_movelist_navigation');
const {parseCommands}=require('../src/command_movelist_model');
const commands=parseCommands('[Command]\nname="A"\ncommand=x\n[Command]\nname="B"\ncommand=y\n').commands;
const reference=i=>({tab:'command',file:'test.cmd',command:commandValues(commands[i])});
assert.strictEqual(findCommand(commands,reference(1)),commands[1]);assert.strictEqual(findCommand([...commands,commands[1]],reference(1)),null);
const elements=new Map();const byId=id=>{if(!elements.has(id))elements.set(id,{value:''});return elements.get(id)};
let form=commandValues(commands[0]),draws=0;
const ctx={data:{commands,files:{commandFile:'test.cmd',movelistFile:'moves.dat'}},selected:0,activeTab:'command',byId,values:()=>form,selectedCommand:()=>commands[ctx.selected],inspect:()=>{form=commandValues(commands[ctx.selected]);draws++},list(){},saveCommandState(){},showTab:tab=>ctx.activeTab=tab};
vm.createContext(ctx);vm.runInContext(clientScript(),ctx);
form={...form,time:99};assert(!ctx.ikemenCanRestoreNavigation(reference(1)));assert.throws(()=>ctx.ikemenRestoreNavigation(reference(1)),/unapplied/);assert.equal(form.time,99);
ctx.ikemenRestoreNavigation(reference(0));assert.equal(draws,0,'same command preserves the live form');
ctx.ikemenRestoreNavigation({tab:'movelist',file:'moves.dat'});assert.equal(ctx.activeTab,'movelist');assert.equal(form.time,99,'tab-only restoration retains command edits');
ctx.inspect();ctx.ikemenRestoreNavigation(reference(1));assert.equal(ctx.selected,1);assert.equal(ctx.activeTab,'command');assert.equal(byId('commandView').value,'all');assert.equal(form.name,'B');
assert(!ctx.ikemenCanRestoreNavigation({...reference(1),file:'other.cmd'}));
assert(!ctx.ikemenCanRestoreNavigation({tab:'movelist',file:'other.dat'}));
assert(!ctx.ikemenCanRestoreNavigation({...reference(1),command:{...reference(1).command,time:900}}));
console.log('Command history identity, ambiguous/changed targets, dirty form veto and tab preservation passed');
