'use strict';
const assert=require('assert'),fs=require('fs'),os=require('os'),path=require('path'),Module=require('module');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'ikemaker-helper-draft-')),stored={},supports=new Map(),records=new Map(),commands=new Map(),panels=[];
const workspaceState={get:(key,fallback)=>stored[key]??fallback,update:async(key,value)=>{stored[key]=value;}};
function panel(){const receive=[],dispose=[];const value={viewColumn:2,reveal(){},onDidDispose:fn=>dispose.push(fn),dispose(){dispose.forEach(fn=>fn());},webview:{cspSource:'test:',html:'',messages:[],onDidReceiveMessage:fn=>{receive.push(fn);return{dispose(){}};},postMessage(message){this.messages.push(message);return true;}}};value.send=async message=>{for(const fn of receive)await fn(message);};panels.push(value);return value;}
const vscode={ViewColumn:{Active:1},Uri:{file:fsPath=>({fsPath})},workspace:{textDocuments:[],onDidChangeTextDocument:()=>({dispose(){}})},commands:{registerCommand:(id,fn)=>{commands.set(id,fn);return{};},executeCommand:async()=>undefined},env:{clipboard:{writeText:async()=>{}}},window:{activeTextEditor:null,visibleTextEditors:[],createWebviewPanel:()=>panel(),showErrorMessage:message=>{throw Error(message);},showWarningMessage(){},showInformationMessage(){}}};
const original=Module._load;
Module._load=function(request,parent,main){const from=parent?.filename||'';if(request==='vscode')return vscode;if(request==='./character_picker'&&/helper_workspace/.test(from))return{nearestCharacterDef:value=>/\.def$/i.test(value)&&fs.existsSync(value)?value:'',chooseCharacterDef:async()=>''};if(request==='./related_work'&&/helper_workspace/.test(from))return{resolveAssigned:def=>({code:[path.join(path.dirname(def),'states.zss')],air:'',sff:''})};if(request==='./move_lab_model'&&/helper_workspace/.test(from))return{contextLabel:def=>({project:'Test',character:path.basename(path.dirname(def))})};if(request==='./character_context'&&/helper_workspace/.test(from))return{gameRoot:()=>root};if(request==='./metadata_registry'&&/helper_workspace/.test(from))return{find:()=>''};if(request==='./viewer_group'&&/helper_workspace/.test(from))return{preferredViewerColumn:()=>2,trackViewerPanel:value=>value,revealInViewerGroup:()=>{}};if(request==='./authoring_context_registry'&&/helper_workspace/.test(from))return{registerCharacterToolPanel(){}};if(request==='./launch_controls'&&/helper_workspace/.test(from))return{launchControlsHtml:()=>'',launchControlsClientScript:()=>'',handleLaunchMessage:async()=>false};if(request==='./webview_policy'&&/helper_workspace/.test(from))return{protect:value=>value};if(request==='./viewer_sessions'&&/helper_workspace/.test(from))return{register:(value,source,kind)=>records.set(value,{source,kind})};if(request==='./viewer_close'&&/helper_workspace/.test(from))return{support:(value,options)=>supports.set(value,options)};return original.call(this,request,parent,main);};
(async()=>{try{
 const make=name=>{const folder=path.join(root,name);fs.mkdirSync(folder);const def=path.join(folder,`${name}.def`);fs.writeFileSync(def,'[Info]\nname='+name+'\n[Files]\nst=states.zss\n');fs.writeFileSync(path.join(folder,'states.zss'),'[StateDef 0]\n');return def;};
 const a=make('A'),b=make('B'),helper=require('../src/helper_authoring_model'),workspace=require('../src/helper_workspace');workspace.registerHelperLab({workspaceState,subscriptions:[]});const open=commands.get('ikemen.helperLab.open'),first=await open(vscode.Uri.file(a));assert(first);assert.deepEqual(records.get(first),{source:a,kind:'helper'});assert(supports.has(first));
 const plan=helper.newHelper({name:'Recovered satellite',id:4100,stateNo:4100}),flow=helper.normalizeFlow({map:'mode',value:'3',note:'Recovered contract'});await first.send({type:'generate',revision:7,plan,flow});assert(first.webview.messages.some(message=>message.type==='helperDraftStored'&&message.revision===7));await supports.get(first).keepDraft();first.dispose();
 const reference={defPath:a,view:'flow',mode:'advanced',editingUid:''},restored=await open(vscode.Uri.file(a),{preset:true,reference});assert.match(restored.webview.html,/Recovered satellite/);assert.match(restored.webview.html,/Recovered contract/);assert.match(restored.webview.html,/view=model\.reference\?\.view/);assert.match(restored.webview.html,/Discard recovered work/);
 const other=await open(vscode.Uri.file(b));assert(other&&other!==restored,'different characters retain separate Helper Lab panels');assert.strictEqual(await open(vscode.Uri.file(a)),restored,'the same character reuses its owned panel');restored.dispose();other.dispose();
 const again=await open(vscode.Uri.file(a),{preset:true,reference});await again.send({type:'discardHelperDraft'});again.dispose();const clean=await open(vscode.Uri.file(a),{preset:true,reference});assert.doesNotMatch(clean.webview.html,/Recovered satellite/);clean.dispose();
 const before=panels.length;assert.strictEqual(await open(vscode.Uri.file(b),{preset:true,reference:{defPath:b,view:'unknown',mode:'basic',editingUid:''}}),undefined);assert.strictEqual(panels.length,before,'invalid view is rejected before panel creation');assert(workspace.validHelperReference(reference,a,{graph:{nodes:[]}}));console.log('Helper Lab drafts survive close/reopen, remain character-bound, discard exactly, and reject invalid typed destinations');
 }finally{Module._load=original;fs.rmSync(root,{recursive:true,force:true});}})().catch(error=>{console.error(error);process.exitCode=1;});
