'use strict';
const assert=require('assert'),fs=require('fs'),os=require('os'),path=require('path'),Module=require('module');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'hitdef-preset-')),source=path.join(root,'attack.zss'),text='stateDef 200 {\n  hitDef {\n    attr: S, NA;\n    damage: 20, 0;\n  }\n}\n';fs.writeFileSync(source,text);
const original=Module._load,panels=[],records=new Map();
function positionAt(offset){const before=text.slice(0,offset),lines=before.split('\n');return{line:lines.length-1,character:lines.at(-1).length};}
function document(){const uri={fsPath:source,toString:()=>`file:${source}`};return{uri,fileName:source,languageId:'zss',getText:()=>text,positionAt,offsetAt:position=>text.split('\n').slice(0,position.line).reduce((n,line)=>n+line.length+1,0)+position.character};}
function panel(){const dispose=[];const value={viewColumn:2,reveal(){},onDidDispose:fn=>dispose.push(fn),dispose(){dispose.forEach(fn=>fn());},webview:{cspSource:'test:',html:'',onDidReceiveMessage(){},postMessage(){return true;}}};panels.push(value);return value;}
const vscode={ViewColumn:{Active:1},TextEditorRevealType:{InCenter:0},Uri:{file:fsPath=>({fsPath,toString:()=>`file:${fsPath}`})},Selection:function(a,b){this.active=b;},Range:function(a,b){this.start=a;this.end=b;},window:{activeTextEditor:null,visibleTextEditors:[],createWebviewPanel:()=>panel(),showTextDocument:async doc=>{const editor={document:doc,selection:{active:{line:0,character:0}},viewColumn:1,revealRange(){}};vscode.window.activeTextEditor=editor;vscode.window.visibleTextEditors=[editor];return editor;},showWarningMessage(){},showErrorMessage(){}},workspace:{textDocuments:[],openTextDocument:async()=>document()},commands:{},languages:{}};
const sessions={has:value=>records.has(value),register:(value,file,kind)=>records.set(value,{file,kind}),updateSource:(value,file)=>records.set(value,{...records.get(value),file})};
Module._load=function(request,parent,main){if(request==='vscode')return vscode;if(request==='./viewer_group')return{preferredViewerColumn:()=>2,trackViewerPanel:value=>value};if(request==='./viewer_close')return{support(){},prepare:async()=>true};if(request==='./viewer_sessions')return sessions;if(request==='./launch_controls')return{launchControlsHtml:()=>'',launchControlsClientScript:()=>'',handleLaunchMessage:async()=>false};if(request==='./webview_policy')return{protect:value=>value};if(request==='./authoring_context_registry')return{currentContext:()=>null,registerCharacterToolPanel(){}};if(request==='./character_picker')return{nearestCharacterDef:()=>'',characterCandidates:()=>({current:[]}),chooseCharacterDef:async()=>undefined};return original.call(this,request,parent,main);};
(async()=>{
 const {hash}=require('../src/mutation_safety'),workspace=require('../src/hitdef_workspace'),reference={sourceHash:hash(text),index:0,defPath:''};
 const opened=await workspace.openHitDefEditor(vscode.Uri.file(source),{preset:true,reference});assert(opened,'exact source and HitDef index restore without a picker');assert.deepEqual(records.get(opened),{file:source,kind:'hitdef'});assert.match(opened.webview.html,/ikemenNavigationSelection/);opened.dispose();
 assert.equal(await workspace.openHitDefEditor(vscode.Uri.file(source),{preset:true,...{reference:{...reference,sourceHash:'changed'}}}),undefined,'changed source rejects stale HitDef preset');
 console.log('HitDef typed presets restore the exact controller and reject changed source content');
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(()=>{Module._load=original;fs.rmSync(root,{recursive:true,force:true});});
