'use strict';

const assert=require('assert');
const vm=require('vm');
const {clientScript}=require('../src/move_lab_direct_component');

class Element{
 constructor(id=''){this.id=id;this.hidden=false;this.dataset={};this.classList={toggle(){}};this.value='';this.disabled=false;this.selectionStart=0;this.selectionEnd=0;this.scrollTop=0;}
 set innerHTML(value){this._html=value;for(const match of value.matchAll(/<button[^>]*id="([^"]+)"[^>]*>/g))elements[match[1]]=new Element(match[1]);for(const match of value.matchAll(/<textarea[^>]*id="([^"]+)"[^>]*>([\s\S]*?)<\/textarea>/g)){const item=elements[match[1]]=new Element(match[1]);item.value=match[2];}for(const match of value.matchAll(/<button[^>]*data-direct-problem="([^"]+)"[^>]*>/g)){const item=new Element();item.dataset.directProblem=match[1];dynamic.push(item);}}
 get innerHTML(){return this._html||'';}
 click(){this.onclick?.();}
}
const elements={directWorkspace:new Element('directWorkspace'),moveOverview:new Element('moveOverview'),status:new Element('status'),character:new Element('character'),moveTitle:new Element('moveTitle')},layout=new Element(),dynamic=[],listeners={};
const document={querySelector:selector=>selector==='.layout'?layout:null,querySelectorAll:selector=>selector==='[data-direct-problem]'?dynamic:[],getElementById:id=>elements[id]||null};
let state={moveFormDrafts:{keep:{damage:44}},moveCodeDrafts:{keep:{text:'draft'}},selectedMove:'normal.slp',selectedFrame:3},staged=0,stopped=0,selected=[],headers=0,overview=0;
const sent=[],reference={defPath:'C:/Hero/Hero.def',kind:'hitdef',id:'c:/hero/a.zss#0',filename:'C:/Hero/a.zss',index:0,line:4,endLine:8,sourceHash:'source',rangeHash:'range',owner:null};
const item={...reference,label:'State 200 · HitDef 1',syntax:'zss',fileLabel:'a.zss',sourceText:'hitDef { damage: 30; custom.option: yes; }',hitdefValues:{damage:'30, 0','ground.hittime':'14','ground.velocity':'-4.8, 0','custom.option':'yes'},hitdefDuplicates:[],diagnostics:[],reference};
const constantsMove={id:'normal.slp',prefix:'normal.sLP',timeline:{actionNumber:200,frames:[{},{},{},{}]}};
const context={saved:{...state},model:{files:{defPath:reference.defPath,constants:'C:/Hero/constants.zss'},timingSources:{constants:'constants-hash'},moves:[constantsMove],directComponents:[item]},move:constantsMove,frame:3,document,window:{addEventListener(type,fn,capture){(listeners[type]||=[]).push({fn,capture});}},queueMicrotask:fn=>fn(),vscode:{getState:()=>state,setState:value=>state=value,postMessage:message=>sent.push(message)},moveDrafts:{stage:()=>staged++},stop:()=>stopped++,saveState(){staged++;state={...state,selectedMove:context.move?.id,selectedFrame:state.selectedFrame};},selectMove:(id,draft,frame)=>selected.push({id,frame}),moveOverviewUi:{render:()=>overview++},renderHeader:()=>headers++,$:id=>elements[id]||null,esc:value=>String(value??''),Number,String,Object,Array,Math,JSON,console};context.globalThis=context;
vm.createContext(context);vm.runInContext(clientScript(),context);const ui=vm.runInContext('moveDirectUi',context);
ui.select(reference);
assert.strictEqual(context.move,null,'direct selection replaces only the active component view');assert.strictEqual(staged,2,'the current constants draft is staged before selection and state persistence');
assert.strictEqual(layout.hidden,true);assert.match(elements.directWorkspace.innerHTML,/Source inspection/);assert.strictEqual(sent.at(-1).type,'moveIntegrationContext');
assert.match(elements.directWorkspace.innerHTML,/Authored classic HitDef values/);assert.match(elements.directWorkspace.innerHTML,/ground\.velocity/);assert.match(elements.directWorkspace.innerHTML,/custom\.option/);assert.match(elements.directWorkspace.innerHTML,/read-only here/,'field presentation delegates mutation to the guarded HitDef editor');
assert.deepStrictEqual(state.moveFormDrafts,{keep:{damage:44}});assert.deepStrictEqual(state.moveCodeDrafts,{keep:{text:'draft'}},'component switching preserves existing draft stores');
assert.strictEqual(state.directReturnReference.profileId,'normal.slp');assert.strictEqual(state.directReturnReference.frameIndex,3,'the typed return target survives refresh/reload even while no constants profile is active');assert.strictEqual(ui.modelChanged(),true);assert.deepStrictEqual(state.directComponent,reference);
elements.returnDirectConstants.onclick();assert.deepStrictEqual(selected.at(-1),{id:'normal.slp',frame:3},'returning to constants restores the selected profile and nonzero frame');
ui.select(reference);elements.editDirectHitDef.onclick();assert.strictEqual(sent.at(-1).type,'editDirectComponent');elements.openDirectSource.onclick();assert.strictEqual(sent.at(-1).type,'openDirectComponent');elements.directOverview.onclick();assert.strictEqual(overview>0,true);
const beforeInvalidReturn=selected.length;context.model={...context.model,timingSources:{constants:'changed'}};elements.returnDirectConstants.onclick();assert.strictEqual(selected.length,beforeInvalidReturn,'a changed constants return target does not fall back to another profile');assert.match(elements.status.textContent,/changed or was removed/);
assert.strictEqual(headers>0,true);assert.strictEqual(stopped>0,true);
console.log('Direct HitDef component view round-trips mixed constants state without dropping drafts or frame selection');

// State/function typing must retain the live textarea instead of rebuilding it.
const behaviorReference={defPath:reference.defPath,kind:'state',id:'behavior-200',stableId:'behavior-200',filename:reference.filename,index:0,line:0,startLine:0,endLine:3,signature:'200',sourceHash:'behavior-source',rangeHash:'behavior-range',owner:null};
const behavior={...behaviorReference,label:'StateDef 200',syntax:'zss',fileLabel:'a.zss',text:'[StateDef 200]\nctrl = 0;',sourceText:'[StateDef 200]\nctrl = 0;',diagnostics:[],controllers:[],reference:behaviorReference};
const behaviorElements={directWorkspace:new Element('directWorkspace'),moveOverview:new Element('moveOverview'),status:new Element('status'),character:new Element('character'),moveTitle:new Element('moveTitle')};Object.keys(elements).forEach(key=>delete elements[key]);Object.assign(elements,behaviorElements);let behaviorState={},renders=0,stages=[],pending=false,failedRequest=null;const draftApi={actionState:()=>({canApply:stages.length>0&&!pending,canDiscard:stages.length>0&&!pending,pending,conflict:false}),value:item=>stages.at(-1)?.value||item.text,stage:(item,value)=>stages.push({item,value}),apply:()=>{pending=true;return 1;},failed:id=>{failedRequest=id;pending=false;},discard(){},rebase(){}};const behaviorContext={saved:{},model:{files:{defPath:reference.defPath,constants:''},timingSources:{},moves:[],directComponents:[],behaviorComponents:[behavior]},move:null,frame:0,document,window:{addEventListener(){}},vscode:{getState:()=>behaviorState,setState:value=>behaviorState=value,postMessage:message=>sent.push(message)},moveDrafts:{stage(){}},stop(){},saveState(){},selectMove(){},moveOverviewUi:{render(){}},renderHeader(){renders++},codeDraftStore:draftApi,$:id=>elements[id]||null,esc:value=>String(value??''),Number,String,Object,Array,Math,JSON,console};behaviorContext.globalThis=behaviorContext;vm.createContext(behaviorContext);vm.runInContext(clientScript(),behaviorContext);const behaviorUi=vm.runInContext('moveDirectUi',behaviorContext);behaviorUi.select(behaviorReference);const liveEditor=elements.directCodeEditor;liveEditor.selectionStart=5;liveEditor.selectionEnd=5;liveEditor.scrollTop=12;liveEditor.value+='x';liveEditor.oninput();assert.strictEqual(elements.directCodeEditor,liveEditor,'typing does not replace the live textarea');assert.strictEqual(liveEditor.selectionStart,5);assert.strictEqual(liveEditor.scrollTop,12);liveEditor.value+='y';liveEditor.oninput();assert.strictEqual(stages.at(-1).value.endsWith('xy'),true,'multiple characters stage continuously in the same editor');assert.strictEqual(elements.applyDirectCode.disabled,false);elements.applyDirectCode.onclick();assert.strictEqual(elements.applyDirectCode.disabled,true);assert.doesNotThrow(()=>behaviorUi.applyFailed(1),'failed direct Apply never calls the constants-only renderer');assert.strictEqual(failedRequest,1);assert.strictEqual(elements.directCodeEditor,liveEditor,'failure retains the live editor, caret and draft');assert.strictEqual(elements.applyDirectCode.disabled,false,'failure clears pending state and enables retry');assert.match(elements.status.textContent,/draft is retained/);assert(renders>=2);

// Specialized creation sites are exact read-only selections. Opening a specialist is separate and never applies or converts source.
const specialistReference={defPath:reference.defPath,kind:'helper',id:'helper-one',stableId:'helper-one',filename:reference.filename,index:0,line:10,endLine:14,signature:'helper',sourceHash:'special-source',rangeHash:'special-range',owner:{kind:'state',signature:'200',startLine:0,endLine:20}};
const specialist={...specialistReference,label:'Helper creation site 1',syntax:'zss',fileLabel:'a.zss',sourceText:'helper {\n  pos: parent, 0;\n}',diagnostics:[],contextPath:[{kind:'condition',title:'time = 1'}],receiverHints:['Parent'],reference:specialistReference};
Object.keys(elements).forEach(key=>delete elements[key]);Object.assign(elements,{directWorkspace:new Element('directWorkspace'),moveOverview:new Element('moveOverview'),status:new Element('status'),character:new Element('character'),moveTitle:new Element('moveTitle')});let specialistState={};const specialistContext={saved:{},model:{files:{defPath:reference.defPath,constants:'',air:'C:/Hero/Hero.air'},timingSources:{},moves:[],directComponents:[],behaviorComponents:[],specialistComponents:[specialist]},move:null,frame:0,document,window:{addEventListener(){}},vscode:{getState:()=>specialistState,setState:value=>specialistState=value,postMessage:message=>sent.push(message)},moveDrafts:{stage(){}},stop(){},saveState(){},selectMove(){},moveOverviewUi:{render(){}},renderHeader(){},codeDraftStore:draftApi,$:id=>elements[id]||null,esc:value=>String(value??''),Number,String,Object,Array,Math,JSON,console};specialistContext.globalThis=specialistContext;vm.createContext(specialistContext);vm.runInContext(clientScript(),specialistContext);const specialistUi=vm.runInContext('moveDirectUi',specialistContext);specialistUi.select(specialistReference);assert.match(elements.directWorkspace.innerHTML,/does not create, convert, or rewrite code/);assert.match(elements.directWorkspace.innerHTML,/time = 1/);assert.match(elements.directWorkspace.innerHTML,/Parent/);assert.strictEqual(elements.directCodeEditor,undefined,'specialist selection does not expose the broad state/function mutation editor');elements.openSpecialistComponent.onclick();assert.strictEqual(sent.at(-1).type,'openSpecialistComponent');assert.deepStrictEqual(sent.at(-1).reference,specialistReference);elements.openComponentAir.onclick();assert.strictEqual(sent.at(-1).type,'openComponentAir','AIR access starts with an explicit action chooser instead of guessing from the component number');
