'use strict';
const assert=require('assert'),fs=require('fs'),os=require('os'),path=require('path'),Module=require('module');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'palfx-draft-')),stored={},panels=[],supports=new Map(),records=new Map(),original=Module._load;
const workspaceState={get:(key,fallback)=>stored[key]??fallback,update:async(key,value)=>{stored[key]=value;}},context={workspaceState,subscriptions:[]};
function panel(){const receive=[],dispose=[];const value={viewColumn:2,reveal(){},onDidDispose:fn=>dispose.push(fn),dispose(){dispose.forEach(fn=>fn());},webview:{cspSource:'test:',html:'',messages:[],onDidReceiveMessage:fn=>receive.push(fn),postMessage(message){this.messages.push(message);return true;}}};value.send=message=>receive.forEach(fn=>fn(message));panels.push(value);return value;}
const sessions={register:(value,file,kind)=>records.set(value,{file,kind})},vscode={ViewColumn:{Active:1},Uri:{file:fsPath=>({fsPath})},workspace:{workspaceFolders:[{uri:{fsPath:root}}]},window:{createWebviewPanel:()=>panel(),activeTextEditor:null,showWarningMessage(){},showInputBox(){}},env:{clipboard:{writeText:async()=>{}}}};
Module._load=function(request,parent,main){if(request==='vscode')return vscode;if(request==='./viewer_group')return{preferredViewerColumn:()=>2,trackViewerPanel:value=>value};if(request==='./viewer_sessions')return sessions;if(request==='./viewer_close')return{support:(value,options)=>supports.set(value,options)};if(request==='./launch_controls')return{launchControlsHtml:()=>'',launchControlsClientScript:()=>'',handleLaunchMessage:async()=>false};return original.call(this,request,parent,main);};
(async()=>{
 const workspace=require('../src/palfx_editor'),draft={page:'composer',basic:'builtIn|Fire',basicValues:[1,2,3,256,256,256,0,0,0,8,1],fx:'',profile:{name:'Recovered Fire',anim:6000,layers:[{name:'Base'}]},layerIndex:0};
 const first=workspace.openPalFxPresetEditor(context);assert.deepEqual(records.get(first),{file:root,kind:'palfx_editor'});first.send({type:'palfxDraft',revision:4,draft});await new Promise(resolve=>setImmediate(resolve));assert.deepEqual(first.webview.messages.at(-1),{type:'palfxDraftStored',revision:4});assert(!supports.get(first).isBusy());await supports.get(first).keepDraft();first.dispose();
 const reference={page:'composer',basic:'builtIn|Fire',fx:'',layerIndex:0},second=workspace.openPalFxPresetEditor(context,vscode.Uri.file(root),{preset:true,reference});assert(second);assert.match(second.webview.html,/Recovered Fire/);assert.match(second.webview.html,/ikemenCanKeepDraft/);second.send({type:'palfxDiscardDraft'});await new Promise(resolve=>setImmediate(resolve));assert.deepEqual(second.webview.messages.at(-1),{type:'palfxDraftDiscarded'});second.dispose();
 const third=workspace.openPalFxPresetEditor(context);assert.doesNotMatch(third.webview.html,/Recovered Fire/);third.dispose();assert.equal(workspace.openPalFxPresetEditor(context,vscode.Uri.file(path.dirname(root)),{preset:true,reference}),undefined,'a preset from another workspace root is rejected');
 console.log('PalFX drafts survive direct close/reopen and typed presets remain bound to the exact workspace root');
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(()=>{Module._load=original;fs.rmSync(root,{recursive:true,force:true});});
