const assert=require('assert'),fs=require('fs'),os=require('os'),path=require('path'),Module=require('module');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'ikemaker-related-owner-'));const shared=path.join(root,'shared.air'),other=path.join(root,'effects.air'),a=path.join(root,'a.def'),b=path.join(root,'b.def');
for(const file of [shared,other])fs.writeFileSync(file,'[Begin Action 0]\n0,0,0,0,1\n');for(const file of [a,b])fs.writeFileSync(file,'[Files]\nanim=shared.air\n');
let cancel=false,ownerPrompts=0,opened=[],shown=[];
const api={Uri:{file:fsPath=>({fsPath})},QuickPickItemKind:{Separator:-1},workspace:{textDocuments:[]},window:{showInformationMessage:async()=>{},showQuickPick:async(items,options)=>{if(options.title==='Choose the asset owner'){ownerPrompts++;return cancel?undefined:items.find(item=>item.filename===b);}shown=items;return items.find(item=>item.target==='air');}}};
const original=Module._load;Module._load=function(request,parent,main){if(request==='vscode')return api;if(request==='./air_viewer'&&parent?.filename.endsWith('viewer_navigation.js'))return {openAirPreview:async uri=>{opened.push(uri.fsPath);return undefined;}};return original.call(this,request,parent,main);};
(async()=>{const related=require('../src/related_work'),navigation=require('../src/viewer_navigation');await related.openRelatedWork(shared,'air');assert.equal(ownerPrompts,1,'A chosen owner must not trigger another owner prompt at handoff');assert.deepEqual(opened,[shared]);cancel=true;await related.openRelatedWork(shared,'air');assert.equal(opened.length,1,'Cancelling owner selection must not fall back to a nearest DEF');
const resolve=navigation.resolveOwner;navigation.resolveOwner=async()=>({def:b,inherited:{ownerDef:b,prefix:'fx',record:{air:other,source:'shared fixture'}}});await related.openRelatedWork(shared,'air');assert.equal(opened.at(-1),other);assert.equal(shown.find(item=>item.target==='air').filename,other,'Picker identity must match the inherited shared archive');navigation.resolveOwner=resolve;
console.log('Related Work preserves chosen/shared owners and cancellation through the same viewer routing path');})().catch(error=>{console.error(error);process.exitCode=1;}).finally(()=>{Module._load=original;assert(path.resolve(root).startsWith(path.resolve(os.tmpdir())+path.sep+'ikemaker-related-owner-'));fs.rmSync(root,{recursive:true,force:true});});
