'use strict';
const assert=require('assert'),fs=require('fs'),os=require('os'),path=require('path'),Module=require('module');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'screenpack-draft-')),file=path.join(root,'system.def'),text='[Info]\nname=Draft UI\nlocalcoord=320,240\n[Files]\nspr=missing.sff\n[Title Info]\nmenu.pos=160,120\n';fs.writeFileSync(file,text);
const original=Module._load,stored={},supports=new Map(),records=new Map(),commands=new Map(),panels=[];const workspaceState={get:(key,fallback)=>stored[key]??fallback,update:async(key,value)=>{stored[key]=value;}};
function panel(){const receive=[],dispose=[];const value={viewColumn:2,reveal(){},onDidDispose:fn=>dispose.push(fn),dispose(){dispose.forEach(fn=>fn());},webview:{cspSource:'test:',html:'',options:{},messages:[],onDidReceiveMessage:fn=>{receive.push(fn);return{dispose(){}};},postMessage(message){this.messages.push(message);return true;}}};value.send=message=>receive.forEach(fn=>fn(message));panels.push(value);return value;}
const vscode={ViewColumn:{Active:1,One:1},Uri:{file:fsPath=>({fsPath})},workspace:{getConfiguration:()=>({get:(_,fallback)=>fallback}),textDocuments:[]},commands:{registerCommand:(id,fn)=>{commands.set(id,fn);return{};}},window:{activeTextEditor:null,createWebviewPanel:()=>panel(),registerWebviewPanelSerializer:()=>({}),showErrorMessage:message=>{throw Error(message);},showWarningMessage(){}}};
const sessions={has:value=>records.has(value),register:(value,source,kind)=>records.set(value,{source,kind}),updateSource:(value,source)=>records.set(value,{...records.get(value),source})};
Module._load=function(request,parent,main){if(request==='vscode')return vscode;if(request==='./viewer_group')return{preferredViewerColumn:()=>2,revealInViewerGroup:value=>value.reveal(),trackViewerPanel:value=>value};if(request==='./viewer_sessions')return sessions;if(request==='./viewer_close')return{support:(value,options)=>supports.set(value,options)};if(request==='./authoring_context_registry')return{registerAuthoringPanel(){}};if(request==='./launch_controls')return{launchControlsHtml:()=>'',launchControlsClientScript:()=>'',handleLaunchMessage:async()=>false};if(request==='./webview_policy')return{protect:value=>value};return original.call(this,request,parent,main);};
(async()=>{
 const {hash}=require('../src/mutation_safety'),workspace=require('../src/screenpack_workspace');workspace.registerScreenpackWorkspace({workspaceState,subscriptions:[]});const sourceHash=hash(text),first=await workspace.openUiWorkspace(vscode.Uri.file(file));assert(first);assert.deepEqual(records.get(first),{source:file,kind:'screenpack'});
 first.send({type:'screenpackDraft',revision:7,draft:{sourceHash,overrides:{'0:0':[171,133]},grid:{}}});await new Promise(resolve=>setImmediate(resolve));assert.deepEqual(first.webview.messages.at(-1),{type:'screenpackDraftStored',revision:7});await supports.get(first).keepDraft();first.dispose();
 const reference={workspaceMode:'screenpack',sourceHash,screen:'title info',element:'menu',profile:0,aspect:'16:9',guides:true,visible:{'-1':true,0:true,1:true,2:true}},second=await workspace.openUiWorkspace(vscode.Uri.file(file),{preset:true,reference});assert(second);assert.match(second.webview.html,/171/);assert.match(second.webview.html,/ikemenCanKeepDraft/);second.send({type:'screenpackDiscardDraft'});await new Promise(resolve=>setImmediate(resolve));assert.doesNotMatch(second.webview.html,/"0:0":\[171,133\]/);second.dispose();
 fs.appendFileSync(file,'; changed\n');assert.equal(await workspace.openUiWorkspace(vscode.Uri.file(file),{preset:true,reference}),undefined,'changed screenpack source rejects a stale preset');
 console.log('Screenpack preview drafts survive close/reopen and typed presets reject changed DEF sources');
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(()=>{Module._load=original;fs.rmSync(root,{recursive:true,force:true});});
