'use strict';

const assert = require('assert');
const vm = require('vm');
const Module = require('module');
const originalLoad = Module._load;
Module._load = function patched(request, parent, isMain) { if (request === 'vscode') return {}; return originalLoad.call(this, request, parent, isMain); };
const { organizedViewerHtml } = require('../src/snd_viewer');
const { workspaceExperience } = require('../src/experience_model');
Module._load = originalLoad;

const html = organizedViewerHtml({ basename: 'Ryu_en.snd', filename: 'Ryu_en.snd', version: '1.0', entries: [{ archiveIndex: 0, group: 200, index: 0, identity: '200,0', name: 'sLP voice', category: 'Voice · Normals and General', valid: true, durationSeconds: .2, sampleRate: 44100, channels: 1, bitsPerSample: 16, format: 1, dataSize: 100, duplicateOf: null }], groups: [{ group: 200, count: 1 }], issues: [], profile: { filename: '.ikemen-sound-profile.json', characterId: 'RYU', definition: { id: 'en', role: 'voice', prefix: 'RYUEN' }, validation: { errors: [], warnings: [] } } });
const scripts = [...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)];
assert.strictEqual(scripts.length, 1);
assert.doesNotThrow(() => new vm.Script(scripts[0][1]));
for (const id of ['soundSort','groups','entries','markVisibleSounds','clearSoundMarks','soundSelectionStatus','wave','audio','freqAudition','profile','nameEvent','exportMarked','openProfile','assignArchive','generateFx','generateAllFx','copyDefLine','auditContract','createBuild','openManifest','sortManifest','rebuild','replace','add','soundBridgeKind','copySoundBridge','scanReferences']) assert(html.includes(`id="${id}"`), `missing ${id}`);
assert(html.includes('function soundSelectionStatus()'));
assert(!html.includes('id="delete"'));
assert(html.includes('webviewSection":"sndEntries'));
assert(html.includes("event.key==='Delete'"));
assert(html.includes('A combined fallback archive is not generated.'));
assert(html.includes('manifest/profile direct save'));
assert(html.includes('SND · Learning'));
assert(html.includes('<details open><summary><b>What am I editing?</b>'));
assert(html.includes('class="guided-workflow"'));
assert(html.includes('details class="task-recipes" open'));
assert(html.includes('Validate the split-archive contract'));
assert(html.includes('[Done] Load and preview the SND archive'));
assert(html.includes('data-workflow-action="control:openProfile"'));
assert(html.includes("closest('[data-workflow-action]')"));
assert(!html.includes('Advanced shortcuts'));
const advancedHtml = organizedViewerHtml({ basename: 'Ryu_fx.snd', filename: 'Ryu_fx.snd', version: '1.0', entries: [], groups: [], issues: [], profile: {}, experience: workspaceExperience('snd', 'advanced') });
assert(advancedHtml.includes('SND · Advanced'));
assert(!advancedHtml.includes('<details open><summary><b>What am I editing?</b>'));
assert(advancedHtml.includes('class="guided-workflow"'));
assert(advancedHtml.includes('details class="task-recipes"'));
assert(!advancedHtml.includes('details class="task-recipes" open'));
assert(advancedHtml.includes('Advanced shortcuts'));
assert(advancedHtml.includes('data-workflow-action="control:exportMarked"'));
console.log('SND viewer HTML tests passed');
