'use strict';
const assert = require('assert');
const fs = require('fs'); const os = require('os'); const path = require('path'); const Module = require('module');
const vscode = { window: { activeTextEditor: null }, workspace: { textDocuments: [], getConfiguration: () => ({ get: (_k, d) => d }) }, languages: { getDiagnostics: () => [] }, ViewColumn: { Active: 1 }, commands: {}, Uri: { file: (fsPath) => ({ fsPath }) } };
const original = Module._load; Module._load = function(request, parent, main) { if (request === 'vscode') return vscode; return original.call(this, request, parent, main); };
const workspace = require('../src/spatial_composer_workspace'); Module._load = original;
const model = { context: { project: 'Test', character: 'Hero' }, mode: 'explod', plan: require('../src/spatial_authoring_model').newExplod(), generated: { valid: true, issues: [], code: 'explod{}' }, visual: { state: 'unavailable', actions: [] }, sources: [] };
const html = workspace.page(model);
new (require('vm').Script)(html.match(/<script>([\s\S]*)<\/script>/)[1]);
assert(workspace.insertionIssue('# heading\n\n[StateDef 1]\n\nposSet{x: 0}\n', 'move.zss', 1));
assert(workspace.insertionIssue('[Function foo(\narg)]\n\n', 'move.zss', 1));
assert(workspace.insertionIssue('[StateDef 1]\nposSet{x: 0}\n', 'move.zss', 1));
assert.strictEqual(workspace.insertionIssue('[StateDef 1]\n\n', 'move.zss', 1), '');
assert.strictEqual(workspace.insertionIssue('[Function foo(\narg)]\n\n', 'move.zss', 2), '');
assert.strictEqual(workspace.insertionIssue('[Statedef 1]\n', 'move.cns', 1), '');
assert(workspace.insertionIssue('[StateDef 1]\nHitDef {\n\n}\n', 'move.zss', 2));
assert(workspace.insertionIssue('[StateDef 1]\nif time = 0 { Explod {\n\n}\n}', 'move.zss', 2));
assert(workspace.insertionIssue('[StateDef 1]\nExplod\n\n{\n}', 'move.zss', 2));
assert.strictEqual(workspace.insertionIssue('[StateDef 1]\nif time = 0 {\n\n}', 'move.zss', 2), '');
assert.strictEqual(workspace.insertionIssue('[Function sample()]\nif time = 0 {\nDisplayToClipboard {text: "# { }";}\n\n}', 'move.zss', 3), '');
assert.strictEqual(workspace.insertionIssue('[StateDef 1]\nExplod { anim: 0; } # { ignored\n\n', 'move.zss', 2), '');
assert(workspace.insertionIssue('[StateDef 1]\nif time = 0 {\n}\n\n# branch comment\nelse {\n}', 'move.zss', 3));
assert(workspace.insertionIssue('[StateDef 1]\nif time = 0 {\n}\n\nelse if time = 1 {\n}', 'move.zss', 3));
assert.strictEqual(workspace.insertionIssue('[StateDef 1]\nswitch time {\ncase 0:\n\n}', 'move.zss', 3), '');
assert.strictEqual(workspace.insertionIssue('[StateDef 1]\nswitch time {\ncase 0: if time = 0 {\n\n}\ndefault: PosSet {x:0;}\n}', 'move.zss', 3), '');
assert(workspace.insertionIssue('[StateDef 1]\nswitch time {\n\ncase 0: PosSet{x:0;}\n}', 'move.zss', 2));
assert.match(html, /Explod Composer/); assert.match(html, /Position & Camera/); assert.match(html, /Mouse wheel zooms/); assert.match(html, /Insert at cursor/); assert.match(html, /Advanced IKEMEN options/); assert.match(html, /Shift-drag pans/); assert.match(html, /data-ikemen-launch="training"/);
assert.match(html, /Discard recovered plan/); assert.match(html, /spatialDraft/); assert.match(html, /ikemenNavigationSelection/); assert.match(html, /ikemenPresetCapture/);
const spatial = require('../src/spatial_authoring_model');
const rejected = workspace.generatedInsertion('explod', spatial.newExplod({ transparency: 'add; RemoveExplod' }));
assert.strictEqual(rejected.valid, false);
const accepted = workspace.generatedInsertion('explod', spatial.newExplod({ language: 'cns', transparency: 'subadd' }));
assert.strictEqual(accepted.valid, true);
assert.match(accepted.code, /trans = subadd/);
(async () => {
  const writes = [], warnings = [];
  const services = { insert: async (_owner, source, code) => writes.push({ source, code }), warn: async (message) => warnings.push(message) };
  const validOwner = { mode: 'explod', plan: spatial.newExplod({ language: 'cns', id: 12 }), model: {}, disposed: true };
  const reviewed = workspace.generatedInsertion(validOwner.mode, validOwner.plan).code;
  assert.strictEqual(await workspace.insertReviewedGeneration(validOwner, { source: 'move.cns', code: 'spoofed' }, services), false);
  assert.strictEqual(writes.length, 0);
  assert.strictEqual(await workspace.insertReviewedGeneration(validOwner, { source: 'move.cns', code: reviewed }, services), true);
  assert.strictEqual(writes.length, 1);
  assert.strictEqual(writes[0].code, reviewed);
  const staleReviewed = reviewed;
  validOwner.plan = spatial.newExplod({ language: 'cns', id: 13 });
  assert.strictEqual(await workspace.insertReviewedGeneration(validOwner, { source: 'move.cns', code: staleReviewed }, services), false);
  assert.strictEqual(writes.length, 1);
  const invalidOwner = { mode: 'explod', plan: spatial.newExplod({ transparency: 'add; RemoveExplod' }), model: {}, disposed: true };
  assert.strictEqual(await workspace.insertReviewedGeneration(invalidOwner, { source: 'move.cns', code: 'anything' }, services), false);
  assert.strictEqual(writes.length, 1);
  assert(warnings.some((message) => /changed after/.test(message)));
  assert(warnings.some((message) => /generator errors/.test(message)));
  console.log('Spatial Composer workspace tests passed');
})().catch((error) => { console.error(error); process.exitCode = 1; });
