'use strict';
const assert=require('assert'),fs=require('fs'),os=require('os'),path=require('path'),Module=require('module');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'ikemaker-spatial-draft-')),stored={},supports=new Map(),records=new Map(),commands=new Map(),panels=[];
const workspaceState={get:(key,fallback)=>stored[key]??fallback,update:async(key,value)=>{stored[key]=value;}};
function panel(){const receive=[],dispose=[];const value={viewColumn:2,reveal(){},onDidDispose:fn=>dispose.push(fn),dispose(){dispose.forEach(fn=>fn());},webview:{cspSource:'test:',html:'',messages:[],onDidReceiveMessage:fn=>{receive.push(fn);return{dispose(){}};},postMessage(message){this.messages.push(message);return true;}}};value.send=async message=>{for(const fn of receive)await fn(message);};panels.push(value);return value;}
const vscode={ViewColumn:{Active:1},Uri:{file:fsPath=>({fsPath})},workspace:{textDocuments:[]},commands:{registerCommand:(id,fn)=>{commands.set(id,fn);return{};},executeCommand:async()=>undefined},env:{clipboard:{writeText:async()=>{}}},window:{activeTextEditor:null,visibleTextEditors:[],createWebviewPanel:()=>panel(),showErrorMessage:message=>{throw Error(message);},showWarningMessage(){},showInformationMessage(){}}};
const original=Module._load;
Module._load=function(request,parent,main){const from=parent?.filename||'';if(request==='vscode')return vscode;if(request==='./character_picker'&&/spatial_composer_workspace/.test(from))return{nearestCharacterDef:value=>/\.def$/i.test(value)&&fs.existsSync(value)?value:'',chooseCharacterDef:async()=>''};if(request==='./related_work'&&/spatial_composer_workspace/.test(from))return{resolveAssigned:def=>({code:[path.join(path.dirname(def),'states.zss')]})};if(request==='./move_lab_model'&&/spatial_composer_workspace/.test(from))return{contextLabel:def=>({project:'Test',character:path.basename(path.dirname(def))})};if(request==='./move_lab_workspace'&&/spatial_composer_workspace/.test(from))return{visualModel:(_def,action)=>({state:'ready',actions:[{number:0,frames:1},{number:100,frames:1}],p1Action:Number.isInteger(action)?action:0,p1:{frames:[]}})};if(request==='./viewer_group'&&/spatial_composer_workspace/.test(from))return{preferredViewerColumn:()=>2,trackViewerPanel:value=>value,revealInViewerGroup:()=>{}};if(request==='./authoring_context_registry'&&/spatial_composer_workspace/.test(from))return{registerCharacterToolPanel(){}};if(request==='./launch_controls'&&/spatial_composer_workspace/.test(from))return{launchControlsHtml:()=>'',launchControlsClientScript:()=>'',handleLaunchMessage:async()=>false};if(request==='./webview_policy'&&/spatial_composer_workspace/.test(from))return{protect:value=>value};if(request==='./viewer_sessions'&&/spatial_composer_workspace/.test(from))return{register:(value,source,kind)=>records.set(value,{source,kind})};if(request==='./viewer_close'&&/spatial_composer_workspace/.test(from))return{support:(value,options)=>supports.set(value,options)};return original.call(this,request,parent,main);};
(async()=>{try{
 const make=name=>{const folder=path.join(root,name);fs.mkdirSync(folder);const def=path.join(folder,`${name}.def`);fs.writeFileSync(def,'[Info]\nname='+name+'\n[Files]\nst=states.zss\n');fs.writeFileSync(path.join(folder,'states.zss'),'[StateDef 0]\n');return def;};
 const a=make('A'),b=make('B'),workspace=require('../src/spatial_composer_workspace');workspace.registerSpatialComposer({workspaceState,subscriptions:[]});const openExplod=commands.get('ikemen.explodComposer.open'),openPosition=commands.get('ikemen.positionCamera.open');
 const first=await openExplod(vscode.Uri.file(a));assert(first);assert.deepEqual(records.get(first),{source:a,kind:'spatial_composer'});assert(supports.has(first));
 await first.send({type:'spatialDraft',revision:4,draft:{mode:'explod',plan:{name:'Recovered flare',anim:100,position:[17,9]},action:100}});assert(first.webview.messages.some(message=>message.type==='spatialDraftStored'&&message.revision===4));await supports.get(first).keepDraft();first.dispose();
 const restored=await openExplod(vscode.Uri.file(a),{preset:true,reference:{defPath:a,mode:'explod',action:100}});assert.match(restored.webview.html,/Recovered flare/);assert.match(restored.webview.html,/Discard recovered plan/);
 await restored.send({type:'mode',mode:'position'});await restored.send({type:'spatialDraft',revision:5,draft:{mode:'position',plan:{name:'Recovered placement',position:[33,44]},action:0}});restored.dispose();
 const position=await openPosition(vscode.Uri.file(a),{preset:true,reference:{defPath:a,mode:'position',action:0}});assert.match(position.webview.html,/Recovered placement/);position.dispose();
 const explodAgain=await openExplod(vscode.Uri.file(a),{preset:true,reference:{defPath:a,mode:'explod',action:100}});assert.match(explodAgain.webview.html,/Recovered flare/);await explodAgain.send({type:'discardSpatialDraft'});explodAgain.dispose();
 const clean=await openExplod(vscode.Uri.file(a),{preset:true,reference:{defPath:a,mode:'explod',action:100}});assert.doesNotMatch(clean.webview.html,/Recovered flare/);const other=await openExplod(vscode.Uri.file(b));assert(other&&other!==clean,'different characters retain separate panels');assert.strictEqual(await openExplod(vscode.Uri.file(a)),clean,'the same character reuses its panel');
 const before=panels.length;assert.strictEqual(await openExplod(vscode.Uri.file(b),{preset:true,reference:{defPath:b,mode:'bad',action:0}}),undefined);assert.strictEqual(panels.length,before,'invalid mode is rejected before panel creation');assert.strictEqual(await openExplod(vscode.Uri.file(b),{preset:true,reference:{defPath:b,mode:'explod',action:999}}),undefined,'missing action is rejected');
 clean.dispose();other.dispose();assert(workspace.validSpatialReference({defPath:a,mode:'explod',action:100},a,{visual:{actions:[{number:100}]}}));console.log('Spatial Composer drafts remain character/mode-bound and typed presets reject stale selections');
 }finally{Module._load=original;fs.rmSync(root,{recursive:true,force:true});}})().catch(error=>{console.error(error);process.exitCode=1;});
