'use strict';
const assert=require('assert'),Module=require('module'),fs=require('fs'),os=require('os'),path=require('path');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'storyboard-lifecycle-'));
const filename=path.join(root,'credits.def');
fs.writeFileSync(filename,'[SceneDef]\nspr = credits.sff\n[Scene 0]\nend.time = 180\nclearcolor = 0,0,0\n');
const panels=[],errors=[],sourceRequests=[];let serializer,pickLayer;
function makePanel(){const disposal=[],listeners=[];const p={active:true,viewColumn:1,webview:{html:'',postMessage:async()=>true,onDidReceiveMessage(fn){listeners.push(fn);p.receive=m=>Promise.all(listeners.map(listener=>listener(m)));return {dispose(){p.listenerDisposed=true}}}},onDidChangeViewState(){},onDidDispose(fn){disposal.push(fn)},reveal(){p.revealed=true},dispose(){p.disposed=true;disposal.forEach(fn=>fn())}};panels.push(p);return p;}
const vscode={Uri:{file:fsPath=>({fsPath})},ViewColumn:{Active:1,One:1},workspace:{textDocuments:[],getConfiguration:()=>({get:(key,fallback)=>fallback})},window:{createWebviewPanel:makePanel,showQuickPick:()=>pickLayer,showInputBox:async()=>'0,0',showWarningMessage:async()=>'Remove Scene',showErrorMessage:x=>{errors.push(x);return new Promise(()=>{})},registerWebviewPanelSerializer(type,value){serializer=value;return {dispose(){}}}},commands:{registerCommand(){return {dispose(){}}}}};
const original=Module._load;
Module._load=function(name,parent,main){if(name==='vscode')return vscode;if(name==='./viewer_navigation'&&parent.filename.endsWith('storyboard_workspace.js'))return {currentPoint:(filename,kind,message,panel)=>({filename,kind,panel}),openViewerSource:async(...args)=>sourceRequests.push(args)};return original.call(this,name,parent,main)};
const api=require('../src/storyboard_workspace');Module._load=original;
(async()=>{try{
  api.registerStoryboardWorkspace({subscriptions:[]});
  assert.equal(await api.openStoryboardWorkspace({fsPath:filename}),panels[0]);assert.equal(panels.length,1);
  assert.equal(await api.openStoryboardWorkspace({fsPath:filename}),panels[0]);assert.equal(panels.length,1);assert(panels[0].revealed);
  const first=panels[0];
  await first.receive({type:'source',line:2});assert.equal(sourceRequests.length,1);assert.equal(sourceRequests[0][0],filename);assert.equal(sourceRequests[0][1],2);assert.equal(sourceRequests[0][2].kind,'storyboard');assert.equal(sourceRequests[0][2].panel,first);
  const originalText=fs.readFileSync(filename,'utf8');
  await first.receive({type:'apply',line:2,duration:'1.5',color:'0,0,0'});assert(errors.pop().includes('positive whole'));assert.equal(fs.readFileSync(filename,'utf8'),originalText);
  await first.receive({type:'apply',line:2,duration:'180',color:'0,256,0'});assert(errors.pop().includes('0 to 255'));assert.equal(fs.readFileSync(filename,'utf8'),originalText);
  fs.appendFileSync(filename,'; external edit\n');const changed=fs.readFileSync(filename,'utf8');
  await first.receive({type:'addScene'});assert(errors.pop().includes('changed outside'));assert.equal(fs.readFileSync(filename,'utf8'),changed);
  await first.receive({type:'refresh'});assert(first.webview.html.includes('external')===false);
  vscode.workspace.textDocuments=[{isDirty:true,uri:{fsPath:filename}}];await first.receive({type:'addScene'});assert(errors.pop().includes('unsaved DEF'));assert.equal(fs.readFileSync(filename,'utf8'),changed);vscode.workspace.textDocuments=[];
  const draft={baseDuration:'180',baseColor:'0,0,0',duration:'240',color:'1,2,3'};await first.receive({type:'sceneDraft',sceneNumber:0,draft});assert.deepEqual(api.payload(filename).drafts[0],draft);
  first.dispose();assert(first.listenerDisposed);
  const restored=makePanel();await serializer.deserializeWebviewPanel(restored,{filename,selected:1});assert(!restored.disposed);assert(restored.webview.html.includes('vscode.getState()'));assert.deepEqual(api.payload(filename).drafts[0],draft,'direct close/reopen retains the scene draft');
  await restored.receive({type:'apply',line:2,sceneNumber:0,draft,duration:draft.duration,color:draft.color});assert.equal(api.payload(filename).model.scenes[0].endTime,240);assert.equal(api.payload(filename).drafts[0],undefined,'successful save clears the submitted draft');
  await api.openStoryboardWorkspace({fsPath:filename});assert.equal(panels.length,2);assert(restored.revealed);
  restored.dispose();await api.openStoryboardWorkspace({fsPath:filename});assert.equal(panels.length,3);
  assert.deepEqual(api.validateSceneValues('181',' 1, 2, 3 '),{duration:'181',color:'1,2,3'});
  const current=panels[2],draft2={baseDuration:'240',baseColor:'1,2,3',duration:'300',color:'1,2,3'};await current.receive({type:'sceneDraft',sceneNumber:0,draft:draft2});
  await current.receive({type:'removeScene',line:2});assert.equal(api.payload(filename).model.scenes.length,0);assert.equal(api.payload(filename).drafts[0],undefined);await current.receive({type:'addScene'});assert.equal(api.payload(filename).drafts[0],undefined,'reusing the deleted scene number must not resurrect its draft');
  let release;pickLayer=new Promise(resolve=>{release=resolve;});const line=api.payload(filename).model.scenes[0].line,originalLayerText=fs.readFileSync(filename,'utf8');
  const pending=current.receive({type:'addLayer',line});await new Promise(resolve=>setImmediate(resolve));
  assert.equal(await require('../src/viewer_close').prepare([current],{window:{showInformationMessage:async()=>{},showWarningMessage:async()=>{throw Error('busy storyboard must not offer discard');}}}),false);
  vscode.workspace.textDocuments=[{isDirty:true,uri:{fsPath:filename}}];release({value:'sprite'});await pending;assert(errors.pop().includes('now has unsaved edits'));assert.equal(fs.readFileSync(filename,'utf8'),originalLayerText);vscode.workspace.textDocuments=[];
  pickLayer=new Promise(resolve=>{release=resolve;});const closing=current.receive({type:'addLayer',line});await new Promise(resolve=>setImmediate(resolve));current.dispose();release({value:'sprite'});await closing;assert.equal(fs.readFileSync(filename,'utf8'),originalLayerText,'closing during the picker must not commit afterwards');
  assert.equal(errors.length,0);console.log('Storyboard lifecycle, validation, dirty source, and stale file tests passed');
}finally{fs.rmSync(root,{recursive:true,force:true})}})().catch(error=>{console.error(error);process.exitCode=1});
