'use strict';
const assert=require('assert'),vm=require('vm');
const {clientScript}=require('../src/storyboard_navigation');
const model={scenes:[{number:2,endTime:180,clearColor:[0,0,0]},{number:7,endTime:90,clearColor:[1,2,3]}]};
const fields={duration:{value:'180'},color:{value:'0,0,0'}};let renders=0;
const context={model,selected:0,$:id=>fields[id]};
context.current=()=>model.scenes[context.selected];
context.render=()=>{renders++;const scene=context.current();fields.duration.value=String(scene.endTime);fields.color.value=scene.clearColor.join(',');};
vm.createContext(context);vm.runInContext(clientScript(),context);
assert.equal(context.ikemenNavigationSelection().sceneNumber,2);
fields.duration.value='201';
assert(context.ikemenCanRestoreNavigation({sceneNumber:2}));context.ikemenRestoreNavigation({sceneNumber:2});
assert.equal(fields.duration.value,'201');assert.equal(renders,0,'same-scene return preserves the draft');
assert.equal(context.ikemenCanRestoreNavigation({sceneNumber:7}),false);
assert.throws(()=>context.ikemenRestoreNavigation({sceneNumber:7}),/unapplied/);assert.equal(context.selected,0);
fields.duration.value='180';assert(context.ikemenCanRestoreNavigation({sceneNumber:7}));context.ikemenRestoreNavigation({sceneNumber:7});
assert.equal(context.selected,1);assert.equal(fields.color.value,'1,2,3');assert.equal(renders,1);
assert.equal(context.ikemenCanRestoreNavigation({sceneNumber:99}),false);
model.scenes.push({...model.scenes[1]});assert.equal(context.ikemenCanRestoreNavigation({sceneNumber:7}),false,'duplicate scene numbers are ambiguous');
console.log('Storyboard exact scene restore, same-scene draft preservation, dirty veto and ambiguous target tests passed');
