'use strict';
const assert = require('assert');
const tickets = require('../src/team_ticket_model');

let board = tickets.normalizeBoard({ project: 'JNP', tickets: [] });
assert.ok(board.roles.includes('CS')); assert.ok(board.roles.includes('Voice')); assert.ok(!board.roles.includes('Spriter'));
board = tickets.createTicket(board, { title: 'Build All Characters', type: 'Epic' }, 'JNP');
const epic = board.tickets[0];
assert.throws(() => tickets.addSubtask(board, epic.id, 'Wrong level'), /child tickets/);
board = tickets.createTicket(board, { title: 'Build Ryu', type: 'Character', parentId: epic.id, character: 'Ryu' }, 'JNP');
const ryu = board.tickets[1];
board = tickets.addSubtask(board, ryu.id, 'Set up sprites', 'Artist');
board = tickets.addSubtask(board, ryu.id, 'Test the character', 'Tester');
assert.strictEqual(tickets.completion(board, epic).remainingChildren, 1);
assert.throws(() => tickets.updateTicket(board, epic.id, { column: 'done' }), /child ticket/);
assert.throws(() => tickets.updateTicket(board, ryu.id, { column: 'done' }), /2 task/);
for (const task of board.tickets[1].subtasks) board = tickets.updateSubtask(board, ryu.id, task.id, { done: true });
board = tickets.updateTicket(board, ryu.id, { column: 'done' });
board = tickets.updateTicket(board, epic.id, { column: 'done' });
assert.strictEqual(tickets.completion(board, epic).canClose, true);
board = tickets.updateTicket(board, ryu.id, { column: 'testing' });
assert.strictEqual(board.tickets.find((ticket) => ticket.id === epic.id).column, 'review');
assert.strictEqual(tickets.descendants(board, epic.id).length, 1);
const pasted = tickets.ticketFromFeedback('Fireballs clash incorrectly\nObserved with Ryu versus Ken.');
assert.strictEqual(pasted.column, 'discussion'); assert.match(pasted.description, /Ryu versus Ken/);
board = tickets.addMember(board, { name: 'Iced', handle: 'Iced', roles: ['QA'] });
board = tickets.addMember(board, { name: 'Voice Actor', handle: 'VoiceActor', roles: ['Voice'] });
assert.throws(() => tickets.addMember(board, { name: 'Duplicate', handle: 'Iced' }), /already exists/);
board = tickets.addComment(board, ryu.id, '@Iced please verify this. @Voice please listen.', 'JNP');
assert.strictEqual(tickets.inbox(board, 'Iced').length, 1); assert.strictEqual(tickets.inbox(board, 'Voice Actor').length, 1);
board = tickets.markNotificationsRead(board, 'Iced'); assert.strictEqual(tickets.inbox(board, 'Iced').length, 0);
board = tickets.addMember(board, { name: 'Local Historian', handle: 'Local', roles: ['QA'] });
board = tickets.syncDirectory(board, { name: 'Assigned Team', jobClasses: ['Writer'], members: [{ name: 'Iced Updated', handle: 'Iced', jobClasses: ['Director'], active: true }, { name: 'New Animator', handle: 'Anim', jobClasses: ['Animator'], active: false }] });
assert.ok(board.roles.includes('Writer'));
assert.strictEqual(board.team.find((member) => member.handle === 'Iced').name, 'Iced Updated');
assert.deepStrictEqual(board.team.find((member) => member.handle === 'Iced').roles, ['Director']);
assert.strictEqual(board.team.find((member) => member.handle === 'Anim').active, false);
assert.ok(board.team.some((member) => member.handle === 'Local'), 'registry import must preserve local-only history');
board = tickets.submitReport(board, { title: 'Bad collision', body: 'Fireballs overlap.', reporter: 'Iced', attachments: ['bug.png'] });
const report = board.reports[0]; board = tickets.reviewReport(board, report.id, 'accepted', { type: 'Bug', reason: 'Reproduced' }, 'JNP');
assert.strictEqual(board.reports[0].status, 'accepted'); assert.strictEqual(board.tickets.at(-1).type, 'Bug'); assert.ok(board.tickets.at(-1).watchers.includes('Iced'));
const issue = { title: 'Crop affects another group', body: 'Observed during scope testing.', project: 'SF6 test project', character: 'Ryu', severity: 'High', build: '0.75.29', steps: '1. Open archive\n2. Crop group 0', expected: 'Group 1 remains unchanged.', actual: 'Group 1 changed.', attachments: ['evidence/crop.png'] };
let issueBoard = tickets.submitReport(tickets.normalizeBoard({ project: 'SF6 test project' }), { ...issue, reporter: 'Tester' });
issueBoard = tickets.normalizeBoard(JSON.parse(JSON.stringify(issueBoard)));
issueBoard = tickets.reviewReport(issueBoard, issueBoard.reports[0].id, 'accepted', { type: 'Bug' }, 'Reviewer');
issueBoard = tickets.updateTicket(issueBoard, issueBoard.tickets[0].id, { column: 'testing' });
const savedIssue = tickets.normalizeBoard(JSON.parse(JSON.stringify(issueBoard))).tickets[0];
for (const field of ['project', 'character', 'severity', 'build', 'steps', 'expected', 'actual', 'attachments']) assert.deepStrictEqual(savedIssue[field], issue[field], field + ' survives report conversion, editing and reload');
const directIssue = tickets.createTicket({ project: 'Other project' }, { title: 'Direct issue', type: 'Bug', steps: 'Open screen' }, 'Tester').tickets[0];
assert.strictEqual(directIssue.project, 'Other project');
assert.strictEqual(directIssue.severity, 'Untriaged');
assert.strictEqual(tickets.normalizeBoard({ tickets: [{ title: 'Legacy' }] }).tickets[0].steps, '', 'legacy boards remain readable');
console.log('Team ticket model tests passed');

const identityModel=require('../src/team_ticket_model');
let identityBoard=identityModel.submitReport({project:'Game'},{title:'Rename test',body:'Details',project:'Old name',workProjectId:'stable-work',gameProjectId:'stable-game'});
identityBoard=identityModel.reviewReport(identityBoard,identityBoard.reports[0].id,'accepted',{},'Reviewer');
identityBoard=identityModel.normalizeBoard(JSON.parse(JSON.stringify(identityBoard)));
assert.strictEqual(identityBoard.tickets[0].workProjectId,'stable-work');assert.strictEqual(identityBoard.tickets[0].gameProjectId,'stable-game');
identityBoard=identityModel.updateTicket(identityBoard,identityBoard.tickets[0].id,{project:'Renamed project'},'Reviewer');
assert.strictEqual(identityBoard.tickets[0].workProjectId,'stable-work');
console.log('Stable project IDs survive report acceptance, persistence and project-name changes');
