'use strict';
const assert=require('assert'),fs=require('fs'),os=require('os'),path=require('path'),Module=require('module');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'ikemaker-throw-draft-')),stored={},supports=new Map(),records=new Map(),commands=new Map(),panels=[];
const workspaceState={get:(key,fallback)=>stored[key]??fallback,update:async(key,value)=>{stored[key]=value;}};
function panel(){const receive=[],dispose=[];const value={viewColumn:2,reveal(){},onDidDispose:fn=>dispose.push(fn),dispose(){dispose.forEach(fn=>fn());},webview:{cspSource:'test:',html:'',messages:[],onDidReceiveMessage:fn=>{receive.push(fn);return{dispose(){}};},postMessage(message){this.messages.push(message);return true;}}};value.send=async message=>{for(const fn of receive)await fn(message);};panels.push(value);return value;}
const vscode={ViewColumn:{Active:1,Beside:2},Uri:{file:fsPath=>({fsPath}),joinPath:(base,...rest)=>({fsPath:path.join(base.fsPath,...rest)})},workspace:{textDocuments:[]},commands:{registerCommand:(id,fn)=>{commands.set(id,fn);return{};},executeCommand:async()=>undefined},window:{createWebviewPanel:()=>panel(),showErrorMessage:message=>{throw Error(message);}}};
const original=Module._load;
Module._load=function(request,parent,main){const from=parent?.filename||'';if(request==='vscode')return vscode;if(request==='./character_picker'&&/throw_creator_workspace/.test(from))return{chooseCharacterDef:async uri=>uri?.fsPath||''};if(request==='./sff_reader'&&/throw_creator_workspace/.test(from))return{readSff:()=>({sprites:[],palettes:[{group:1,number:1,colors:0}]}),spriteDataUri:()=>''};if(request==='./palette_preview'&&/throw_creator_workspace/.test(from))return{assignedDefault:()=>({index:0})};if(request==='./viewer_group'&&/throw_creator_workspace/.test(from))return{preferredViewerColumn:()=>2,trackViewerPanel:value=>value,revealInViewerGroup:()=>{}};if(request==='./authoring_context_registry'&&/throw_creator_workspace/.test(from))return{registerCharacterToolPanel(){}};if(request==='./launch_controls'&&/throw_creator_workspace/.test(from))return{launchControlsHtml:()=>'',launchControlsClientScript:()=>'',handleLaunchMessage:async()=>false};if(request==='./webview_policy'&&/throw_creator_workspace/.test(from))return{protect:value=>value};if(request==='./viewer_sessions'&&/throw_creator_workspace/.test(from))return{register:(value,source,kind)=>records.set(value,{source,kind})};if(request==='./viewer_close'&&/throw_creator_workspace/.test(from))return{support:(value,options)=>supports.set(value,options)};return original.call(this,request,parent,main);};
(async()=>{try{
 const make=name=>{const folder=path.join(root,name);fs.mkdirSync(folder);const def=path.join(folder,`${name}.def`),air=path.join(folder,`${name}.air`),sff=path.join(folder,`${name}.sff`);fs.writeFileSync(def,`[Info]\nname=${name}\n[Files]\nanim=${name}.air\nsprite=${name}.sff\n`);fs.writeFileSync(air,'[Begin Action 800]\n0,0,0,0,4\n[Begin Action 801]\n0,0,0,0,4\n');fs.writeFileSync(sff,'fixture');return def;};
 const a=make('A'),b=make('B'),creator=require('../src/throw_creator_model'),workspace=require('../src/throw_creator_workspace');workspace.registerThrowCreator({workspaceState,subscriptions:[],extensionUri:{fsPath:root}});const open=commands.get('ikemen.throwCreator.open'),first=await open(vscode.Uri.file(a));assert(first);assert.deepEqual(records.get(first),{source:a,kind:'throw_creator'});assert(supports.has(first));
 const plan=creator.newPlan('Recovered Grapple');plan.id='recovered-grapple';plan.p1Action=800;plan.p2Action=801;plan.notes='Host-backed throw notes';await first.send({type:'throwDraft',plan});assert(first.webview.messages.some(message=>message.type==='throwDraftStored'));await supports.get(first).keepDraft();first.dispose();
 const reference={defPath:a,planId:plan.id,p1Action:800,p2Action:801},restored=await open(vscode.Uri.file(a),{preset:true,reference});assert.match(restored.webview.html,/Recovered Grapple/);assert.match(restored.webview.html,/Host-backed throw notes/);assert.match(restored.webview.html,/Discard recovered work/);const other=await open(vscode.Uri.file(b));assert(other&&other!==restored,'different characters retain separate Throw Creator panels');assert.strictEqual(await open(vscode.Uri.file(a)),restored,'the same character reuses its panel');restored.dispose();other.dispose();
 const again=await open(vscode.Uri.file(a),{preset:true,reference});await again.send({type:'discardThrowDraft'});again.dispose();const clean=await open(vscode.Uri.file(a));assert.doesNotMatch(clean.webview.html,/Recovered Grapple/);clean.dispose();
 const before=panels.length;assert.strictEqual(await open(vscode.Uri.file(b),{preset:true,reference:{defPath:b,planId:'missing',p1Action:800,p2Action:801}}),undefined);assert.strictEqual(panels.length,before,'a missing plan is rejected before panel creation');assert(workspace.validThrowReference(reference,a,{plan:{id:plan.id},actions:[{action:800},{action:801}]}));console.log('Throw Creator drafts survive close/reopen, remain character-bound, discard exactly, and reject stale typed plans');
 }finally{Module._load=original;fs.rmSync(root,{recursive:true,force:true});}})().catch(error=>{console.error(error);process.exitCode=1;});
