'use strict';
const assert=require('assert');
const {createHistory}=require('../src/viewer_history');
(async()=>{
  const source={filename:'C:/chars/A/moves.zss',kind:'source',line:3,text:'anim: 200'};
  const air={filename:'C:/chars/A/a.air',kind:'air',reference:{group:200}};
  const sound={filename:'C:/chars/A/a.snd',kind:'snd',reference:{group:1,number:2}};
  const sprite={filename:'C:/chars/A/a.sff',kind:'sff',reference:{group:3,number:4}};
  const opened=[];let fail=false,throws=false,release;
  const history=createHistory(async point=>{opened.push(point);if(throws)throw Error('unavailable');if(release)await new Promise(resolve=>release=resolve);return !fail;});
  assert.deepStrictEqual(history.state(),{back:false,forward:false,busy:false});
  history.transition(source,air);history.transition(air,sound);
  assert(await history.travel(-1));assert.deepStrictEqual(opened.at(-1).reference,{group:200});
  assert(history.state().back&&history.state().forward);
  fail=true;assert.strictEqual(await history.travel(1),false);assert(history.state().forward);
  fail=false;throws=true;await assert.rejects(history.travel(1),/unavailable/);assert(!history.state().busy);throws=false;
  const changed={...air,reference:{group:210,frameIndex:2}};
  history.transition(changed,sprite);assert(!history.state().forward);
  changed.reference.group=999;
  await history.travel(-1);assert.deepStrictEqual(opened.at(-1).reference,{group:210,frameIndex:2},'history snapshots selections and discards the old forward branch');
  await history.travel(-1);assert.strictEqual(opened.at(-1).kind,'source');assert.strictEqual(opened.at(-1).line,3);
  assert.strictEqual(await history.travel(-1),false);
  release=true;const moving=history.travel(1);assert(history.state().busy);assert.strictEqual(await history.travel(1),false);release();await moving;release=null;
  history.transition(air,air);assert(!history.state().forward,'repeated destination does not create a duplicate');
  const bounded=createHistory(async()=>true,()=>{},3);
  for(let i=0;i<8;i++)bounded.transition(null,{...air,reference:{group:i}});
  assert(await bounded.travel(-1));assert(await bounded.travel(-1));assert.strictEqual(await bounded.travel(-1),false);
  console.log('Viewer history branching, selection snapshots, failure/cancel, concurrency and bounds passed');
})().catch(error=>{console.error(error);process.exitCode=1;});
