'use strict';
const assert=require('assert'),{build,frameAt}=require('../src/viewer_animation_comparison');
const {bounds,html}=require('../src/viewer_animation_comparison');
const archive={sprites:[{group:0,number:0,width:20,height:30,axisX:10,axisY:30}]};let encodes=0;
const action=build('[Begin Action 200]\n0,0,2,-3,2,H\nLoopStart\n0,0,0,0,0\n0,0,0,0,3\n',200,archive,()=>{encodes++;return'data:image/png;base64,AA==';});
assert.strictEqual(encodes,1,'repeated sprite frames share immutable image data');
assert.strictEqual(action.frames[0].flags,'H');assert.strictEqual(action.frames[0].x,2);assert.strictEqual(action.images['0,0'].axisY,30);
assert.deepStrictEqual(bounds(action),{left:-10,right:12,top:-33,bottom:0});
const snapshot={identity:'AIR 200',filename:'<test.air>',detail:'test',animation:action};
const page=html(snapshot,snapshot,'abc');assert(!page.includes('<test.air>'));assert.match(page,/&lt;test.air&gt;/);assert.doesNotThrow(()=>new Function(page.match(/<script nonce="abc">([\s\S]*)<\/script>/)[1]));
assert.match(page,/Go to Tick/);assert.match(page,/Reset Both/);
assert.deepStrictEqual([0,1,2,4,5,7,8].map(tick=>frameAt(action,tick)),[0,0,2,2,2,2,2]);
const loop={loopStart:1,frames:[{rawTime:2},{rawTime:3},{rawTime:4}]};
assert.deepStrictEqual([0,2,5,8,9,12].map(t=>frameAt(loop,t)),[0,1,2,2,1,2]);
assert.strictEqual(frameAt({loopStart:0,frames:[{rawTime:0},{rawTime:0}]},1e9),1,'all-zero loops terminate deterministically');
assert.strictEqual(frameAt({loopStart:0,frames:[{rawTime:2},{rawTime:4},{rawTime:-1}]},1e9),2,'final indefinite frames remain held');
assert.deepStrictEqual(build('[Begin Action 1]\n9,9,0,0,1',1,archive,()=>'' ).missing,['9,9']);
assert.throws(()=>build('[Begin Action 1]\n9,9,0,0,1',2,archive,()=>''),/missing/);
console.log('AIR comparison frame timing, zero/indefinite durations, loops, offsets and shared sprite images passed');
