'use strict';
const assert = require('assert');
const { preferredViewerColumn, trackViewerPanel, revealInViewerGroup, resetViewerGroupForTests } = require('../src/viewer_group');

resetViewerGroupForTests();
assert.strictEqual(preferredViewerColumn(1), 1);
assert.strictEqual(preferredViewerColumn(-1), -2, 'a first visual viewer must open beside the active text group');
let changed, revealed;
const panel = { viewColumn: 2, onDidChangeViewState(callback) { changed = callback; }, onDidDispose() {}, reveal(column, preserveFocus) { revealed = { column, preserveFocus }; } };
trackViewerPanel(panel);
assert.strictEqual(preferredViewerColumn(1), 2);
assert.strictEqual(preferredViewerColumn(-2, 2), -2);
changed({ webviewPanel: { active: true, viewColumn: 3 } });
assert.strictEqual(preferredViewerColumn(1), 3);
revealInViewerGroup({ viewColumn: undefined, reveal(column, preserveFocus) { revealed = { column, preserveFocus }; } }, true, 1);
assert.deepStrictEqual(revealed, { column: 3, preserveFocus: true });
resetViewerGroupForTests();
let dispose;
const finalPanel = { viewColumn: 4, onDidChangeViewState() {}, onDidDispose(callback) { dispose = callback; } };
trackViewerPanel(finalPanel);
dispose();
assert.strictEqual(preferredViewerColumn(1), 1);
let disposeActive;
trackViewerPanel({viewColumn:2,onDidDispose(){}});
trackViewerPanel({viewColumn:4,active:true,onDidDispose(callback){disposeActive=callback;}});
disposeActive();assert.strictEqual(preferredViewerColumn(1),2,'closing the active viewer must not retain its dead group as the preferred destination');
resetViewerGroupForTests();
let activateFirst, activateSecond, closeSecond;
const first={viewColumn:2,active:true,onDidChangeViewState(fn){activateFirst=fn;},onDidDispose(){}};
const second={viewColumn:4,active:false,onDidChangeViewState(fn){activateSecond=fn;},onDidDispose(fn){closeSecond=fn;}};
trackViewerPanel(first);trackViewerPanel(second);
assert.strictEqual(preferredViewerColumn(1),2,'A background restored tab must not steal the destination');
activateSecond({webviewPanel:second});assert.strictEqual(preferredViewerColumn(1),2);
second.active=true;second.viewColumn=5;activateSecond({webviewPanel:second});
assert.strictEqual(preferredViewerColumn(1),5,'Dragging and activating a viewer updates the destination');
let existingReveal;
revealInViewerGroup({viewColumn:3,reveal(column){existingReveal=column;}});
assert.strictEqual(existingReveal,3,'Reopening a moved viewer preserves its chosen group');
closeSecond();assert.strictEqual(preferredViewerColumn(1),2);
resetViewerGroupForTests();
console.log('Shared visual viewer group tests passed');
