const assert=require('assert'),toolbar=require('../src/viewer_toolbar'),layout=require('../src/viewer_layout');
let data={'ikemaker.viewerToolbars.v1':{air:{hidden:['game']}},'ikemaker.viewerLayouts.v1':{air:{current:{right:false,leftWidth:400}}}};
const storage={get:(key,fallback)=>data[key]||fallback,update:async(key,value)=>data[key]=value};toolbar.configure({globalState:storage});
function panel(){const p={messages:[],onDidDispose(){},webview:{postMessage:message=>p.messages.push(message)}};return p;}
(async()=>{assert.deepEqual(toolbar.read('air','workspace').hidden,['game']);assert(toolbar.read('air','simple').hidden.includes('compare'));assert(!toolbar.read('air','simple').hidden.includes('game'));
const simple=panel(),full=panel();await toolbar.handle({type:'viewerToolbarReady',surface:'air',mode:'simple'},simple);await toolbar.handle({type:'viewerToolbarReady',surface:'air',mode:'workspace'},full);const before=full.messages.length;await toolbar.handle({type:'viewerToolbarSave',surface:'air',preferences:{hidden:['snd']}},simple);assert.equal(full.messages.length,before);assert.deepEqual(toolbar.read('air','workspace').hidden,['game']);assert.deepEqual(toolbar.read('air','simple').hidden,['snd']);
await layout.handle({type:'viewerLayoutReady',surface:'air',mode:'simple'},simple);assert.equal(simple.messages.at(-1).current.right,true);await layout.handle({type:'viewerLayoutReady',surface:'air',mode:'workspace'},full);assert.equal(full.messages.at(-1).current.right,false);const count=full.messages.length;await layout.handle({type:'viewerLayoutSave',surface:'air',layout:{left:false}},simple);assert.equal(full.messages.length,count);assert.equal(data['ikemaker.viewerLayouts.v1']['air:simple'].current.left,false);assert.equal(data['ikemaker.viewerLayouts.v1'].air.current.leftWidth,400);
const sprite=panel();await layout.handle({type:'viewerLayoutReady',surface:'sff',mode:'simple',initial:{panes:{right2:{visible:true}}}},sprite);assert.equal(sprite.messages.at(-1).current.panes.right2.visible,false,'Simple must not inherit legacy SFF visibility from webview state');
console.log('Toolbar/layout modes stay independent; legacy customizations migrate only to Workspace');})().catch(error=>{console.error(error);process.exitCode=1;});
