'use strict';
const assert=require('assert'),Module=require('module'),fs=require('fs'),os=require('os'),path=require('path');
const sources=require('../src/viewer_sources');
const page=sources.html('<owner>', ['a<cns>.cns','functions.zss'],'abc');
assert(page.includes('&lt;owner&gt;'));assert(!page.includes('a<cns>'));assert.doesNotThrow(()=>new Function(page.match(/<script nonce="abc">([\s\S]*)<\/script>/)[1]));
assert.deepStrictEqual(sources.matchingLines('normal.lp.damage = 20\nnormal.mp.damage = 30',{id:'normal.mp'}),[1]);
assert.deepStrictEqual(sources.matchingLines('text',{}),[]);
(async()=>{
 const folder=fs.mkdtempSync(path.join(os.tmpdir(),'pinned-sources-')),owner=path.join(folder,'char.def'),file=path.join(folder,'constants.cns');fs.writeFileSync(owner,'[Files]');fs.writeFileSync(file,'normal.lp.damage=20\nnormal.mp.damage=30');
 const sent=[],opened=[],stored={},information=[];let receiver,change,disposed,changesDisposed=false,watchChange,watchDisposed=false,inputValue='Medium damage',inputHook,assignmentEnabled=true;
 const panel={reveal(){},webview:{postMessage:m=>sent.push(m),onDidReceiveMessage:fn=>receiver=fn},onDidDispose:fn=>disposed=fn};
 const nav={archiveContext:()=>({ownerDef:owner}),archiveRegistry:()=>({commonSources:[]}),openReferenceSource:(origin,point)=>opened.push({origin,point})};
 const vscode={RelativePattern:class{},Uri:{file:fsPath=>({fsPath})},ViewColumn:{Beside:2},workspace:{createFileSystemWatcher:()=>({onDidChange:fn=>watchChange=fn,onDidCreate(){},onDidDelete(){},dispose(){watchDisposed=true;}}),textDocuments:[],onDidChangeTextDocument:fn=>{change=fn;return{dispose(){changesDisposed=true;}};}},window:{showQuickPick:async items=>items,showInputBox:async options=>inputHook?inputHook(options):inputValue,showWarningMessage:async()=>undefined,showInformationMessage:text=>information.push(text),registerWebviewPanelSerializer:()=>({dispose(){}}),createWebviewPanel:()=>panel,showErrorMessage:text=>{throw Error(text);}}};
 const original=Module._load;Module._load=function(request,parent,main){if(request==='vscode')return vscode;if(parent?.filename.endsWith('viewer_sources.js')&&request==='./viewer_navigation')return nav;if(parent?.filename.endsWith('viewer_sources.js')&&request==='./related_work')return{resolveAssigned:()=>assignmentEnabled?({constants:file,code:[file]}):({constants:null,code:[]})};return original.call(this,request,parent,main);};
 try{
 sources.registerSources({workspaceState:{get:(name,fallback)=>stored[name]??fallback,update:async(name,value)=>stored[name]=value},subscriptions:[]});
 const point={filename:owner,kind:'constants',reference:{id:'normal.mp'}};
 assert.strictEqual(await sources.openSources(owner,point),panel);
 await receiver({type:'select',index:0,follow:true,restorePosition:true});assert.strictEqual(sent.at(-1).jump,false,'restored view retains its reading position while Follow remains enabled');
 let displayed=sent.filter(message=>message.type==='source').at(-1);
 await receiver({type:'pinExample',index:0,line:1,sourceFingerprint:displayed.sourceFingerprint});let examplesMessage=sent.filter(message=>message.type==='examples').at(-1);assert.strictEqual(examplesMessage.items.length,1);assert.strictEqual(examplesMessage.items[0].label,'Medium damage');assert(stored['ikemaker.personalExamples.v1'],'example bookmark persists in workspace state');
 inputValue='Renamed medium damage';await receiver({type:'renameExample',id:examplesMessage.items[0].id});examplesMessage=sent.filter(message=>message.type==='examples').at(-1);assert.strictEqual(examplesMessage.items[0].label,'Renamed medium damage');
 assignmentEnabled=false;await receiver({type:'refreshExamples'});examplesMessage=sent.filter(message=>message.type==='examples').at(-1);assert.strictEqual(examplesMessage.items[0].status,'unlinked','live assignment removal invalidates an open shelf');
 const countBefore=stored['ikemaker.personalExamples.v1'].byOwner[Object.keys(stored['ikemaker.personalExamples.v1'].byOwner)[0]].length;
 await receiver({type:'openExample',id:examplesMessage.items[0].id});await receiver({type:'pinExample',index:0,line:0,sourceFingerprint:displayed.sourceFingerprint});await receiver({type:'relinkExample',id:examplesMessage.items[0].id,index:0,line:0,sourceFingerprint:displayed.sourceFingerprint});
 assert.strictEqual(stored['ikemaker.personalExamples.v1'].byOwner[Object.keys(stored['ikemaker.personalExamples.v1'].byOwner)[0]].length,countBefore,'unassigned sources cannot be opened, pinned or relinked from stale panel state');assert(information.length>=3);
 assignmentEnabled=true;await receiver({type:'select',index:0,follow:false});displayed=sent.filter(message=>message.type==='source').at(-1);
 await receiver({type:'relinkExample',id:examplesMessage.items[0].id,index:0,line:0,sourceFingerprint:displayed.sourceFingerprint});const ownerPins=stored['ikemaker.personalExamples.v1'].byOwner[Object.keys(stored['ikemaker.personalExamples.v1'].byOwner)[0]];assert.strictEqual(ownerPins[0].startLine,0,'relink uses the exact visibly selected block');
 let releasePrompt;inputHook=()=>new Promise(resolve=>{releasePrompt=resolve;});const pendingPin=receiver({type:'pinExample',index:0,line:0,sourceFingerprint:displayed.sourceFingerprint});fs.writeFileSync(file,'changed while prompt open');await receiver({type:'select',index:0,follow:false});releasePrompt('Stale label');await pendingPin;inputHook=null;
 examplesMessage=sent.filter(message=>message.type==='examples').at(-1);assert.strictEqual(examplesMessage.items.length,1,'a source change during the label prompt cannot create a mismatched pin');
 fs.writeFileSync(file,'normal.lp.damage=20\nnormal.mp.damage=30');await receiver({type:'select',index:0,follow:true});
 await receiver({type:'select',index:0,follow:true});assert.strictEqual(sent.at(-1).line,1);assert.strictEqual(sent.at(-1).jump,true,'explicit selection still follows the move');
 await receiver({type:'editor',index:0,line:1});assert.strictEqual(opened[0].origin.text,'normal.mp.damage=30');assert.strictEqual(opened[0].point,point);
 await receiver({type:'editor',index:0,line:99});assert.strictEqual(opened.length,1);
 sources.followSelection({...point,filename:owner.toUpperCase(),reference:{id:'normal.lp'}});assert.strictEqual(sent.at(-1).line,0,'Windows path casing must not stop move following');
 vscode.workspace.textDocuments=[{fileName:file,isDirty:true,getText:()=>'; changed\nnormal.lp.damage=22'}];change({document:vscode.workspace.textDocuments[0]});assert.strictEqual(sent.at(-1).line,1);assert.match(sent.at(-1).status,/Unsaved source/);
 await receiver({type:'select',index:0,follow:false});sources.followSelection({...point,reference:{id:'normal.mp'}});assert.match(sent.at(-1).status,/Read-only/);
 vscode.workspace.textDocuments=[];fs.writeFileSync(file,'; external\nnormal.mp.damage=40');watchChange({fsPath:file});assert.match(sent.at(-1).text,/external/);
 fs.unlinkSync(file);watchChange({fsPath:file});assert.strictEqual(sent.at(-1).error,true);assert.strictEqual(sent.at(-1).text,'');assert.match(sent.at(-1).status,/Source unavailable/);
 const openedBefore=opened.length;await receiver({type:'editor',index:0,line:0});assert.strictEqual(opened.length,openedBefore,'unavailable source cannot open a stale line');
 fs.writeFileSync(file,'; external recovered\nnormal.mp.damage=41');watchChange({fsPath:file});assert(!sent.at(-1).error);assert.match(sent.at(-1).text,/recovered/);
 disposed();assert(changesDisposed);assert(watchDisposed);
 assert.strictEqual(sources.restoreSources(panel,{owner,files:[file],fromPoint:point,index:0,follow:false}),panel);
 assert(panel.webview.html.includes('metadata='));assert(panel.webview.html.includes('"owner":'));
 await receiver({type:'select',index:0,follow:false});assert.match(sent.at(-1).text,/external/);assert.match(sent.at(-1).status,/Read-only/);
 disposed();
 let visibleChange,visibilityDisposed=false,reveals=0,duplicateDisposed=false;
 panel.visible=false;panel.reveal=()=>{reveals++;};panel.onDidChangeViewState=fn=>{visibleChange=fn;return {dispose(){visibilityDisposed=true;}};};
 panel.webview.html='retained state placeholder';
 sources.restoreSources(panel,{owner,files:[file],fromPoint:point});
 assert.strictEqual(panel.webview.html,'retained state placeholder','Hidden restored panel must not render into a collapsed group');
 visibleChange({webviewPanel:{visible:false}});assert.strictEqual(panel.webview.html,'retained state placeholder');
 sources.restoreSources({dispose(){duplicateDisposed=true;}},{owner,files:[file],fromPoint:{...point,reference:{id:'other'}}});
 assert(duplicateDisposed);assert.strictEqual(reveals,0,'Restoring duplicates must not activate or move existing tabs');
 visibleChange({webviewPanel:{visible:true}});assert(visibilityDisposed);assert(panel.webview.html.includes('metadata='));
 const initializedHtml=panel.webview.html;visibleChange({webviewPanel:{visible:true}});assert.strictEqual(panel.webview.html,initializedHtml,'Late visibility events must not reset reading state');
 await receiver({type:'select',index:0,follow:true,restorePosition:true});assert.strictEqual(sent.at(-1).jump,false);assert.strictEqual(sent.at(-1).fromPoint.reference.id,'normal.mp','Duplicate restoration preserves the live navigation origin');
 disposed();
 visibilityDisposed=false;panel.visible=false;
 sources.restoreSources(panel,{owner,files:[file],fromPoint:point});disposed();assert(visibilityDisposed,'Closing a hidden restored panel disposes its visibility listener');
 const closedHtml=panel.webview.html;visibleChange({webviewPanel:{visible:true}});assert.strictEqual(panel.webview.html,closedHtml,'Queued visibility events cannot revive a closed tab');
 let rejected=false;sources.restoreSources({dispose(){rejected=true;}},{owner:'relative.def',files:[file]});assert(rejected);
 }finally{Module._load=original;fs.rmSync(folder,{recursive:true,force:true});}
 console.log('Pinned source HTML, exact source links, live drafts, move following, and disposal passed');
})().catch(error=>{console.error(error);process.exitCode=1;});
