'use strict';
const assert=require('assert'),layout=require('../src/viewer_layout');
(async()=>{
 const defaults=layout.presets('air').Default;
 assert.strictEqual(defaults.leftWidth,245);assert.strictEqual(layout.presets('move_constants').Default.leftWidth,360);
 assert.deepStrictEqual(layout.normalize({left:false,leftWidth:1,rightWidth:900}),{left:false,right:true,leftWidth:160,rightWidth:600});
 assert.strictEqual(layout.html('unknown'),'');assert.match(layout.html('snd'),/Reset Layout/);assert.match(layout.html('air'),/Reset Layout/);assert.doesNotThrow(()=>new Function(layout.clientScript()));
 assert.deepStrictEqual(layout.presets('snd').Default,{groups:true,groupsWidth:220,left:true,leftWidth:300,right:false,rightWidth:340});
 let state={},fail=false;const storage={get:()=>state,update:async(key,value)=>{if(fail)throw Error('disk unavailable');state=value;}};
 layout.configure({globalState:storage});const received=[],panel={webview:{postMessage:m=>received.push(m)},onDidDispose(){}};
 await layout.handle({type:'viewerLayoutReady',surface:'air'},panel);assert.deepStrictEqual(received.at(-1).current,defaults);
 await layout.handle({type:'viewerLayoutSave',surface:'air',name:'My animation view',layout:{left:true,right:false,leftWidth:220,rightWidth:300}},panel);
 assert.strictEqual(state['air:simple'].current.right,false);assert.strictEqual(state['air:simple'].saved['My animation view'].leftWidth,220);
 layout.configure({globalState:storage});await layout.handle({type:'viewerLayoutReady',surface:'air'},panel);assert.strictEqual(received.at(-1).current.right,false,'saved visibility survives storage reload');
 fail=true;await layout.handle({type:'viewerLayoutReset',surface:'air'},panel);assert.strictEqual(received.at(-1).type,'viewerLayoutError');assert.strictEqual(state['air:simple'].current.right,false,'failed reset does not mutate persisted layout');
 fail=false;await layout.handle({type:'viewerLayoutReset',surface:'air'},panel);assert.deepStrictEqual(state['air:simple'].current,defaults);assert(state['air:simple'].saved['My animation view'],'reset retains named user layouts');
 const second={webview:{postMessage(){}},onDidDispose(){}};await layout.handle({type:'viewerLayoutReady',surface:'move_constants'},second);
 await Promise.all([layout.handle({type:'viewerLayoutSave',surface:'air',layout:{right:false}},panel),layout.handle({type:'viewerLayoutSave',surface:'move_constants',layout:{left:false}},second)]);
 assert.strictEqual(state['air:simple'].current.right,false);assert.strictEqual(state['move_constants:simple'].current.left,false);
 const sound={webview:{postMessage:m=>received.push(m)},onDidDispose(){}};
 await layout.handle({type:'viewerLayoutReady',surface:'snd'},sound);
 await layout.handle({type:'viewerLayoutSave',surface:'snd',name:'Sound focus',layout:{groups:false,groupsWidth:999,left:false,right:false,leftWidth:300,rightWidth:340}},sound);
 assert.strictEqual(state['snd:simple'].current.groups,false);assert.strictEqual(state['snd:simple'].current.groupsWidth,420);
 layout.configure({globalState:storage});await layout.handle({type:'viewerLayoutReady',surface:'snd'},sound);assert.strictEqual(received.at(-1).current.groups,false);
 await layout.handle({type:'viewerLayoutReset',surface:'snd'},sound);assert.deepStrictEqual(state['snd:simple'].current,layout.presets('snd').Default);assert(state['snd:simple'].saved['Sound focus']);
 const sprite={webview:{postMessage:m=>received.push(m)},onDidDispose(){}};
 const initial=layout.presets('sff').Default;initial.panes.left2.visible=false;initial.panes.right1.width=410;
 await layout.handle({type:'viewerLayoutReady',surface:'sff',mode:'workspace',initial},sprite);assert.deepStrictEqual(received.at(-1).current,initial,'first use preserves existing SFF panel choices');
 await layout.handle({type:'viewerLayoutSave',surface:'sff',name:'Sprites and tools',layout:initial},sprite);
 assert.strictEqual(state['sff:workspace'].saved['Sprites and tools'].panes.right1.width,410);
 const invalid=layout.normalizeLayout('sff',{panes:{left1:{width:999},right2:{visible:false,width:1}}});assert.strictEqual(invalid.panes.left1.width,420);assert.strictEqual(invalid.panes.right2.width,170);assert.strictEqual(invalid.panes.right2.visible,false);
 await layout.handle({type:'viewerLayoutReset',surface:'sff'},sprite);assert.deepStrictEqual(state['sff:workspace'].current,layout.presets('sff','workspace').Default);assert(state['sff:workspace'].saved['Sprites and tools']);
 await layout.handle({type:'viewerLayoutReady',surface:'snd',mode:'workspace'},sound);assert.equal(received.at(-1).mode,'workspace');assert.equal(received.at(-1).current.right,true);
 await layout.handle({type:'viewerLayoutReady',surface:'snd',mode:'simple'},sound);assert.equal(received.at(-1).mode,'simple');assert.equal(received.at(-1).current.right,false);
 console.log('Viewer layout defaults, bounds, saved presets, reset, isolation, concurrent saves and failure recovery passed');
})().catch(error=>{console.error(error);process.exitCode=1;});
