'use strict';
const assert=require('assert');
const {references,findUsedBy}=require('../src/viewer_used_by_model');
const assets={air:'/char/own.air',sff:'/char/own.sff',snd:'/char/own.snd'};
const registry={candidates:[{prefix:'fx6',air:'/fx/shared.air',sff:'/fx/shared.sff',snd:'/fx/shared.snd'}],diagnostics:[]};
const code='// anim: 210;\nexplod { anim: 210; } explod { anim: FX6210; } // anim: 210;\nplaySnd { value: 3,4; } playSnd { value: FX63,4; }\nchangeAnim { value: const(normal.mp.moveID); }\nvelSet { value: 210; }\ndisplayToClipboard { text: "anim: 210;"; }\n/* anim: 210;\n anim: 210; */\nexplod { anim: var(0); }';
const parsed=references(code,'/char/moves.zss');
assert.strictEqual(parsed.length,6,'comments, strings and unrelated value controllers are excluded; same-line assignments remain distinct');
assert.deepStrictEqual(parsed.slice(0,2).map(item=>item.line),[1,1]);
const documents=[{filename:'/char/moves.zss',text:code},{filename:'/char/own.air',text:'[Begin Action 210]\n1,0,0,0,1\n'},{filename:'/fx/shared.air',text:'[Begin Action 210]\n1,0,0,0,1\n'}];
const constants=new Map([['normal.mp.moveid',{value:210}]]);
const query=(kind,filename,reference)=>findUsedBy({documents,assets,registry,constants,target:{kind,filename},reference});
let result=query('air',assets.air,{group:210});assert.strictEqual(result.matches.length,2);assert.strictEqual(result.unresolved,1);
result=query('air','/fx/shared.air',{group:210});assert.strictEqual(result.matches.length,1);assert(result.matches[0].expression.includes('FX6'));
assert.strictEqual(query('snd',assets.snd,{group:3,number:4}).matches.length,1);
assert.strictEqual(query('snd','/fx/shared.snd',{group:3,number:4}).matches.length,1);
result=query('sff',assets.sff,{group:1,number:0});assert.strictEqual(result.matches.length,1);assert.strictEqual(result.matches[0].filename,assets.air);assert.strictEqual(result.matches[0].line,1);
result=query('sff','/fx/shared.sff',{group:1,number:0});assert.strictEqual(result.matches.length,1);assert.strictEqual(result.matches[0].filename,'/fx/shared.air');
assert.strictEqual(references('[Constants]\nnormal.mp.anim = 210','/char/data.cns').length,0,'constant keys are not executable asset assignments');
const cns=references('[State 1]\ntype = PlaySnd\nvalue = 3,4 ; anim = 210\n[State 2]\ntype = VelSet\nvalue = 210\n[State 3]\ntype = HitDef\nhitsound = S3,4\nsparkno = 210','/char/state.cns');
assert.strictEqual(cns.length,3);assert.strictEqual(cns[1].defaultPrefix,'f');
registry.candidates.push({prefix:'fx6',air:'/other/shared.air',sff:'/other/shared.sff',snd:'/other/shared.snd'});
result=query('air','/fx/shared.air',{group:210});assert.strictEqual(result.matches.length,0);assert.strictEqual(result.unresolved,2,'ambiguous shared ownership is not an exact match');
const {html}=require('../src/viewer_used_by');
const page=html({identity:'AIR 210',filename:'<archive>',owner:'<owner>',files:1,unresolved:0,diagnostics:['<bad>'],matches:[{filename:'/char/<file>.zss',line:3,text:'<script>alert(1)</script>'}]},'nonce');
assert(!page.includes('<script>alert'));assert(page.includes('&lt;script&gt;'));assert(page.includes('Open &lt;file&gt;.zss:4'));
const script=page.match(/<script nonce="nonce">([\s\S]*?)<\/script>/)[1];assert.doesNotThrow(()=>new Function(script));
const fields={filter:{value:''},count:{textContent:''},'empty-filter':{hidden:true},refresh:{}},rows=[{dataset:{search:'moves.zss anim: 210'},hidden:false}];let saved;
require('vm').runInNewContext(script,{acquireVsCodeApi:()=>({getState:()=>({filter:'missing'}),setState:value=>saved=value,postMessage(){}}),document:{getElementById:id=>fields[id],querySelectorAll:selector=>selector==='article'?rows:[]}});
assert.strictEqual(fields.count.textContent,'0 of 1 exact reference(s) shown.');assert.strictEqual(fields['empty-filter'].hidden,false);
fields.filter.value='moves';fields.filter.oninput();assert.strictEqual(rows[0].hidden,false);assert.strictEqual(fields['empty-filter'].hidden,true);assert.strictEqual(saved.filter,'moves');
console.log('Used By exact lines, shared ownership, same-line references, comments, constants, ambiguity and safe HTML passed');
