const assert=require('assert'),close=require('../src/viewer_close'),vm=require('vm');
function panel(clean){const listeners=[];return {title:'Test form',clean,viewColumn:2,webview:{onDidReceiveMessage:fn=>{listeners.push(fn);return{dispose(){}};},postMessage(message){queueMicrotask(()=>listeners.forEach(fn=>fn({type:'ikemenCloseState',id:message.id,clean})));return true;}},onDidDispose(){},reveal(){this.revealed=true;}};}
(async()=>{let answer,prompts=0;const api={window:{showInformationMessage:async()=>{},showWarningMessage:async()=>{prompts++;return answer;}}};const clean=panel(true),dirty=panel(false);close.track(clean);close.track(dirty);assert.equal(await close.prepare([clean],api),true);assert.equal(prompts,0);assert.equal(await close.prepare([dirty],api),false);assert(dirty.revealed);answer='Close Without Applying';assert.equal(await close.prepare([dirty],api),true);
const unavailable=panel(true);unavailable.webview.postMessage=()=>false;close.track(unavailable);assert.equal(await close.prepare([unavailable],api),false,'An unresponsive panel cannot silently approve closing');
let inputs={},onmessage,reply;const env={document:{addEventListener:(name,handler)=>inputs[name]=handler},addEventListener:(name,handler)=>onmessage=handler,vscode:{postMessage:message=>reply=message}};vm.runInNewContext(close.clientScript(),env);onmessage({data:{type:'ikemenPrepareClose',id:1}});assert(reply.clean);inputs.input({target:{id:'search',matches:()=>true}});onmessage({data:{type:'ikemenPrepareClose',id:2}});assert(reply.clean);inputs.input({target:{id:'damage',matches:()=>true}});onmessage({data:{type:'ikemenPrepareClose',id:3}});assert.equal(reply.clean,false);const field={id:'duration',value:'180',isConnected:true,matches:()=>true};inputs.focusin({target:field});field.value='200';inputs.input({target:field});onmessage({data:{type:'ikemenPrepareClose',id:4}});assert(!reply.clean);
// Start another page to isolate the earlier unknown-baseline test input.
inputs={};vm.runInNewContext(close.clientScript(),env);inputs.focusin({target:field});field.value='240';inputs.input({target:field});onmessage({data:{type:'ikemenPrepareClose',id:5}});assert(!reply.clean);field.value='200';onmessage({data:{type:'ikemenPrepareClose',id:6}});assert(reply.clean,'reverted values do not require a discard prompt');
field.value='260';inputs.input({target:field});inputs.focusin({target:field});onmessage({data:{type:'ikemenPrepareClose',id:7}});assert(!reply.clean,'refocusing must not bless an edit as the baseline');field.isConnected=false;onmessage({data:{type:'ikemenPrepareClose',id:8}});assert(reply.clean,'removed form fields no longer represent live input');
field.isConnected=true;env.ikemenHasUnappliedForms=()=>false;env.ikemenCanLeaveAsset=()=>false;onmessage({data:{type:'ikemenPrepareClose',id:9}});assert(!reply.clean,'pending asset writes still veto clean forms');env.ikemenCanLeaveAsset=()=>true;onmessage({data:{type:'ikemenPrepareClose',id:10}});assert(reply.clean,'authoritative applied state clears the obsolete touched warning');env.ikemenHasUnappliedForms=()=>{throw Error('unavailable')};onmessage({data:{type:'ikemenPrepareClose',id:11}});assert(!reply.clean,'failed state inspection never approves close');
console.log('Visual close checks: clean, edited, explicit discard, cancellation and unresponsive panels passed');})().catch(error=>{console.error(error);process.exitCode=1;});
