'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');const source=fs.readFileSync(path.join(__dirname,'../src/production_workflow_workspace.js'),'utf8');
let revision=0,release;const gate=new Promise(resolve=>{release=resolve;}),calls=[],draftCalls=[],supports=new Map();
function panel(){const p={webview:{html:'',onDidReceiveMessage:fn=>{p.receive=fn;},postMessage(){}},onDidDispose:fn=>{p.dispose=fn;}};return p;}
const box={path,activeSession:null,actionQueue:Promise.resolve(),workflowSessions:new Map(),sessionKey:file=>path.resolve(file).toLowerCase(),chooseCharacter:async uri=>uri.fsPath,characterContext:defPath=>({defPath,name:path.basename(defPath)}),loadState:(context,character)=>({character,revision,progressPath:'progress'}),html:state=>state.character.defPath,preferredViewerColumn:()=>1,trackViewerPanel:p=>p,revealInViewerGroup(){},registerCharacterToolPanel(){},refresh:async()=>{},require:name=>name==='./viewer_close'?{support:(p,value)=>supports.set(p,value)}:{protect:value=>value},handle:async(context,session,message)=>{if(message.type==='issueDraft'){draftCalls.push(session.state.character.defPath);return;}calls.push({owner:session.state.character.defPath,revision:session.state.revision,id:message.id});if(message.id==='first')await gate;revision++;},vscode:{ViewColumn:{Active:1},window:{createWebviewPanel:panel,showErrorMessage:message=>{throw Error(message);}}}};
vm.createContext(box);vm.runInContext(source.slice(source.indexOf('async function openProductionWorkflow('),source.indexOf('function registerProductionWorkflow(')),box);
(async()=>{
 const a=await box.openProductionWorkflow({},{fsPath:'A.def'});const first=a.receive({id:'first'});await new Promise(resolve=>setImmediate(resolve));assert(supports.get(a).isBusy());
 const b=await box.openProductionWorkflow({},{fsPath:'B.def'});assert.notEqual(a,b);await b.receive({type:'issueDraft'});assert.deepEqual(draftCalls,['B.def'],'typing persists without waiting for another panel dialog');const second=b.receive({id:'second'});assert.equal(calls.length,1);assert(supports.get(b).isBusy());assert.equal(a.webview.html,'A.def','opening B retains the original page and form');
 release();await Promise.all([first,second]);assert.deepEqual(calls,[{owner:'A.def',revision:0,id:'first'},{owner:'B.def',revision:1,id:'second'}]);assert(!supports.get(a).isBusy());assert(!supports.get(b).isBusy());assert.equal(await box.openProductionWorkflow({},{fsPath:'A.def'}),a);
 const queued=b.receive({id:'discarded'});b.dispose();await queued;assert.equal(calls.length,2,'queued actions cannot run after their panel closes');assert.equal(box.workflowSessions.size,1);assert.equal(await box.openProductionWorkflow({},{fsPath:'A.def'}),a);
 console.log('Workflow panels keep immutable character ownership, reuse pages, serialize shared board actions and skip disposed queues');
})().catch(error=>{console.error(error);process.exitCode=1;});
