'use strict';
function client(){
 const local={...(vscode.getState()?.moveFormDrafts||{})};
 const key=()=>model.files.defPath.toLowerCase()+'#'+move.id;
 const persist=()=>vscode.setState({...vscode.getState(),moveFormDrafts:local});
 function entry(){const id=key();if(!Object.prototype.hasOwnProperty.call(local,id))local[id]=model.formDrafts?.[move.id]||{};return local[id];}
 function stage(){if(!move)return;const previous=entry(),next={};for(const [suffix,value]of Object.entries(draft)){next[suffix]={base:previous[suffix]?.base??move.values[suffix],value};}if(JSON.stringify(previous)===JSON.stringify(next))return;local[key()]=next;persist();vscode.postMessage({type:'moveFormDraft',defPath:model.files.defPath,sourceId:move.id,draft:next});notice();}
 function select(legacy){if(!move)return{};const fields=entry();if(!Object.keys(fields).length&&legacy)for(const [suffix,value]of Object.entries(legacy))if(Number.isFinite(value)&&move.fields?.some(field=>field.suffix===suffix&&field.present))fields[suffix]={base:move.values[suffix],value};persist();return Object.fromEntries(Object.entries(fields).map(([suffix,field])=>[suffix,field.value]));}
 function base(suffix){return entry()[suffix]?.base??move.values[suffix];}
 function notice(){if(!move)return;const fields=entry(),conflicts=Object.keys(fields).filter(suffix=>fields[suffix].base!==move.values[suffix]);let bar=document.getElementById('moveDraftStatus');if(!bar){bar=document.createElement('div');bar.id='moveDraftStatus';bar.setAttribute('role','status');$('fields').before(bar);}bar.textContent=conflicts.length?'Source values changed for '+conflicts.map(suffix=>suffix+' (draft '+fields[suffix].value+', source '+(move.values[suffix]??'missing')+')').join(', ')+'. Drafts are retained; discard this move draft to reload those values.':Object.keys(fields).length?'Unapplied values retained for this move.':'';for(const button of document.querySelectorAll('[data-apply]'))button.disabled=conflicts.includes(button.dataset.apply);if(Object.keys(fields).length){const button=document.createElement('button');button.textContent='Discard move draft';button.onclick=()=>{local[key()]={};draft={};persist();vscode.postMessage({type:'moveFormDraft',defPath:model.files.defPath,sourceId:move.id,draft:{}});render();};bar.append(button);}}
 window.addEventListener('message',event=>{const message=event.data;if(message.type!=='moveFieldApplied')return;const id=message.defPath.toLowerCase()+'#'+message.sourceId,fields=local[id];if(!fields)return;const field=fields[message.suffix];if(field&&field.base===message.base){if(field.value===message.value)delete fields[message.suffix];else field.base=message.value;persist();vscode.postMessage({type:'moveFormDraft',defPath:message.defPath,sourceId:message.sourceId,draft:fields});if(move&&key()===id){if(!fields[message.suffix])delete draft[message.suffix];}}});
 const hasDrafts=()=>{const prefix=model.files.defPath.toLowerCase()+'#',all=Object.fromEntries(Object.entries(model.formDrafts||{}).map(([id,fields])=>[prefix+id,fields]));return Object.entries({...all,...local}).some(([id,fields])=>id.startsWith(prefix)&&Object.keys(fields).length>0);};
 globalThis.ikemenHasUnappliedForms=hasDrafts;globalThis.ikemenCanKeepDraft=hasDrafts;
 return{stage,select,base,notice};
}
module.exports={clientScript:()=>`const moveDrafts=(${client.toString()})();`};
