'use strict';

function client(){
 let reference=saved.directComponent&&typeof saved.directComponent==='object'?saved.directComponent:null;
 let returnReference=saved.directReturnReference&&typeof saved.directReturnReference==='object'?saved.directReturnReference:null;
 const canonical=value=>String(value||'').replace(/\\/g,'/').toLowerCase();
 const ownerEqual=(a,b)=>(!a&&!b)||Boolean(a&&b&&a.kind===b.kind&&a.signature===b.signature&&a.startLine===b.startLine&&a.endLine===b.endLine);
 const matches=(candidate,wanted)=>Boolean(candidate&&wanted&&['hitdef','state','function'].includes(candidate.kind)&&candidate.kind===wanted.kind&&canonical(candidate.reference?.defPath||candidate.defPath)===canonical(model.files.defPath)&&canonical(wanted.defPath)===canonical(model.files.defPath)&&candidate.id===wanted.id&&canonical(candidate.filename)===canonical(wanted.filename)&&candidate.index===wanted.index&&candidate.line===wanted.line&&candidate.endLine===wanted.endLine&&candidate.sourceHash===wanted.sourceHash&&candidate.rangeHash===wanted.rangeHash&&String(candidate.signature||'')===String(wanted.signature||'')&&ownerEqual(candidate.owner,wanted.owner));
 const components=()=>[...(model.directComponents||[]),...(model.behaviorComponents||[])];
 const current=()=>reference?components().find(item=>matches(item,reference)):null;
 const persist=()=>vscode.setState({...vscode.getState(),directComponent:reference,directReturnReference:returnReference});
 const constantsReference=()=>move?{kind:'constants',defPath:model.files.defPath,profileId:move.id,prefix:move.prefix,sourceFilename:model.files.constants||'',sourceHash:model.timingSources?.constants||'',actionNumber:move.timeline?.actionNumber,frameIndex:frame}:null;
 function validReturn(){if(!returnReference||returnReference.kind!=='constants'||canonical(returnReference.defPath)!==canonical(model.files.defPath)||canonical(returnReference.sourceFilename)!==canonical(model.files.constants||'')||returnReference.sourceHash!==(model.timingSources?.constants||''))return null;const target=model.moves.find(item=>item.id===returnReference.profileId&&item.prefix===returnReference.prefix);if(!target||target.timeline?.actionNumber!==returnReference.actionNumber||!Number.isInteger(returnReference.frameIndex)||returnReference.frameIndex<0||returnReference.frameIndex>=(target.timeline?.frames?.length||0))return null;return target}
 function mode(on){const playback=document.querySelector('.playback');if(playback)playback.hidden=on;for(const id of ['airWorkspace','advancedTools']){const element=$(id);if(element)element.hidden=on;}}
 function render(){
  const root=$('directWorkspace'),layout=document.querySelector('.layout'),item=current();if(!root)return;
  root.hidden=!item;if(layout)layout.hidden=Boolean(item);mode(Boolean(item));if(!item)return;
  $('character').textContent=model.character||'';$('moveTitle').textContent='— '+item.label;
  const owner=item.owner?esc(item.owner.title||item.owner.signature||item.owner.kind):'No enclosing StateDef/function was proven';
  const hitdef=item.kind==='hitdef',state=hitdef?null:codeDraftStore.actionState(item),shared=item.shared?' · shared source':'';
  const source=hitdef?'<h3>Source inspection</h3><pre class="direct-source">'+esc(item.sourceText||'')+'</pre>':'<p class="muted">Edit this exact '+esc(item.kind)+' block. Apply changes only the open text document, so normal Undo and Save remain available.'+(item.shared?' This assigned shared file may affect other characters.':'')+'</p>'+(state.conflict?'<div class="problem error"><b>SOURCE CHANGED</b> — compare the current block, then rebase or discard this retained draft.</div>':'')+'<textarea id="directCodeEditor" class="code-editor" spellcheck="false">'+esc(codeDraftStore.value(item))+'</textarea><div class="code-actions"><button id="applyDirectCode" '+(!state.canApply?'disabled':'')+'>Apply to open document</button>'+(state.conflict?'<button id="rebaseDirectCode" '+(state.pending?'disabled':'')+'>Use current source as base</button>':'')+'<button id="discardDirectCode" '+(!state.canDiscard?'disabled':'')+'>Discard draft</button><button id="behaviorMaps">Browse Maps…</button></div>';
  root.innerHTML='<div class="direct-heading"><div><h2>'+esc(item.label)+'</h2><p class="muted">Direct '+esc(item.syntax.toUpperCase())+' '+esc(item.kind)+' · '+esc(item.fileLabel)+':'+(item.line+1)+'–'+(item.endLine+1)+shared+'</p></div><div class="direct-actions">'+(hitdef?'<button id="editDirectHitDef">Edit HitDef</button>':'')+'<button id="openDirectSource">Open source</button>'+(model.moves?.length?'<button id="returnDirectConstants">Return to constants profile</button>':'')+'<button id="directOverview">Moves / Overview</button></div></div><div class="direct-grid"><section class="card">'+(hitdef?'<h3>Owning block</h3><p>'+owner+'</p><p class="muted">The owner is context only. This exact controller remains selected; equal state numbers and callers are not merged.</p>':'<h3>Exact source block</h3>')+source+'</section><aside class="card"><h3>Preview</h3><p class="muted">'+esc(model.previewUnavailable||'No animation is inferred from a StateDef number. Choose an exact AIR action separately when one is known.')+'</p>'+(item.controllers?.length?'<h3>Controllers in this block</h3><p>'+esc(item.controllers.join(', '))+'</p>':'')+'<h3>Problems</h3>'+((item.diagnostics||[]).map(problem=>'<button class="overview-entry" data-direct-problem="'+esc(problem.line)+'">'+esc(problem.message)+'<br><span class="muted">'+esc(problem.source||'IKEMEN')+' · line '+(problem.line+1)+'</span></button>').join('')||'<p class="muted">No diagnostics intersect this exact component.</p>')+'</aside></div>';
  if($('editDirectHitDef'))$('editDirectHitDef').onclick=()=>vscode.postMessage({type:'editDirectComponent',reference:item.reference});$('openDirectSource').onclick=()=>vscode.postMessage({type:'openDirectComponent',reference:item.reference});
  if(!hitdef){const area=$('directCodeEditor'),sync=()=>{const next=codeDraftStore.actionState(item);$('applyDirectCode').disabled=!next.canApply;$('discardDirectCode').disabled=!next.canDiscard;if($('rebaseDirectCode'))$('rebaseDirectCode').disabled=next.pending;};area.oninput=()=>{codeDraftStore.stage(item,area.value);renderHeader();sync()};$('applyDirectCode').onclick=()=>{if(codeDraftStore.apply(item,item.reference)){$('status').textContent='Applying exact '+item.kind+' block…';sync()}};$('discardDirectCode').onclick=()=>{codeDraftStore.discard(item);render();renderHeader()};if($('rebaseDirectCode'))$('rebaseDirectCode').onclick=()=>{codeDraftStore.rebase(item);render();renderHeader()};$('behaviorMaps').onclick=()=>vscode.postMessage({type:'openBehaviorMaps',reference:item.reference});}
  if($('returnDirectConstants'))$('returnDirectConstants').onclick=()=>{const target=validReturn();reference=null;persist();if(target)selectMove(target.id,undefined,returnReference.frameIndex);else{move=null;$('status').textContent='The previous constants profile changed or was removed. Choose a current profile from Moves / Overview.';render();moveOverviewUi.render()}};
  $('directOverview').onclick=()=>$('moveOverview').click();document.querySelectorAll('[data-direct-problem]').forEach(button=>button.onclick=()=>vscode.postMessage({type:'openDirectDiagnostic',reference:item.reference,line:Number(button.dataset.directProblem)}));
  moveOverviewUi.render();renderHeader();
 }
 function select(next){moveDrafts.stage();stop();if(move)returnReference=constantsReference();reference=next;move=null;persist();render();saveState();vscode.postMessage({type:'moveIntegrationContext',componentReference:next})}
 function clear(){if(!reference){mode(false);return;}reference=null;persist();const root=$('directWorkspace'),layout=document.querySelector('.layout');if(root)root.hidden=true;if(layout)layout.hidden=false;mode(false)}
 function beforeRender(){if(!current())return false;render();return true}
 function restoreInitial(){const savedReference=reference,requested=model.openReference?.componentReference||savedReference||(!model.moves?.length?components()[0]?.reference:null);if(!requested)return false;const item=components().find(candidate=>matches(candidate,requested));if(!item){reference=null;persist();$('status').textContent='The saved direct component changed or was removed. Choose it again from Moves / Overview.';move=null;render();moveOverviewUi.render();return false}select(item.reference);return true}
 function modelChanged(){if(!reference)return false;if(current()){persist();render();return true;}reference=null;persist();$('status').textContent='The selected exact code component changed or was removed. Choose it again from Moves / Overview.';const target=validReturn();if(target)selectMove(target.id,undefined,returnReference.frameIndex);else{move=null;render();moveOverviewUi.render()}return true}
 function applyFailed(requestId){codeDraftStore.failed(requestId);const item=current();if(item){const state=codeDraftStore.actionState(item);if($('applyDirectCode'))$('applyDirectCode').disabled=!state.canApply;if($('discardDirectCode'))$('discardDirectCode').disabled=!state.canDiscard;if($('rebaseDirectCode'))$('rebaseDirectCode').disabled=state.pending;}renderHeader();$('status').textContent='Connected-code apply was stopped; the draft is retained.'}
 window.addEventListener('message',event=>{if(event.data?.type==='directComponentSelect')select(event.data.reference)},true);
 window.addEventListener('message',event=>{if(event.data?.type==='codeSectionApplied'&&event.data.nextComponentReference&&reference&&event.data.id===current()?.stableId){reference=event.data.nextComponentReference;persist()}},true);
 return{select,clear,beforeRender,restoreInitial,current,matches,hasSelection:()=>Boolean(reference),modelChanged,applyFailed,validReturn};
}
module.exports={clientScript:()=>`const moveDirectUi=(${client.toString()})();`};
