'use strict';

function client(){
 let reference=saved.directComponent&&typeof saved.directComponent==='object'?saved.directComponent:null;
 let returnReference=saved.directReturnReference&&typeof saved.directReturnReference==='object'?saved.directReturnReference:null;
 let airSelections=saved.componentAirSelections&&typeof saved.componentAirSelections==='object'?{...saved.componentAirSelections}:{};
 const canonical=value=>String(value||'').replace(/\\/g,'/').toLowerCase();
 const ownerEqual=(a,b)=>(!a&&!b)||Boolean(a&&b&&a.kind===b.kind&&a.signature===b.signature&&a.startLine===b.startLine&&a.endLine===b.endLine);
 const matches=(candidate,wanted)=>Boolean(candidate&&wanted&&['hitdef','state','function','helper','explod','projectile'].includes(candidate.kind)&&candidate.kind===wanted.kind&&canonical(candidate.reference?.defPath||candidate.defPath)===canonical(model.files.defPath)&&canonical(wanted.defPath)===canonical(model.files.defPath)&&candidate.id===wanted.id&&canonical(candidate.filename)===canonical(wanted.filename)&&candidate.index===wanted.index&&candidate.line===wanted.line&&candidate.endLine===wanted.endLine&&candidate.sourceHash===wanted.sourceHash&&candidate.rangeHash===wanted.rangeHash&&String(candidate.signature||'')===String(wanted.signature||'')&&ownerEqual(candidate.owner,wanted.owner));
 const components=()=>[...(model.directComponents||[]),...(model.behaviorComponents||[]),...(model.specialistComponents||[])];
 const current=()=>reference?components().find(item=>matches(item,reference)):null;
 const persist=()=>vscode.setState({...vscode.getState(),directComponent:reference,directReturnReference:returnReference,componentAirSelections:{...airSelections}});
 const constantsReference=()=>move?{kind:'constants',defPath:model.files.defPath,profileId:move.id,prefix:move.prefix,sourceFilename:model.files.constants||'',sourceHash:model.timingSources?.constants||'',actionNumber:move.timeline?.actionNumber,frameIndex:frame}:null;
 function validReturn(){if(!returnReference||returnReference.kind!=='constants'||canonical(returnReference.defPath)!==canonical(model.files.defPath)||canonical(returnReference.sourceFilename)!==canonical(model.files.constants||'')||returnReference.sourceHash!==(model.timingSources?.constants||''))return null;const target=model.moves.find(item=>item.id===returnReference.profileId&&item.prefix===returnReference.prefix);if(!target||target.timeline?.actionNumber!==returnReference.actionNumber||!Number.isInteger(returnReference.frameIndex)||returnReference.frameIndex<0||returnReference.frameIndex>=(target.timeline?.frames?.length||0))return null;return target}
 function mode(on){const playback=document.querySelector('.playback');if(playback)playback.hidden=on;for(const id of ['airWorkspace','advancedTools']){const element=$(id);if(element)element.hidden=on;}}
 function render(){
  const root=$('directWorkspace'),layout=document.querySelector('.layout'),item=current();if(!root)return;
  root.hidden=!item;if(layout)layout.hidden=Boolean(item);mode(Boolean(item));if(!item)return;
  $('character').textContent=model.character||'';$('moveTitle').textContent='— '+item.label;
  const owner=item.owner?esc(item.owner.title||item.owner.signature||item.owner.kind):'No enclosing StateDef/function was proven';
  const hitdef=item.kind==='hitdef',behavior=['state','function'].includes(item.kind),specialist=['helper','explod','projectile'].includes(item.kind),state=behavior?codeDraftStore.actionState(item):null,shared=item.shared?' · shared source':'';
  const source=!behavior?'<h3>Source inspection</h3><pre class="direct-source">'+esc(item.sourceText||'')+'</pre>':'<p class="muted">Edit this exact '+esc(item.kind)+' block. Apply changes only the open text document, so normal Undo and Save remain available.'+(item.shared?' This assigned shared file may affect other characters.':'')+'</p>'+(state.conflict?'<div class="problem error"><b>SOURCE CHANGED</b> — compare the current block, then rebase or discard this retained draft.</div>':'')+'<textarea id="directCodeEditor" class="code-editor" spellcheck="false">'+esc(codeDraftStore.value(item))+'</textarea><div class="code-actions"><button id="applyDirectCode" '+(!state.canApply?'disabled':'')+'>Apply to open document</button>'+(state.conflict?'<button id="rebaseDirectCode" '+(state.pending?'disabled':'')+'>Use current source as base</button>':'')+'<button id="discardDirectCode" '+(!state.canDiscard?'disabled':'')+'>Discard draft</button><button id="behaviorMaps">Browse Maps…</button></div>';
  const specialistLabel=item.kind==='helper'?'Open Helper Lab separately':item.kind==='explod'?'Open Explod Composer separately':'';
  const nested=(item.contextPath||[]).length?'<h3>Nested execution context</h3><p>'+esc(item.contextPath.map(value=>value.title||value.signature||value.kind).join(' → '))+'</p>':'';
  const receivers=(item.receiverHints||[]).length?'<h3>Receiver names mentioned</h3><p>'+esc(item.receiverHints.join(', '))+'</p><p class="muted">These names occur in this exact controller or its nested execution path. They are shown as context, not inferred ownership.</p>':'';
  const classicKeys=['attr','damage','pausetime','guard.pausetime','ground.hittime','ground.slidetime','guard.hittime','guard.slidetime','air.hittime','ground.velocity','guard.velocity','air.velocity','yaccel','sparkno','guard.sparkno','sparkxy'],values=item.hitdefValues||{},classic=classicKeys.filter(key=>Object.prototype.hasOwnProperty.call(values,key)),other=Object.keys(values).filter(key=>!classicKeys.includes(key));
  const valueRows=keys=>keys.map(key=>'<div class="quick-field"><span>'+esc(key)+'</span><code>'+esc(values[key])+'</code></div>').join('');
  const hitdefSummary=hitdef?'<h3>Authored classic HitDef values</h3>'+(classic.length?'<div class="quick-grid">'+valueRows(classic)+'</div>':'<p class="muted">No classic contact fields are explicitly authored in this controller.</p>')+(other.length?'<details><summary>Other authored options · '+other.length+'</summary><div class="quick-grid">'+valueRows(other)+'</div></details>':'')+((item.hitdefDuplicates||[]).length?'<div class="problem warning">Duplicate option names remain source-owned and must be resolved in text before guarded editing: '+esc([...new Set(item.hitdefDuplicates)].join(', '))+'</div>':'')+'<p class="muted">These values are read-only here. Edit HitDef opens the established guarded field editor; custom and unknown options are preserved.</p>':'';
  const actions=model.airActions||[],airKey=[item.id,item.sourceHash,item.rangeHash].join('|'),remembered=Number(airSelections[airKey]),selected=actions.some(action=>action.number===remembered)?remembered:null,airContext=model.files?.air?'<h3>AIR / Clsn context</h3>'+(actions.length?'<label>Assigned AIR action <select id="componentAirAction"><option value="">Choose an action…</option>'+actions.map(action=>'<option value="'+action.number+'" '+(action.number===selected?'selected':'')+'>Action '+action.number+' · '+action.frames+' frames · '+action.ticks+' ticks</option>').join('')+'</select></label><p id="componentAirSummary" class="muted"></p><button id="openComponentAirAction" disabled>Open selected action in AIR / Clsn</button>':'<p class="muted">The assigned AIR currently has no complete actions. No animation is inferred from this component number.</p>'):'<h3>AIR / Clsn context</h3><p class="muted">No assigned AIR is available. IKEMaker will not guess another animation source.</p>';
  root.innerHTML='<div class="direct-heading"><div><h2>'+esc(item.label)+'</h2><p class="muted">Direct '+esc(item.syntax.toUpperCase())+' '+esc(item.kind)+' · '+esc(item.fileLabel)+':'+(item.line+1)+'–'+(item.endLine+1)+shared+'</p></div><div class="direct-actions">'+(hitdef?'<button id="editDirectHitDef">Edit HitDef</button>':'')+(specialistLabel?'<button id="openSpecialistComponent">'+specialistLabel+'</button>':'')+'<button id="openDirectSource">Open source</button>'+(model.moves?.length?'<button id="returnDirectConstants">Return to constants profile</button>':'')+'<button id="directOverview">Moves / Overview</button></div></div><div class="direct-grid"><section class="card">'+(!behavior?'<h3>Owning block</h3><p>'+owner+'</p><p class="muted">The owner is context only. Selecting this exact controller does not create, convert, or rewrite code.</p>':'<h3>Exact source block</h3>')+nested+receivers+hitdefSummary+source+(specialist?'<p class="muted">The specialist button opens the established tool separately; this source selection remains unchanged until you explicitly apply an edit there.</p>':'')+'</section><aside class="card"><h3>Preview</h3><p class="muted">'+esc(model.previewUnavailable||'No animation is inferred from a StateDef number. Choose an exact AIR action separately when one is known.')+'</p>'+airContext+(item.controllers?.length?'<h3>Controllers in this block</h3><p>'+esc(item.controllers.join(', '))+'</p>':'')+'<h3>Problems</h3>'+((item.diagnostics||[]).map(problem=>'<button class="overview-entry" data-direct-problem="'+esc(problem.line)+'">'+esc(problem.message)+'<br><span class="muted">'+esc(problem.source||'IKEMEN')+' · line '+(problem.line+1)+'</span></button>').join('')||'<p class="muted">No diagnostics intersect this exact component.</p>')+'</aside></div>';
  for(const [id,destination] of [['editDirectHitDef','move_lab'],['openSpecialistComponent','move_lab'],['openComponentAirAction','air'],['openDirectSource','code'],['directOverview','move_lab']])if($(id))$(id).dataset.ikemenDestination=destination;
  if($('editDirectHitDef'))$('editDirectHitDef').onclick=()=>vscode.postMessage({type:'editDirectComponent',reference:item.reference});$('openDirectSource').onclick=()=>vscode.postMessage({type:'openDirectComponent',reference:item.reference});
  if($('openSpecialistComponent'))$('openSpecialistComponent').onclick=()=>vscode.postMessage({type:'openSpecialistComponent',reference:item.reference});
  if($('componentAirAction')){const select=$('componentAirAction'),summary=$('componentAirSummary'),open=$('openComponentAirAction'),chosen=()=>select.value===''?null:actions.find(candidate=>candidate.number===Number(select.value)),update=()=>{const action=chosen();open.disabled=!action;summary.textContent=action?'Action '+action.number+' starts at AIR line '+action.line+'. Clsn1: '+action.clsn1Frames+'/'+action.frames+' frames ('+action.clsn1Boxes+' boxes). Clsn2: '+action.clsn2Frames+'/'+action.frames+' frames ('+action.clsn2Boxes+' boxes).'+(action.hasLoopStart?' Loop starts at element '+(action.loopStart+1)+'.':' No explicit LoopStart.'):'Choose one real assigned action. This selection is remembered for this exact component and does not edit source.';};select.value=selected===null?'':String(selected);select.onchange=()=>{const action=chosen();if(action)airSelections[airKey]=action.number;else delete airSelections[airKey];persist();update()};open.onclick=()=>{const action=chosen();if(action)vscode.postMessage({type:'openComponentAirAction',reference:item.reference,action:action.number})};update();}
  if(behavior){const area=$('directCodeEditor'),sync=()=>{const next=codeDraftStore.actionState(item);$('applyDirectCode').disabled=!next.canApply;$('discardDirectCode').disabled=!next.canDiscard;if($('rebaseDirectCode'))$('rebaseDirectCode').disabled=next.pending;};area.oninput=()=>{codeDraftStore.stage(item,area.value);renderHeader();sync()};$('applyDirectCode').onclick=()=>{if(codeDraftStore.apply(item,item.reference)){$('status').textContent='Applying exact '+item.kind+' block…';sync()}};$('discardDirectCode').onclick=()=>{codeDraftStore.discard(item);render();renderHeader()};if($('rebaseDirectCode'))$('rebaseDirectCode').onclick=()=>{codeDraftStore.rebase(item);render();renderHeader()};$('behaviorMaps').onclick=()=>vscode.postMessage({type:'openBehaviorMaps',reference:item.reference});}
  if($('returnDirectConstants'))$('returnDirectConstants').onclick=()=>{const target=validReturn();reference=null;persist();if(target)selectMove(target.id,undefined,returnReference.frameIndex);else{move=null;$('status').textContent='The previous constants profile changed or was removed. Choose a current profile from Moves / Overview.';render();moveOverviewUi.render()}};
  $('directOverview').onclick=()=>$('moveOverview').click();document.querySelectorAll('[data-direct-problem]').forEach(button=>button.onclick=()=>vscode.postMessage({type:'openDirectDiagnostic',reference:item.reference,line:Number(button.dataset.directProblem)}));
  moveOverviewUi.render();renderHeader();
 }
 function select(next){moveDrafts.stage();stop();if(move)returnReference=constantsReference();reference=next;move=null;persist();render();saveState();vscode.postMessage({type:'moveIntegrationContext',componentReference:next})}
 function clear(){if(!reference){mode(false);return;}reference=null;persist();const root=$('directWorkspace'),layout=document.querySelector('.layout');if(root)root.hidden=true;if(layout)layout.hidden=false;mode(false)}
 function beforeRender(){if(!current())return false;render();return true}
 function restoreInitial(){const savedReference=reference,requested=model.openReference?.componentReference||savedReference||(!model.moves?.length?components()[0]?.reference:null);if(!requested)return false;const item=components().find(candidate=>matches(candidate,requested));if(!item){reference=null;persist();$('status').textContent='The saved direct component changed or was removed. Choose it again from Moves / Overview.';move=null;render();moveOverviewUi.render();return false}select(item.reference);return true}
 function modelChanged(){if(!reference)return false;if(current()){persist();render();return true;}reference=null;persist();$('status').textContent='The selected exact code component changed or was removed. Choose it again from Moves / Overview.';const target=validReturn();if(target)selectMove(target.id,undefined,returnReference.frameIndex);else{move=null;render();moveOverviewUi.render()}return true}
 function applyFailed(requestId){codeDraftStore.failed(requestId);const item=current();if(item){const state=codeDraftStore.actionState(item);if($('applyDirectCode'))$('applyDirectCode').disabled=!state.canApply;if($('discardDirectCode'))$('discardDirectCode').disabled=!state.canDiscard;if($('rebaseDirectCode'))$('rebaseDirectCode').disabled=state.pending;}renderHeader();$('status').textContent='Connected-code apply was stopped; the draft is retained.'}
 window.addEventListener('message',event=>{if(event.data?.type==='directComponentSelect')select(event.data.reference)},true);
 window.addEventListener('message',event=>{if(event.data?.type==='codeSectionApplied'&&event.data.nextComponentReference&&reference&&event.data.id===current()?.stableId){reference=event.data.nextComponentReference;persist()}},true);
 return{select,clear,beforeRender,restoreInitial,current,matches,hasSelection:()=>Boolean(reference),modelChanged,applyFailed,validReturn};
}
module.exports={clientScript:()=>`const moveDirectUi=(${client.toString()})();`};
