'use strict';

const vscode = require('vscode');
const fs = require('fs');
const path = require('path');
const { parseDef, sections, value, unquote } = require('./def_model');
const { gameRoot, characterDefs } = require('./character_context');
const detectionCache=require('./versioned_file_cache').createCache();
const { parseAirInventory } = require('./requirements');
const { readSff, friendlyVersion } = require('./sff_reader');
const { hash, transactionalWrite } = require('./mutation_safety');
const workflow = require('./production_workflow_model');
const tickets = require('./team_ticket_model');
const feedback = require('./feedback_context');
const { chooseCharacterDef } = require('./character_picker');
const { launchControlsHtml, launchControlsClientScript, handleLaunchMessage } = require('./launch_controls');
const { registerCharacterToolPanel } = require('./authoring_context_registry');
const { preferredViewerColumn, trackViewerPanel, revealInViewerGroup } = require('./viewer_group');

let activeSession = null,actionQueue=Promise.resolve();
const workflowSessions=new Map();
const sessionKey=file=>path.resolve(file).toLowerCase();
const {WorkflowDrafts}=require('./workflow_drafts');
let drafts=new WorkflowDrafts();
const workflowFiles=state=>[state.progressPath,state.ticketPath];
function autoSave(state){return vscode.workspace.getConfiguration?.('ikemenZss',vscode.Uri.file(state.character.defPath)).get('autoSave',false)||false;}
async function stageWorkflow(state,file,value,expectedHash){await drafts.stage(file,value,expectedHash);if(autoSave(state))await drafts.save(workflowFiles(state));}
async function previewData(filename,value){const document=await vscode.workspace.openTextDocument({language:'json',content:JSON.stringify(value,null,2)+'\n'});await vscode.window.showTextDocument(document,{preview:false});}
function cohesive(page) { return page.replace('</header>', `${launchControlsHtml('production_workflow')}</header>`).replace('</script></body>', `${require('./workflow_selection').clientScript()}${launchControlsClientScript()}</script></body>`); }
function safeId(value) { return String(value || 'character').replace(/[^A-Za-z0-9_.-]+/g, '-').replace(/^-+|-+$/g, '') || 'character'; }
function isCharacterDef(filename) { try { const doc = parseDef(fs.readFileSync(filename, 'utf8'), filename), files = sections(doc, 'Files')[0]; return Boolean(files && (value(files, 'sprite') || value(files, 'anim') || value(files, 'cns') || value(files, 'st'))); } catch (_) { return false; } }
function characterContext(defPath) {
  const text = fs.readFileSync(defPath, 'utf8'), document = parseDef(text, defPath), files = sections(document, 'Files')[0], info = sections(document, 'Info')[0], folder = path.dirname(defPath), root = gameRoot(defPath) || folder;
  const resolve = (key) => { const reference = unquote(value(files, key, '')); return reference ? path.resolve(folder, reference.replace(/[\\/]/g, path.sep)) : ''; };
  const code = ['st', 'st1', 'st2', 'st3', 'st4', 'st5', 'st6', 'st7', 'st8', 'st9', 'cns'].map(resolve).filter(Boolean);
  const name = unquote(value(info, 'displayname', '')) || unquote(value(info, 'name', '')) || path.basename(folder);
  return { contentVersion: feedback.definitionContext(text, defPath, 'Character').contentVersion, id: safeId(path.relative(path.join(root, 'chars'), folder) || path.basename(folder)), name, root, folder, defPath, sff: resolve('sprite'), air: resolve('anim'), snd: resolve('sound'), cmd: resolve('cmd'), constants: resolve('cns'), code: [...new Set(code)] };
}
function projectProfileDirectory(character) { return path.join(character.root, '.ikemen', 'workflow-profiles'); }
function settingsPath(character) { return path.join(character.root, '.ikemen', 'workflow-settings.json'); }
function progressPath(character) { return path.join(character.root, '.ikemen', 'workflows', 'characters', `${safeId(character.id)}.json`); }
function ticketPath(character) { return path.join(character.root, '.ikemen', 'workflows', 'team-board.json'); }
function bundledProfileDirectory(context) { return path.join(context.extensionPath, 'data', 'workflow-profiles'); }
function bundledBlockDirectory(context) { return path.join(context.extensionPath, 'data', 'workflow-blocks'); }
function bundledProfile(context, id = 'sf-character-production') {
  const match = jsonCandidates(bundledProfileDirectory(context), true).find((item) => String(item.raw?.id || '').toLowerCase() === String(id).toLowerCase());
  return match?.filename || path.join(bundledProfileDirectory(context), 'SF-character-production.json');
}
function workflowGuide(context) { return path.join(context.extensionPath, 'data', 'Production-Workflow-Guide.md'); }
function readJson(filename, fallback = null) { try { return JSON.parse(fs.readFileSync(filename, 'utf8')); } catch (_) { return fallback; } }
function writeData(filename, value, label, expectedHash = '') { return transactionalWrite(fs, filename, `${JSON.stringify(value, null, 2)}\n`, { label, journalRoot: path.dirname(path.dirname(filename)), backup: false, journal: false, expectedHash: expectedHash || undefined }); }
function jsonCandidates(directory, bundled = false) {
  if (!fs.existsSync(directory)) return [];
  return fs.readdirSync(directory).filter((name) => /\.json$/i.test(name)).map((name) => { const filename = path.join(directory, name), raw = readJson(filename, {}); return { label: raw.name || name.replace(/\.json$/i, ''), description: `${raw.id || 'unidentified'} · v${raw.version || 1}${bundled ? ' · bundled' : ''}`, filename, bundled, raw }; });
}
function profileCandidates(context, character) {
  const output = jsonCandidates(bundledProfileDirectory(context), true), directory = projectProfileDirectory(character);
  if (fs.existsSync(directory)) for (const name of fs.readdirSync(directory)) if (/\.json$/i.test(name)) output.push({ label: name.replace(/\.json$/i, ''), filename: path.join(directory, name), bundled: false });
  return output;
}
function blockCandidates(context, character) { return [...jsonCandidates(bundledBlockDirectory(context), true), ...jsonCandidates(path.join(character.root, '.ikemen', 'workflow-blocks'), false)]; }
function activeProfilePath(context, character) {
  const settings = readJson(settingsPath(character), {}), configured = String(settings.defaultProfile || '');
  if (/^bundled:/i.test(configured)) return bundledProfile(context, configured.slice(8));
  if (configured) { const target = path.isAbsolute(configured) ? configured : path.resolve(character.root, '.ikemen', configured); if (fs.existsSync(target)) return target; }
  const project = path.join(projectProfileDirectory(character), 'JNP-character-production.json'); return fs.existsSync(project) ? project : bundledProfile(context);
}
function loadProfileFile(context, character, filename, seen = new Set()) {
  const resolved = path.resolve(filename); if (seen.has(resolved.toLowerCase())) throw new Error(`Workflow profile inheritance loop: ${resolved}`); seen.add(resolved.toLowerCase());
  const raw = readJson(resolved); if (!raw) throw new Error(`Could not read workflow profile: ${resolved}`);
  let profile;
  if (!raw.extends) profile = workflow.normalizeProfile(raw);
  else {
    let basePath = raw.extends;
    if (/^bundled:/i.test(basePath)) { const id = basePath.slice(8).toLowerCase(), match = profileCandidates(context, character).find((item) => item.bundled && String(item.raw?.id || '').toLowerCase() === id); if (!match) throw new Error(`Bundled workflow profile not found: ${id}`); basePath = match.filename; }
    else if (!path.isAbsolute(basePath)) basePath = path.resolve(path.dirname(resolved), basePath);
    profile = workflow.mergeProfiles(loadProfileFile(context, character, basePath, seen), raw);
  }
  for (const reference of raw.blocks || []) {
    let blockPath = reference;
    if (/^bundled-block:/i.test(reference)) { const id = reference.slice(14).toLowerCase(), match = blockCandidates(context, character).find((item) => item.bundled && String(item.raw?.id || '').toLowerCase() === id); if (!match) throw new Error(`Bundled workflow block not found: ${id}`); blockPath = match.filename; }
    else if (!path.isAbsolute(blockPath)) blockPath = path.resolve(path.dirname(resolved), blockPath);
    const block = readJson(blockPath); if (!block) throw new Error(`Could not read workflow block: ${blockPath}`);
    profile = workflow.applyBlock(profile, block);
  }
  return profile;
}
function detection(state, detail, files = []) { return { state, detail, files: files.filter(Boolean) }; }
function issueProject(state,parentId){const parent=parentId&&state.ticketBoard.tickets.find(item=>item.id===parentId);if(parent)return {workProjectId:parent.workProjectId||'',gameProjectId:parent.gameProjectId||'',project:parent.project||state.ticketBoard.project};return {workProjectId:state.assignedWorkProject?.id||'',gameProjectId:state.assignedWorkProject?.gameId||'',project:state.assignedWorkProject?.name||state.ticketBoard.project};}
function actorFor(character) { try { const config = vscode.workspace.getConfiguration('ikemenZss', vscode.Uri.file(character.defPath)); return config.get('productionWorkflow.actor', '') || config.get('authorName', '') || 'Team member'; } catch (_) { return 'Team member'; } }
function detections(character) {
  const result = {}, required = [character.defPath, character.sff, character.air, character.cmd, character.constants, ...character.code].filter(Boolean), missing = required.filter((file) => !fs.existsSync(file));
  result['character-files'] = detection(missing.length ? 'missing' : 'detected', missing.length ? `${missing.length} assigned file(s) are missing.` : `${required.length} assigned character files were found.`, missing);
  if (!character.sff || !fs.existsSync(character.sff)) result['sff-readable'] = detection('missing', 'No assigned SFF file was found.', [character.sff]);
  else try { const summary=detectionCache.get(character.sff,'sff-summary-v1',file=>{const archive=readSff(file);return{version:friendlyVersion(archive.header?.version),sprites:archive.sprites.length,palettes:(archive.palettes||[]).length};});const version=summary.version; result['sff-readable'] = detection('detected', `SFF v${version} opened with ${summary.sprites} sprites and ${summary.palettes} palettes.`, [character.sff]); } catch (error) { result['sff-readable'] = detection('warning', `The SFF exists but could not be read: ${error.message}`, [character.sff]); }
  let actions = new Map(); if (character.air && fs.existsSync(character.air)) actions = new Set(detectionCache.get(character.air,'air-inventory-v1',file=>[...parseAirInventory(fs.readFileSync(file,'utf8')).keys()]));
  const basic = [0, 5, 6, 10, 11, 12, 20, 21, 40, 41, 42, 43, 44, 45, 50, 51, 52], basicFound = basic.filter((number) => actions.has(number));
  result['basic-actions'] = detection(basicFound.length ? 'detected' : 'missing', `${basicFound.length}/${basic.length} common movement actions were detected. Human review still determines whether they are correct.`, [character.air]);
  const gethits = [5000, 5001, 5002, 5010, 5011, 5012, 5020, 5030, 5035, 5040, 5050, 5060, 5070, 5080, 5100, 5110, 5120, 5150, 5160, 5170, 5180, 5200, 5210], hitFound = gethits.filter((number) => actions.has(number));
  result['gethit-actions'] = detection(hitFound.length ? 'detected' : 'missing', `${hitFound.length}/${gethits.length} common get-hit actions were detected. Project requirements remain authoritative.`, [character.air]);
  const patterns=[/\bStateDef\s+200\b/i,/\bsLP\b/i,/standing\s+light\s+punch/i,/HitDef\s*\{/i];
  const signals=character.code.filter(fs.existsSync).map(file=>detectionCache.get(file,'slp-signals-v1',filename=>{const text=fs.readFileSync(filename,'utf8');return patterns.map(pattern=>pattern.test(text));}));
  const slpSignals=patterns.filter((_,index)=>signals.some(found=>found[index])).length;
  result['slp-code'] = detection(slpSignals ? 'detected' : 'missing', `${slpSignals}/4 sLP code signals were found. Detection does not verify frame data or gameplay behavior.`, character.code);
  return result;
}
function issueDraftKey(character) { return 'ikemaker.issueDraft.v1:' + path.resolve(character.defPath).toLowerCase(); }
function loadState(context, character) {
  const profilePath = activeProfilePath(context, character), profile = loadProfileFile(context, character, profilePath), filename = progressPath(character), raw = drafts.read(filename, readJson(filename, null)), progress = workflow.reconcileProgress(profile, raw, character), detected = detections(character), phases = workflow.decorate(profile, progress, detected);
  const actor = actorFor(character), allNext = workflow.nextTasks(phases, Number.MAX_SAFE_INTEGER), personal = allNext.filter((step) => !step.progress.assignedTo || step.progress.assignedTo.toLowerCase() === actor.toLowerCase());
  const teamPath = ticketPath(character), ticketBoard = tickets.normalizeBoard(drafts.read(teamPath, readJson(teamPath, { project: path.basename(character.root), tickets: [] })));
  let assignedTeam = null, assignedWorkProject = null;
  try {
    const loaded = require('./project_context_ui').readRegistry(character.root), registryRoot = path.dirname(path.dirname(loaded.filename)), characterRoot = path.resolve(character.folder).toLowerCase();
    const matches = loaded.registry.workProjects.map((item) => ({ item, root: path.resolve(registryRoot, item.root || '.') })).filter((entry) => characterRoot === entry.root.toLowerCase() || characterRoot.startsWith(`${entry.root.toLowerCase()}${path.sep}`)).sort((a, b) => b.root.length - a.root.length);
    assignedWorkProject = matches[0]?.item || null;
    assignedTeam = assignedWorkProject?.teamId ? loaded.registry.teams.find((item) => item.id === assignedWorkProject.teamId) || null : null;
  } catch (_) {}
  const profileIsBundled = path.resolve(profilePath).toLowerCase().startsWith(`${path.resolve(bundledProfileDirectory(context)).toLowerCase()}${path.sep}`);
  return { issueDraft: context.workspaceState?.get(issueDraftKey(character), null) || null, hasDraft: drafts.has(filename)||drafts.has(teamPath), reportContext: feedback.reportContext({ character, profile }, readJson(path.join(context.extensionPath, 'package.json'), {}).version || 'Unknown'), itemTypes: feedback.ITEM_TYPES, character, actor, profile, profilePath, profileIsBundled, progress, progressPath: filename, progressHash: fs.existsSync(filename) ? hash(fs.readFileSync(filename)) : '', detections: detected, phases, next: personal.slice(0, 8), board: workflow.teamBoard(phases), ticketBoard, ticketPath: teamPath, ticketHash: fs.existsSync(teamPath) ? hash(fs.readFileSync(teamPath)) : '', assignedTeam, assignedWorkProject, ticketColumns: tickets.COLUMNS, ticketTypes: tickets.TYPES, summaries: Object.fromEntries(phases.map((phase) => [phase.id, workflow.phaseSummary(phase)])) };
}
function json(value) { return JSON.stringify(value).replace(/</g, '\\u003c'); }
function htmlText(value) { return String(value == null ? '' : value).replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character])); }
function html(data) { return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
:root{color-scheme:light dark}*{box-sizing:border-box}body{margin:0;font:13px var(--vscode-font-family);background:var(--vscode-editor-background);color:var(--vscode-foreground)}header{position:sticky;top:0;z-index:4;display:flex;align-items:center;gap:8px;padding:9px 12px;border-bottom:1px solid var(--vscode-panel-border);background:var(--vscode-editor-background)}button,select,input,textarea{font:inherit;color:inherit;background:var(--vscode-input-background);border:1px solid var(--vscode-input-border);padding:6px}button{cursor:pointer;background:var(--vscode-button-secondaryBackground)}.grow{flex:1}.tabs{display:flex;gap:5px;padding:8px 12px;border-bottom:1px solid var(--vscode-panel-border)}.tabs button.active{background:var(--vscode-button-background);color:var(--vscode-button-foreground)}main{padding:12px}.intro{padding:10px;background:var(--vscode-editor-inactiveSelectionBackground);margin-bottom:10px}.phase{border:1px solid var(--vscode-panel-border);margin:9px 0}.phase>summary{padding:9px;cursor:pointer;font-weight:700}.steps,.board{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:8px;padding:8px}.step{border:1px solid var(--vscode-panel-border);padding:9px;border-radius:4px}.step h3{margin:0 0 5px}.meta,.muted{color:var(--vscode-descriptionForeground)}.detection{margin:7px 0;padding:6px;border-left:3px solid var(--vscode-charts-blue);background:var(--vscode-textCodeBlock-background)}.detection.missing,.detection.warning{border-color:var(--vscode-charts-yellow)}.actions{display:flex;flex-wrap:wrap;gap:5px;margin-top:8px}.progress{height:7px;background:var(--vscode-progressBar-background);opacity:.35}.progress>span{display:block;height:100%;background:var(--vscode-charts-green);opacity:1}.badge{padding:2px 7px;border-radius:9px;background:var(--vscode-badge-background);color:var(--vscode-badge-foreground)}.note{white-space:pre-wrap;margin-top:5px}.hidden{display:none}.board-column{border-top:3px solid var(--vscode-focusBorder)}.ticket-tools{display:flex;gap:6px;align-items:center;margin:8px 0}.kanban{display:grid;grid-template-columns:repeat(7,minmax(270px,1fr));gap:8px;overflow-x:auto;padding:5px 0 14px}.kanban-column{background:var(--vscode-sideBar-background);border:1px solid var(--vscode-panel-border);min-height:240px;padding:7px}.kanban-column>h2{font-size:14px;margin:2px 0 8px}.ticket{background:var(--vscode-editor-background);border:1px solid var(--vscode-panel-border);border-left:4px solid var(--vscode-focusBorder);padding:8px;margin-bottom:8px}.ticket h3{margin:0 0 4px}.ticket-description{white-space:pre-wrap;max-height:100px;overflow:auto;margin:6px 0}.subtasks{margin:7px 0;padding-left:0;list-style:none}.subtasks label{display:flex;gap:5px;margin:3px 0}.ticket.done{opacity:.7}.count{float:right}.comments{max-height:90px;overflow:auto;margin-top:6px}.ticket select{max-width:125px}
header,.tabs,.ticket-tools{flex-wrap:wrap}header>*{min-width:0;max-width:100%}button{max-width:100%;overflow-wrap:anywhere}main,.step,.steps>*,.board>*{min-width:0}.steps,.board{grid-template-columns:repeat(auto-fit,minmax(min(100%,290px),1fr))}.ticket-tools h2{margin:0}.note,.meta,.ticket-description{overflow-wrap:anywhere}button:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible,summary:focus-visible{outline:2px solid var(--vscode-focusBorder);outline-offset:2px}@media(max-width:700px){header{position:static}.tabs{gap:5px}.ticket-tools .grow{display:none}.intro{overflow-wrap:anywhere}.kanban{grid-template-columns:repeat(7,minmax(250px,1fr))}}
</style></head><body><header><b>Production Workflow</b><span class="badge">${htmlText(data.profile.name)}</span><b>${htmlText(data.character.name)}</b><span class="grow"></span><button id="identity">Identity: ${htmlText(data.actor)}</button><button id="saveWorkflow">Save Workflow</button><button id="discardWorkflow">Discard Unsaved Changes</button><span id="saveStatus" role="status">${data.hasDraft ? 'Unsaved changes — kept locally until Save' : 'No unsaved changes'}</span><button id="refresh">Refresh</button><button id="chooseCharacter">Character…</button><button id="chooseProfile">Profile…</button><button id="profileTools">Profile tools…</button><button id="editProfile">${data.profileIsBundled ? 'Create editable project profile' : 'Edit profile'}</button><button id="openGuide">Profile guide</button><button id="openProgress">Progress file</button></header><nav class="tabs"><button data-view="tickets">Project Tickets</button><button data-view="reports">Report Intake</button><button data-view="inbox">My Inbox</button><button data-workspace-control="team-assignment" data-view="members">Team Directory</button><button data-view="next">My Next Tasks</button><button data-view="phases">Character Workflow</button><button data-view="lessons">Lessons</button><button data-workspace-control="team-handoff" data-view="team">Responsibilities</button></nav><main><div class="intro"><b>${htmlText(data.profile.description)}</b>${data.profile.sourceAuthority ? `<br><b>Source authority:</b> ${htmlText(data.profile.sourceAuthority)}` : ''}${data.profile.completionModel ? `<br><b>Complete means:</b> ${htmlText(data.profile.completionModel)}` : ''}${data.profile.ownershipScope ? `<br><b>Ownership:</b> ${htmlText(data.profile.ownershipScope)}` : ''}<br><span class="muted">Project tickets coordinate the team. Character Workflow is an optional reference, not the ticket hierarchy. Automated findings say DETECTED, never PASSED; human review owns completion.</span>${data.profile.appliedBlocks?.length ? `<br><span class="muted">Blocks: ${data.profile.appliedBlocks.map((entry) => `${htmlText(entry.name)} v${entry.version}`).join(' · ')}</span>` : ''}</div><div id="content"></div></main><script>
const vscode=acquireVsCodeApi();let data=${json(data)},view=vscode.getState()?.view||'tickets';const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function issueDraftIdentity(){return String(data.character.defPath).toLowerCase();}
const localIssueDrafts={...(vscode.getState()?.issueDrafts||{})};
function rememberIssueDraft(values){const key=issueDraftIdentity();localIssueDrafts[key]=values;vscode.setState({...vscode.getState(),view,issueDrafts:localIssueDrafts});vscode.postMessage({type:'issueDraft',defPath:data.character.defPath,values});}
function captureIssueDraft(){const form=$('issueForm');if(form)rememberIssueDraft(Object.fromEntries(new FormData(form)));}
function restoreIssueDraft(){const form=$('issueForm');if(!form)return;const key=issueDraftIdentity(),values=Object.prototype.hasOwnProperty.call(localIssueDrafts,key)?localIssueDrafts[key]:data.issueDraft;if(values)for(const [name,value]of Object.entries(values)){const field=form.elements.namedItem(name);if(field)field.value=value;}form.oninput=captureIssueDraft;form.onchange=captureIssueDraft;form.onreset=()=>rememberIssueDraft(null);}
function step(s){const p=s.progress,d=s.detection,guide=(s.description||s.learning||s.acceptance)?'<details><summary>Learning and acceptance</summary>'+(s.description?'<p>'+esc(s.description)+'</p>':'')+(s.learning?'<p><b>Why:</b> '+esc(s.learning)+'</p>':'')+(s.acceptance?'<p><b>Pass when:</b> '+esc(s.acceptance)+'</p>':'')+(s.dependsOn?.length?'<p><b>Depends on:</b> '+s.dependsOn.map(esc).join(', ')+'</p>':'')+'</details>':'';return '<article class="step"><h3>'+esc(s.label)+'</h3><div class="meta">'+esc(s.phaseName||'')+(s.discipline?' · '+esc(s.discipline):'')+(s.optional?' · optional':'')+(s.evidenceRequired?' · evidence required':'')+(s.signoffRequired?' · named owner sign-off required':'')+(s.lessonCapture?' · lesson packet':'')+(p.assignedTo?' · assigned to '+esc(p.assignedTo):' · unassigned')+'</div>'+guide+(d?'<div class="detection '+esc(d.state)+'"><b>'+esc(d.state.toUpperCase())+'</b> — '+esc(d.detail)+'</div>':'')+'<label>Status <select data-status="'+esc(s.id)+'">'+data.profile.statuses.map(x=>'<option value="'+esc(x)+'" '+(x===p.status?'selected':'')+'>'+esc(x.replaceAll('-',' '))+'</option>').join('')+'</select></label>'+(p.note?'<div class="note"><b>Note:</b> '+esc(p.note)+'</div>':'')+(p.evidence?.length?'<div class="note"><b>Evidence:</b><br>'+p.evidence.map(x=>'• '+esc(x.label)+': '+esc(x.value)).join('<br>')+'</div>':'')+'<div class="actions">'+(s.action?'<button data-action="'+esc(s.action)+'" data-id="'+esc(s.id)+'">Open work</button>':'')+'<button data-workspace-control="team-assignment" data-assign="'+esc(s.id)+'">Assign…</button><button data-note="'+esc(s.id)+'">Note…</button><button data-evidence="'+esc(s.id)+'">Evidence…</button>'+(s.lessonCapture?'<button data-lesson="'+esc(s.id)+'">Capture structured lesson…</button>':'')+'</div></article>'}
function lessonCard(l){return '<article class="step"><h3>'+esc(l.rule||'Untitled lesson')+'</h3><p><b>Game-specific exception:</b> '+esc(l.gameSpecificException||'None recorded')+'</p><p><b>Test procedure:</b> '+esc(l.testProcedure||'Not recorded')+'</p><p><b>Evidence:</b> '+esc(l.evidence||'Not recorded')+'</p><p><b>Known limitation:</b> '+esc(l.knownLimitation||'None recorded')+'</p><p><b>Owner sign-off:</b> '+esc(l.ownerSignoff||'Not signed off')+'</p><div class="meta">'+esc(l.actor||'Unknown')+' · '+esc(l.time||'')+'</div></article>'}
function ticket(t){const done=t.subtasks.filter(x=>x.done).length,total=t.subtasks.length,parent=data.ticketBoard.tickets.find(x=>x.id===t.parentId),children=data.ticketBoard.tickets.filter(x=>!x.archived&&x.parentId===t.id),childrenDone=children.filter(x=>x.column==='done').length,parts=t.type==='Epic'?children.length:total,complete=t.type==='Epic'?childrenDone:done;return '<article class="ticket '+(t.column==='done'?'done':'')+'"><h3>'+esc(t.title)+'</h3>'+(parent?'<div class="meta">↳ '+esc(parent.id)+' · '+esc(parent.title)+'</div>':'')+'<div class="meta"><b>'+esc(t.id)+'</b> · '+esc(t.type)+(t.character?' · '+esc(t.character):'')+(t.assignedTo?' · '+esc(t.assignedTo):' · unassigned')+'</div>'+(t.description?'<div class="ticket-description">'+esc(t.description)+'</div>':'')+'<div class="progress"><span style="width:'+(parts?Math.round(complete/parts*100):0)+'%"></span></div><div class="meta">'+(t.type==='Epic'?(childrenDone+'/'+children.length+' child tickets'):(done+'/'+total+' tasks'))+'</div><ul class="subtasks">'+t.subtasks.map(s=>'<li><label><input type="checkbox" data-ticket-task="'+esc(t.id)+'" data-task="'+esc(s.id)+'" '+(s.done?'checked':'')+'><span>'+esc(s.title)+(s.assignedTo?' · '+esc(s.assignedTo):'')+'</span></label></li>').join('')+'</ul>'+(children.length?'<details><summary>Child tickets ('+children.length+')</summary>'+children.map(c=>'<div>• <b>'+esc(c.id)+'</b> '+esc(c.title)+' — '+esc(c.column)+'</div>').join('')+'</details>':'')+(t.comments.length?'<details><summary>Discussion ('+t.comments.length+')</summary><div class="comments">'+t.comments.map(c=>'<div><b>'+esc(c.author)+':</b> '+esc(c.text)+'</div>').join('')+'</div></details>':'')+'<div class="actions"><select data-ticket-column="'+esc(t.id)+'">'+data.ticketColumns.map(c=>'<option value="'+c.id+'" '+(c.id===t.column?'selected':'')+'>'+esc(c.label)+'</option>').join('')+'</select>'+(t.type==='Epic'?'<button data-ticket-child="'+esc(t.id)+'">Child ticket…</button>':'<button data-ticket-task-add="'+esc(t.id)+'">Task…</button>')+'<button data-ticket-assign="'+esc(t.id)+'">Assign…</button><button data-ticket-comment="'+esc(t.id)+'">Comment…</button><button data-ticket-archive="'+esc(t.id)+'">Archive</button></div></article>'}
function wireTickets(){for(const s of document.querySelectorAll('[data-ticket-column]')){const t=data.ticketBoard.tickets.find(x=>x.id===s.dataset.ticketColumn),watching=t?.watchers.some(x=>x.toLowerCase()===data.actor.toLowerCase());s.parentElement.insertAdjacentHTML('beforeend','<button data-ticket-watch="'+esc(s.dataset.ticketColumn)+'">'+(watching?'Unwatch':'Watch')+' ('+(t?.watchers.length||0)+')</button>');s.onchange=()=>vscode.postMessage({type:'ticketColumn',id:s.dataset.ticketColumn,column:s.value})}for(const b of document.querySelectorAll('[data-ticket-watch]'))b.onclick=()=>vscode.postMessage({type:'ticketWatch',id:b.dataset.ticketWatch});for(const b of document.querySelectorAll('[data-ticket-child]'))b.onclick=()=>vscode.postMessage({type:'ticketChild',id:b.dataset.ticketChild});for(const b of document.querySelectorAll('[data-ticket-assign]'))b.onclick=()=>vscode.postMessage({type:'ticketAssign',id:b.dataset.ticketAssign});for(const b of document.querySelectorAll('[data-ticket-task-add]'))b.onclick=()=>vscode.postMessage({type:'ticketAddTask',id:b.dataset.ticketTaskAdd});for(const b of document.querySelectorAll('[data-ticket-comment]'))b.onclick=()=>vscode.postMessage({type:'ticketComment',id:b.dataset.ticketComment});for(const b of document.querySelectorAll('[data-ticket-archive]'))b.onclick=()=>vscode.postMessage({type:'ticketArchive',id:b.dataset.ticketArchive});for(const c of document.querySelectorAll('[data-ticket-task]'))c.onchange=()=>vscode.postMessage({type:'ticketTask',id:c.dataset.ticketTask,taskId:c.dataset.task,done:c.checked})}
function reportCard(r){return '<article class="step"><h3>'+esc(r.title)+'</h3><div class="meta"><b>'+esc(r.id)+'</b> · '+esc(r.status)+' · reported by '+esc(r.reporter||'unknown')+'</div><div class="ticket-description">'+esc(r.body)+'</div>'+(r.attachments.length?'<div class="meta">Attachments: '+r.attachments.map(esc).join(', ')+'</div>':'')+(r.decision?'<div class="note"><b>Decision:</b> '+esc(r.decision)+'</div>':'')+(r.status==='pending'?'<div class="actions"><button data-report-accept="'+esc(r.id)+'">Accept as ticket…</button><button data-report-reject="'+esc(r.id)+'">Reject…</button></div>':'')+'</article>'}
function memberCard(m){return '<article class="step"><h3>'+esc(m.name)+' <span class="badge">@'+esc(m.handle)+'</span></h3><div>'+m.roles.map(r=>'<span class="badge">'+esc(r)+'</span>').join(' ')+'</div><div class="meta">'+(m.active?'Active':'Inactive')+'</div><div class="actions"><button data-member-edit="'+esc(m.id)+'">Edit roles…</button><button data-member-active="'+esc(m.id)+'">'+(m.active?'Mark inactive':'Reactivate')+'</button></div></article>'}
function noticeCard(n){const t=data.ticketBoard.tickets.find(x=>x.id===n.ticketId);return '<article class="step"><h3>'+esc(n.ticketId)+(t?' · '+esc(t.title):'')+'</h3><div>'+esc(n.text)+'</div><div class="meta">'+esc(n.time)+'</div></article>'}
function issueDetails(item){return '<details><summary>Issue details</summary>'+[['Project',item.project||data.ticketBoard.project],['Work project ID',item.workProjectId],['Game project ID',item.gameProjectId],['Severity',item.severity],['IKEMaker version',item.toolVersion],['Item type',item.itemType],['Item name',item.itemName],['Item/content version',item.contentVersion],['Game/project profile',item.profile],['Screen/viewer',item.screen],['New use-case scenario',item.useCase],['Other build',item.build],['Steps to reproduce',item.steps],['Expected result',item.expected],['Actual result',item.actual],['Attachments',(item.attachments||[]).join(', ')]].filter(pair=>pair[1]).map(pair=>'<div class="note"><b>'+esc(pair[0])+':</b> '+esc(pair[1])+'</div>').join('')+'</details>'}
function issueForm(){
  const c=data.reportContext||{},field=(name,label,value='')=>'<label>'+label+'<input name="'+name+'" value="'+esc(value)+'" style="display:block;width:100%"></label>',area=(name,label,required=false)=>'<label style="display:block;margin:8px 0">'+label+'<textarea name="'+name+'" rows="3" style="display:block;width:100%;resize:vertical" '+(required?'required':'')+'></textarea></label>';
  return '<details class="step"><summary><b>Log a project issue or feedback</b></summary><form id="issueForm"><p>Project: <b>'+esc(data.assignedWorkProject?.name||data.ticketBoard.project)+'</b>. Saved to the shared game board; each issue keeps its work-project identity. IKEMaker '+esc(c.toolVersion||'Unknown')+' is recorded automatically.</p><label>Title (required)<input name="title" required style="display:block;width:100%"></label>'+area('body','What happened? (required)',true)+area('expected','What I would have liked to happen')+area('useCase','New use-case scenario (optional)')+area('attachments','Screenshots, mockups, logs or file references (optional, one path or link per line)')+'<details class="step"><summary>Context and reproduction details</summary><p class="muted">Current character and workflow are prefilled. Change these when reporting a different item. Choose a definition to read its declared name/version, or enter details manually; Unknown is accepted.</p><div class="steps"><label>Item type<select id="issueItemType" name="itemType" style="display:block;width:100%">'+(data.itemTypes||[]).map(x=>'<option '+(x===c.itemType?'selected':'')+'>'+esc(x)+'</option>').join('')+'</select></label>'+field('itemName','Item name',c.itemName)+field('contentVersion','Item/content version',c.contentVersion)+field('profile','Game/project profile',c.profile)+field('screen','IKEMaker screen or viewer',c.screen)+field('build','Game build or other version (optional)')+'<label>Severity<select name="severity" style="display:block;width:100%">'+['Untriaged','Low','Medium','High','Critical'].map(x=>'<option>'+x+'</option>').join('')+'</select></label></div><button type="button" id="issueDefinition">Read name/version from definition…</button>'+area('steps','Steps to reproduce')+area('actual','Additional observed result (optional)')+'</details><label>Destination <select name="destination"><option value="ticket" '+(view==='tickets'?'selected':'')+'>Create Bug ticket in Backlog</option><option value="report" '+(view==='reports'?'selected':'')+'>Submit feedback to Report Intake</option></select></label><p class="muted">Board scope: all work projects in this game share one board. Evidence entries are references; files are not uploaded or copied.</p><button type="submit">Save to project</button><button type="reset">Clear form</button></form></details>';
}
let issueProjectFilter=vscode.getState()?.issueProjectFilter||'all';
function inIssueProject(item){return issueProjectFilter==='all'||(issueProjectFilter==='unassigned'?!item.workProjectId:item.workProjectId===issueProjectFilter.slice(3));}
function projectFilterHtml(){const projects=new Map([...data.ticketBoard.tickets,...data.ticketBoard.reports].filter(item=>item.workProjectId).map(item=>[item.workProjectId,item.project||item.workProjectId]));if(data.assignedWorkProject)projects.set(data.assignedWorkProject.id,data.assignedWorkProject.name);const choices=[['all','All work projects in this game'],['unassigned','Legacy / no assigned work project'],...[...projects].map(([id,name])=>['id:'+id,name])];return '<label>Board filter <select id="issueProjectFilter">'+choices.map(([id,label])=>'<option value="'+esc(id)+'" '+(id===issueProjectFilter?'selected':'')+'>'+esc(label)+'</option>').join('')+'</select></label>';}
function render(){
  document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.view===view)); let out='';
  if(view==='tickets') out='<div class="ticket-tools"><h2>Project Tickets</h2><span class="grow"></span><button id="newTicket">New ticket…</button><button id="pasteReport">Paste report into intake</button><button id="openTickets">Open board data</button></div><p class="muted">Epic → child ticket → task checklist. Ticket creators and assignees watch their work automatically; comments notify watchers and @mentions.</p><div class="kanban">'+data.ticketColumns.map(c=>{const list=data.ticketBoard.tickets.filter(t=>!t.archived&&t.column===c.id&&inIssueProject(t));return '<section class="kanban-column"><h2>'+esc(c.label)+'<span class="count badge">'+list.length+'</span></h2>'+list.map(ticket).join('')+'</section>'}).join('')+'</div>';
  else if(view==='reports') out='<div class="ticket-tools"><h2>Report Intake</h2><span class="grow"></span><button id="newReport">Submit report…</button><button id="pasteReport">Paste report</button></div><p class="muted">Reports stay pending until a reviewer accepts them as a typed ticket or rejects them with a reason.</p><div class="steps">'+(data.ticketBoard.reports.filter(inIssueProject).map(reportCard).join('')||'<p>No reports have been submitted.</p>')+'</div>';
  else if(view==='inbox'){const notices=data.ticketBoard.notifications.filter(n=>!n.read&&n.to.toLowerCase()===data.actor.toLowerCase());out='<div class="ticket-tools"><h2>My Inbox · '+esc(data.actor)+'</h2><span class="grow"></span><button id="readNotices">Mark all read</button></div><div class="steps">'+(notices.map(noticeCard).join('')||'<p>No unread ticket notifications.</p>')+'</div>'}
  else if(view==='members') out='<div class="ticket-tools"><h2>Team Directory</h2><span class="grow"></span>'+(data.assignedTeam?'<button id="syncAssignedTeam" title="Import or update members and job classes from the team assigned in Project & Team Manager">Import assigned team…</button>':'')+'<button id="openProjectManager" title="Create, rename, or assign project teams">Project & Teams…</button><button id="addMember">Add local member…</button></div><p class="muted">'+(data.assignedTeam?'Assigned registry team: <b>'+esc(data.assignedTeam.name)+'</b>. Importing updates matching handles and adds missing members; it does not remove local members or ticket history.':'No registry team is assigned to this character project. Assign one in Project & Team Manager or keep a local-only directory.')+' Roles can be mentioned, such as @QA or @Voice.</p><div class="steps">'+(data.ticketBoard.team.map(memberCard).join('')||'<p>No team members have been added.</p>')+'</div>';
  else if(view==='next') out='<h2>My Next Tasks · '+esc(data.actor)+'</h2><div class="steps">'+(data.next.map(step).join('')||'<p>No unfinished work is currently unassigned or assigned to you. Use Character Workflow or Responsibilities to review the rest.</p>')+'</div>';
  else if(view==='lessons') out='<h2>Reusable Lessons</h2><p class="muted">Lessons preserve proven rules without silently promoting game-specific behavior into universal policy.</p><div class="steps">'+((data.progress.lessons||[]).map(lessonCard).join('')||'<p>No structured lessons have been captured yet.</p>')+'</div>';
  else if(view==='team') out='<h2>Responsibilities</h2><div class="board">'+data.board.map(g=>'<section class="step board-column"><h2>'+esc(g.discipline)+'</h2>'+g.steps.filter(x=>!['passed','intentionally-skipped'].includes(x.progress.status)).map(step).join('')+'</section>').join('')+'</div>';
  else out=data.phases.map(p=>{const sum=data.summaries[p.id];return '<details class="phase" open><summary>'+esc(p.name)+' — '+sum.complete+'/'+sum.total+' complete</summary><div class="progress"><span style="width:'+sum.percent+'%"></span></div><p class="muted" style="padding:0 9px">'+esc(p.summary)+'</p><div class="steps">'+p.steps.map(x=>step({...x,phaseName:p.name})).join('')+'</div></details>'}).join('');
  if(view==='tickets'||view==='reports') out=issueForm()+projectFilterHtml()+out;
  $('content').innerHTML=out;
  document.querySelectorAll('.ticket').forEach(card=>{const id=card.querySelector('[data-ticket-column]')?.dataset.ticketColumn,item=data.ticketBoard.tickets.find(t=>t.id===id);if(item)card.insertAdjacentHTML('beforeend',issueDetails(item));});
  if(view==='reports') document.querySelectorAll('#content>.steps>.step').forEach((card,index)=>card.insertAdjacentHTML('beforeend',issueDetails(data.ticketBoard.reports.filter(inIssueProject)[index])));
  if($('issueProjectFilter'))$('issueProjectFilter').onchange=()=>{issueProjectFilter=$('issueProjectFilter').value;vscode.setState({...vscode.getState(),issueProjectFilter});render();$('issueProjectFilter')?.focus();};
  restoreIssueDraft();
  if($('issueForm')) $('issueForm').onsubmit=event=>{event.preventDefault();const form=event.currentTarget,input=Object.fromEntries(new FormData(form));vscode.postMessage({type:'issueSubmit',input});};
  if($('issueDefinition')) $('issueDefinition').onclick=()=>vscode.postMessage({type:'issueDefinition',itemType:$('issueItemType').value});
  if($('issueItemType')) $('issueItemType').onchange=()=>{const form=$('issueForm'),type=$('issueItemType').value,c=data.reportContext||{};form.elements.itemName.value=type==='Character'?c.itemName:type==='Game Project'||type==='Team Project'?(data.assignedWorkProject?.name||data.ticketBoard.project):type==='Universal tool/viewer'?'IKEMaker':'Unknown';form.elements.contentVersion.value=type==='Character'?c.contentVersion:type==='Universal tool/viewer'?c.toolVersion:'Unknown';};
  if(view==='tickets'){ $('newTicket').onclick=()=>vscode.postMessage({type:'ticketNew'}); $('pasteReport').onclick=()=>vscode.postMessage({type:'reportPaste'}); $('openTickets').onclick=()=>vscode.postMessage({type:'ticketOpen'}); wireTickets(); }
  if(view==='reports'){ $('newReport').onclick=()=>{const form=$('issueForm');form.parentElement.open=true;form.elements.title.focus();}; $('pasteReport').onclick=()=>vscode.postMessage({type:'reportPaste'}); document.querySelectorAll('[data-report-accept]').forEach(b=>b.onclick=()=>vscode.postMessage({type:'reportAccept',id:b.dataset.reportAccept})); document.querySelectorAll('[data-report-reject]').forEach(b=>b.onclick=()=>vscode.postMessage({type:'reportReject',id:b.dataset.reportReject})); }
  if(view==='inbox') $('readNotices').onclick=()=>vscode.postMessage({type:'noticeRead'});
  if(view==='members'){ $('addMember').onclick=()=>vscode.postMessage({type:'memberAdd'}); $('openProjectManager').onclick=()=>vscode.postMessage({type:'openProjectManager'}); if($('syncAssignedTeam')) $('syncAssignedTeam').onclick=()=>vscode.postMessage({type:'syncAssignedTeam'}); document.querySelectorAll('[data-member-edit]').forEach(b=>b.onclick=()=>vscode.postMessage({type:'memberEdit',id:b.dataset.memberEdit})); document.querySelectorAll('[data-member-active]').forEach(b=>b.onclick=()=>vscode.postMessage({type:'memberActive',id:b.dataset.memberActive})); }
  for(const s of document.querySelectorAll('[data-status]'))s.onchange=()=>vscode.postMessage({type:'status',id:s.dataset.status,status:s.value}); for(const b of document.querySelectorAll('[data-assign]'))b.onclick=()=>vscode.postMessage({type:'assign',id:b.dataset.assign}); for(const b of document.querySelectorAll('[data-note]'))b.onclick=()=>vscode.postMessage({type:'note',id:b.dataset.note}); for(const b of document.querySelectorAll('[data-evidence]'))b.onclick=()=>vscode.postMessage({type:'evidence',id:b.dataset.evidence}); for(const b of document.querySelectorAll('[data-lesson]'))b.onclick=()=>vscode.postMessage({type:'lesson',id:b.dataset.lesson}); for(const b of document.querySelectorAll('[data-action]'))b.onclick=()=>vscode.postMessage({type:'action',id:b.dataset.id,action:b.dataset.action});
}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{view=b.dataset.view;vscode.setState({...vscode.getState(),view});render()});$('identity').onclick=()=>vscode.postMessage({type:'identity'});$('saveWorkflow').onclick=()=>vscode.postMessage({type:'saveWorkflow'});$('discardWorkflow').onclick=()=>vscode.postMessage({type:'discardWorkflow'});$('refresh').onclick=()=>vscode.postMessage({type:'refresh'});$('chooseCharacter').onclick=()=>vscode.postMessage({type:'chooseCharacter'});$('chooseProfile').onclick=()=>vscode.postMessage({type:'chooseProfile'});$('profileTools').onclick=()=>vscode.postMessage({type:'profileTools'});$('editProfile').onclick=()=>vscode.postMessage({type:'editProfile'});$('openGuide').onclick=()=>vscode.postMessage({type:'openGuide'});$('openProgress').onclick=()=>vscode.postMessage({type:'openProgress'});window.addEventListener('message',e=>{if(e.data.type==='issueSubmitted'){const form=$('issueForm'),current=form?Object.fromEntries(new FormData(form)):localIssueDrafts[issueDraftIdentity()];if(JSON.stringify(current)===JSON.stringify(e.data.input)){rememberIssueDraft(null);if(form)form.reset();}return;}if(e.data.type==='issueContext'&&$('issueForm')){const form=$('issueForm');for(const key of ['itemType','itemName','contentVersion'])form.elements[key].value=e.data.context[key]||'Unknown';captureIssueDraft();}if(e.data.type==='state'){data=e.data.data;$('saveStatus').textContent=data.hasDraft?'Unsaved changes — kept locally until Save':'No unsaved changes';$('identity').textContent='Identity: '+data.actor;render()}});render();
</script></body></html>`; }

const productionHtml = html;
html = (data) => cohesive(productionHtml(data));

function workflowCharacterChoices(seed) {
  const candidates = [], seen = new Set(), add = (filename) => { const resolved = path.resolve(filename || ''); if (!filename || seen.has(resolved.toLowerCase()) || !isCharacterDef(resolved)) return; seen.add(resolved.toLowerCase()); candidates.push(resolved); };
  const starts = [seed?.fsPath, vscode.window.activeTextEditor?.document.fileName, ...(vscode.workspace.workspaceFolders || []).map((folder) => folder.uri.fsPath)].filter(Boolean);
  for (const start of starts) { const root = gameRoot(start); if (root) for (const filename of characterDefs(root)) add(filename); }
  return candidates.sort((a, b) => path.basename(path.dirname(a)).localeCompare(path.basename(path.dirname(b)), undefined, { numeric: true })).map((filename) => ({ label: path.basename(path.dirname(filename)), description: filename, filename }));
}
async function browseCharacterDef(seed) {
  const root = gameRoot(seed?.fsPath || vscode.window.activeTextEditor?.document.fileName || (vscode.workspace.workspaceFolders || [])[0]?.uri.fsPath || '');
  const picked = await vscode.window.showOpenDialog({ title: 'Choose a character DEF', defaultUri: root ? vscode.Uri.file(path.join(root, 'chars')) : undefined, canSelectMany: false, canSelectFiles: true, canSelectFolders: false, filters: { 'Character definition': ['def'] } });
  if (!picked?.[0]) return '';
  if (!isCharacterDef(picked[0].fsPath)) { vscode.window.showWarningMessage('That DEF does not declare character files. Choose the character’s main DEF, not a stage or screenpack DEF.'); return ''; }
  return picked[0].fsPath;
}
async function chooseCharacter(seed) {
  return chooseCharacterDef(seed, { title: 'Production Workflow — Character' });
}
async function saveProgress(state, changes) { const progress = changes(state.progress); await stageWorkflow(state,state.progressPath,progress,state.progressHash); }
async function saveTickets(state, changes) { const board = changes(state.ticketBoard); await stageWorkflow(state,state.ticketPath,board,state.ticketHash); }
async function createTicketPrompt(state, actor, parentId = '') {
  const parent = parentId ? state.ticketBoard.tickets.find((ticket) => ticket.id === parentId) : null;
  const title = await vscode.window.showInputBox({ title: parent ? `New child ticket under ${parent.title}` : 'New project ticket', prompt: 'Use one clear outcome, such as “Build Ryu” or “Correct fireball clashes”.' }); if (!title?.trim()) return false;
  const type = await vscode.window.showQuickPick(parent ? tickets.TYPES.filter((item) => item !== 'Epic') : tickets.TYPES, { title: 'Ticket type', placeHolder: 'Epic contains child tickets; other tickets contain task checklists.' }); if (!type) return false;
  const scope = await vscode.window.showQuickPick([{ label: state.character.name, description: 'Current character' }, { label: 'Project-wide', description: 'Not tied to one character' }], { title: 'Ticket scope' }); if (!scope) return false;
  const description = await vscode.window.showInputBox({ title: 'Ticket description (optional)', prompt: 'State the desired result or acceptance condition. Add the task checklist from the board.' }); if (description === undefined) return false;
  await saveTickets(state, (board) => tickets.createTicket(board, { ...issueProject(state,parentId), title, type, parentId, character: scope.label === 'Project-wide' ? '' : state.character.name, description: description || '', column: type === 'Discussion' ? 'discussion' : 'backlog' }, actor)); return true;
}
async function submitReportPrompt(state, actor, seed = null) {
  const title = seed?.title || await vscode.window.showInputBox({ title: 'Submit problem report', prompt: 'Short summary of what happened.' }); if (!title?.trim()) return false;
  const body = seed?.body || await vscode.window.showInputBox({ title: 'Problem details', prompt: 'What happened, what was expected, and how can the team reproduce it?' }); if (!body?.trim()) return false;
  const attach = await vscode.window.showQuickPick(['Submit without attachments', 'Add screenshots, logs, or other evidence'], { title: 'Report evidence' }); if (!attach) return false;
  let attachments = []; if (attach.startsWith('Add')) { const picked = await vscode.window.showOpenDialog({ title: 'Attach report evidence', canSelectMany: true, canSelectFiles: true, canSelectFolders: false }); if (!picked) return false; attachments = picked.map((uri) => path.relative(state.character.root, uri.fsPath).replace(/\\/g, '/')); }
  await saveTickets(state, (board) => tickets.submitReport(board, { ...state.reportContext, ...issueProject(state), project: state.assignedWorkProject?.name || state.ticketBoard.project, title, body, reporter: actor, attachments })); return true;
}
async function openPath(filename) { if (!filename || !fs.existsSync(filename)) return vscode.window.showWarningMessage('The related file has not been assigned or does not exist yet.'); const ext = path.extname(filename).toLowerCase(); if (ext === '.sff') return vscode.commands.executeCommand('sff.openViewer', vscode.Uri.file(filename)); if (ext === '.snd') return vscode.commands.executeCommand('snd.openViewer', vscode.Uri.file(filename)); const document = await vscode.workspace.openTextDocument(vscode.Uri.file(filename)); return vscode.window.showTextDocument(document, { preview: false }); }
async function runAction(state, action) {
  const c = state.character;
  if (action === 'open-def') return openPath(c.defPath); if (action === 'open-sff' || action === 'open-sff-palettes') return openPath(c.sff); if (action === 'open-air') return openPath(c.air); if (action === 'open-snd') return openPath(c.snd); if (action === 'open-constants') return openPath(c.constants);
  if (action === 'open-character-folder') return vscode.commands.executeCommand('revealFileInOS', vscode.Uri.file(c.folder));
  if (action === 'open-requirements') return vscode.commands.executeCommand('sff.openRequirementsProfile', c.sff ? vscode.Uri.file(c.sff) : vscode.Uri.file(c.defPath));
  if (action === 'audit-requirements') return vscode.commands.executeCommand('sff.auditCharacterRequirements', c.sff ? vscode.Uri.file(c.sff) : undefined);
  if (action === 'review-unassigned') return vscode.commands.executeCommand('sff.reviewUnassignedSprites', c.sff ? vscode.Uri.file(c.sff) : undefined);
  if (action === 'launch-training') { await vscode.workspace.getConfiguration('ikemenZss', vscode.Uri.file(c.defPath)).update('defaultTrainingCharacter', path.relative(c.root, c.defPath).replace(/\\/g, '/'), vscode.ConfigurationTarget.Workspace); await openPath(c.defPath); return vscode.commands.executeCommand('ikemen.launchTrainingCurrent'); }
  if (action === 'open-code') { const items = c.code.filter(fs.existsSync).map((file) => ({ label: path.relative(c.folder, file), file })); const picked = items.length === 1 ? items[0] : await vscode.window.showQuickPick(items, { placeHolder: 'Choose the state/code file' }); if (picked) return openPath(picked.file); return; }
  if (action === 'open-reports') { const directory = path.join(c.root, 'save', 'logs'); if (!fs.existsSync(directory)) return vscode.window.showWarningMessage('No save/logs directory was found.'); const files = fs.readdirSync(directory).filter((name) => /(?:report|log).*\.(?:txt|log)$/i.test(name)).map((name) => path.join(directory, name)); const picked = await vscode.window.showQuickPick(files.map((file) => ({ label: path.basename(file), file })), { placeHolder: 'Choose a test report or log' }); if (picked) return openPath(picked.file); }
}
async function createOrEditProfile(context, state) {
  let target = state.profilePath;
  if (state.profileIsBundled) { target = path.join(projectProfileDirectory(state.character), `${safeId(state.profile.id)}.project.json`); if (!fs.existsSync(target)) { const raw = { schemaVersion: 1, id: `${state.profile.id}-project`, version: 1, name: `${state.profile.name} — Project`, description: 'Project-owned additions and refinements layered over the bundled workflow.', extends: `bundled:${state.profile.id}`, blocks: [], phases: [] }; writeData(target, raw, 'create-project-workflow-profile'); writeData(settingsPath(state.character), { schemaVersion: 1, defaultProfile: path.relative(path.join(state.character.root, '.ikemen'), target).replace(/\\/g, '/') }, 'select-production-workflow-profile'); } }
  return openPath(target);
}
function settingForProfile(character, filename, bundled = false) { return bundled ? `bundled:${readJson(filename, {}).id}` : path.relative(path.join(character.root, '.ikemen'), filename).replace(/\\/g, '/'); }
async function profileIdentity(title, suggestedName, suggestedId) {
  const name = await vscode.window.showInputBox({ title, value: suggestedName, prompt: 'Human-readable game or project workflow name.' }); if (!name?.trim()) return null;
  const id = await vscode.window.showInputBox({ title: 'Stable workflow profile ID', value: safeId(suggestedId).toLowerCase(), validateInput: (value) => /^[a-z0-9][a-z0-9_.-]*$/i.test(value) ? undefined : 'Use letters, numbers, dots, underscores, or hyphens.' });
  return id?.trim() ? { name: name.trim(), id: id.trim() } : null;
}
async function duplicateProfile(context, state) {
  const identity = await profileIdentity('Duplicate resolved workflow', `${state.profile.name} Copy`, `${state.profile.id}-copy`); if (!identity) return;
  const target = path.join(projectProfileDirectory(state.character), `${safeId(identity.id)}.json`);
  if (fs.existsSync(target)) return vscode.window.showWarningMessage(`A workflow profile already exists at ${target}.`);
  const raw = { ...state.profile, id: identity.id, name: identity.name, version: 1, description: `Independent copy of ${state.profile.name}.`, extends: '', blocks: [], phases: state.profile.phases };
  writeData(target, raw, 'duplicate-workflow-profile'); writeData(settingsPath(state.character), { schemaVersion: 1, defaultProfile: settingForProfile(state.character, target) }, 'select-production-workflow-profile'); await openPath(target);
}
async function inheritProfile(context, state) {
  const identity = await profileIdentity('Create inherited game workflow', `${state.profile.name} Branch`, `${state.profile.id}-branch`); if (!identity) return;
  const target = path.join(projectProfileDirectory(state.character), `${safeId(identity.id)}.json`);
  if (fs.existsSync(target)) return vscode.window.showWarningMessage(`A workflow profile already exists at ${target}.`);
  const parent = state.profileIsBundled ? `bundled:${state.profile.id}` : path.relative(path.dirname(target), state.profilePath).replace(/\\/g, '/');
  writeData(target, { schemaVersion: 1, id: identity.id, version: 1, name: identity.name, description: `Game/project branch inheriting ${state.profile.name}.`, extends: parent, blocks: [], phases: [] }, 'inherit-workflow-profile');
  writeData(settingsPath(state.character), { schemaVersion: 1, defaultProfile: settingForProfile(state.character, target) }, 'select-production-workflow-profile'); await openPath(target);
}
async function importWorkflowBlock(context, state) {
  if (state.profileIsBundled) return vscode.window.showInformationMessage('Create an editable or inherited project profile before importing a workflow block. Bundled profiles remain read-only.');
  const candidates = blockCandidates(context, state.character), picked = await vscode.window.showQuickPick(candidates, { title: 'Import reusable workflow blocks', canPickMany: true, placeHolder: 'Existing step IDs are updated; new phases and steps are added.' }); if (!picked?.length) return;
  const raw = readJson(state.profilePath); if (!raw) throw new Error(`Could not read ${state.profilePath}`);
  raw.blocks = Array.isArray(raw.blocks) ? raw.blocks : [];
  for (const item of picked) { const reference = item.bundled ? `bundled-block:${item.raw.id}` : path.relative(path.dirname(state.profilePath), item.filename).replace(/\\/g, '/'); if (!raw.blocks.includes(reference)) raw.blocks.push(reference); }
  raw.version = (Number(raw.version) || 1) + 1; writeData(state.profilePath, raw, 'import-workflow-block');
}
async function exportPhaseAsBlock(context, state) {
  const picked = await vscode.window.showQuickPick(state.profile.phases.map((phase) => ({ label: phase.name, description: `${phase.steps.length} step(s)`, phase })), { title: 'Export a profile phase as a reusable block' }); if (!picked) return;
  const identity = await profileIdentity('Reusable block name', picked.phase.name.replace(/^\d+\.\s*/, ''), picked.phase.id); if (!identity) return;
  const target = path.join(state.character.root, '.ikemen', 'workflow-blocks', `${safeId(identity.id)}.json`); if (fs.existsSync(target)) return vscode.window.showWarningMessage(`A workflow block already exists at ${target}.`);
  writeData(target, { schemaVersion: 1, id: identity.id, version: 1, name: identity.name, category: 'Project', description: `Reusable phase exported from ${state.profile.name}. Review game-specific steps before importing elsewhere.`, phases: [picked.phase] }, 'export-workflow-block'); await openPath(target);
}
async function profileTools(context, state) {
  const picked = await vscode.window.showQuickPick([
    { label: 'Duplicate resolved profile', description: 'Create a fully independent copy of the current resolved workflow.', action: 'duplicate' },
    { label: 'Create inherited game/project profile', description: 'Branch from this profile and continue receiving reviewed parent updates.', action: 'inherit' },
    { label: 'Import reusable workflow blocks', description: 'Insert selected versioned portions into an editable profile.', action: 'import' },
    { label: 'Export one phase as a reusable block', description: 'Create a project block that another profile can import.', action: 'export' }
  ], { title: 'Production Workflow Profile Tools' });
  if (!picked) return;
  if (picked.action === 'duplicate') return duplicateProfile(context, state);
  if (picked.action === 'inherit') return inheritProfile(context, state);
  if (picked.action === 'import') return importWorkflowBlock(context, state);
  if (picked.action === 'export') return exportPhaseAsBlock(context, state);
}
async function chooseProfile(context, state) {
  const picked = await vscode.window.showQuickPick(profileCandidates(context, state.character), { title: 'Production Workflow Profile', placeHolder: 'Choose a bundled or project profile' }); if (!picked) return;
  const setting = picked.bundled ? `bundled:${readJson(picked.filename, {}).id || 'jnp-character-production'}` : path.relative(path.join(state.character.root, '.ikemen'), picked.filename).replace(/\\/g, '/'); writeData(settingsPath(state.character), { schemaVersion: 1, defaultProfile: setting }, 'select-production-workflow-profile');
}
async function refresh(context, session) { session.state = loadState(context, session.state.character); session.panel.title = `${session.state.character.name} — Production Workflow`; session.panel.webview.postMessage({ type: 'state', data: session.state }); }
async function handle(context, session, message) {
  if (await handleLaunchMessage(message, session?.state?.character?.defPath, 'workflow', session?.panel)) return;
  let state = session.state, actor = actorFor(state.character);
  if(message.type==='issueDraft'){if(path.resolve(String(message.defPath||'')).toLowerCase()!==path.resolve(state.character.defPath).toLowerCase())return;const values=message.values&&typeof message.values==='object'?Object.fromEntries(Object.entries(message.values).filter(([key,value])=>typeof value==='string'&&key.length<80).map(([key,value])=>[key,value.slice(0,100000)])):undefined;await context.workspaceState.update(issueDraftKey(state.character),values);return;}
  if(message.type==='saveWorkflow'){await drafts.save(workflowFiles(state));await refresh(context,session);return;}
  if(message.type==='discardWorkflow'){if(!state.hasDraft)return;const answer=await vscode.window.showWarningMessage('Discard unsaved Workflow changes for this character and project board?',{modal:true},'Discard Changes');if(answer==='Discard Changes'){await drafts.discard(workflowFiles(state));await refresh(context,session);}return;}
  if (message.type === 'issueDefinition') {
    const picked = await vscode.window.showOpenDialog({ title: 'Read item name and version from definition', canSelectMany: false, filters: { 'IKEMEN definition': ['def'] } });
    if (!picked?.[0]) return;
    const filename = picked[0].fsPath, itemType = feedback.ITEM_TYPES.includes(message.itemType) ? message.itemType : 'Other';
    try { session.panel.webview.postMessage({ type: 'issueContext', context: feedback.definitionContext(fs.readFileSync(filename, 'utf8'), filename, itemType) }); }
    catch (error) { vscode.window.showWarningMessage('Could not read this definition. Enter the item details manually.'); }
    return;
  }
  if (message.type === 'issueSubmit') {
    const input = message.input || {}, title = String(input.title || '').trim(), body = String(input.body || '').trim();
    if (!title || !body) { vscode.window.showWarningMessage('Add a title and what happened before saving the issue.'); return; }
    const details = { ...issueProject(state), ...feedback.reportContext(state, readJson(path.join(context.extensionPath, 'package.json'), {}).version || 'Unknown'), useCase: input.useCase, itemType: feedback.ITEM_TYPES.includes(input.itemType) ? input.itemType : 'Other', itemName: String(input.itemName || 'Unknown'), contentVersion: String(input.contentVersion || 'Unknown'), profile: String(input.profile || 'Unknown'), screen: String(input.screen || 'Unknown'), title, project: state.assignedWorkProject?.name || state.ticketBoard.project || path.basename(state.character.root), severity: input.severity, build: input.build, steps: input.steps, expected: input.expected, actual: input.actual, character: input.itemType === 'Character' ? String(input.itemName || state.character.name) : '', attachments: String(input.attachments || '').split(/\r?\n/).map(value => value.trim()).filter(Boolean) };
    await saveTickets(state, board => input.destination === 'report' ? tickets.submitReport(board, { ...details, body, reporter: actor }) : tickets.createTicket(board, { ...details, description: body, type: 'Bug', column: 'backlog' }, actor));
    await drafts.save([state.ticketPath]);
    await context.workspaceState?.update(issueDraftKey(state.character),undefined);
    session.panel.webview.postMessage({type:'issueSubmitted',input});
    await refresh(context, session);
    vscode.window.showInformationMessage(input.destination === 'report' ? 'Feedback saved to this project’s Report Intake.' : 'Issue saved to this project’s Backlog.');
    return;
  }
  if (message.type === 'identity') { const name = await vscode.window.showInputBox({ title: 'Workflow team identity', value: actor === 'Team member' ? '' : actor, prompt: 'Use the name teammates should see, such as JustNoPoint or JNP. Do not use a private real name unless you want it stored in project history.' }); if (!name?.trim()) return; await vscode.workspace.getConfiguration('ikemenZss', vscode.Uri.file(state.character.defPath)).update('productionWorkflow.actor', name.trim(), vscode.ConfigurationTarget.Workspace); }
  else if (message.type === 'ticketNew') { if (!await createTicketPrompt(state, actor)) return; }
  else if (message.type === 'ticketChild') { if (!await createTicketPrompt(state, actor, message.id)) return; }
  else if (message.type === 'reportNew') { if (!await submitReportPrompt(state, actor)) return; }
  else if (message.type === 'reportPaste') { const text = await vscode.env.clipboard.readText(); let input; try { input = tickets.ticketFromFeedback(text); } catch (error) { vscode.window.showWarningMessage(error.message); return; } if (!await submitReportPrompt(state, actor, { title: input.title, body: input.description })) return; }
  else if (message.type === 'reportAccept') { const type = await vscode.window.showQuickPick(tickets.TYPES.filter((item) => item !== 'Epic'), { title: 'Accept report as ticket', placeHolder: 'Choose the reviewed ticket type' }); if (!type) return; const reason = await vscode.window.showInputBox({ title: 'Acceptance note (optional)', prompt: 'Record any triage decision or scope clarification.' }); if (reason === undefined) return; await saveTickets(state, (board) => tickets.reviewReport(board, message.id, 'accepted', { type, reason }, actor)); }
  else if (message.type === 'reportReject') { const reason = await vscode.window.showInputBox({ title: 'Reject report', prompt: 'Record why this report is rejected, duplicated, invalid, or out of scope.' }); if (!reason?.trim()) return; await saveTickets(state, (board) => tickets.reviewReport(board, message.id, 'rejected', { reason }, actor)); }
  else if (message.type === 'memberAdd') { const name = await vscode.window.showInputBox({ title: 'Add team member', prompt: 'Public team display name.' }); if (!name?.trim()) return; const handle = await vscode.window.showInputBox({ title: 'Mention handle', value: name.replace(/\s+/g, ''), prompt: 'Used as @Name in ticket comments.' }); if (!handle?.trim()) return; const roles = await vscode.window.showQuickPick(state.ticketBoard.roles.map((role) => ({ label: role })), { title: 'Team roles', canPickMany: true, placeHolder: 'Choose one or more lightweight responsibilities' }); if (!roles) return; await saveTickets(state, (board) => tickets.addMember(board, { name, handle, roles: roles.map((item) => item.label) })); }
  else if (message.type === 'memberEdit') { const member = state.ticketBoard.team.find((item) => item.id === message.id); if (!member) return; const roles = await vscode.window.showQuickPick(state.ticketBoard.roles.map((role) => ({ label: role, picked: member.roles.includes(role) })), { title: `Roles for ${member.name}`, canPickMany: true }); if (!roles) return; await saveTickets(state, (board) => tickets.updateMember(board, member.id, { roles: roles.map((item) => item.label) })); }
  else if (message.type === 'memberActive') { const member = state.ticketBoard.team.find((item) => item.id === message.id); if (!member) return; await saveTickets(state, (board) => tickets.updateMember(board, member.id, { active: !member.active })); }
  else if (message.type === 'openProjectManager') { await vscode.commands.executeCommand('ikemen.projectManager.open', vscode.Uri.file(state.character.root)); return; }
  else if (message.type === 'syncAssignedTeam') { if (!state.assignedTeam) return vscode.window.showInformationMessage('Assign this work project to a team in Project & Team Manager first.'); await saveTickets(state, (board) => tickets.syncDirectory(board, state.assignedTeam)); }
  else if (message.type === 'noticeRead') await saveTickets(state, (board) => tickets.markNotificationsRead(board, actor));
  else if (message.type === 'ticketColumn') await saveTickets(state, (board) => tickets.updateTicket(board, message.id, { column: message.column }));
  else if (message.type === 'ticketWatch') await saveTickets(state, (board) => tickets.toggleWatch(board, message.id, actor));
  else if (message.type === 'ticketAssign') { const choices = [{ label: 'Unassigned', name: '' }, ...state.ticketBoard.team.filter((member) => member.active).map((member) => ({ label: member.name, description: member.roles.join(', '), name: member.name }))], assigned = await vscode.window.showQuickPick(choices, { title: 'Assign ticket', placeHolder: 'Choose an active team member' }); if (!assigned) return; await saveTickets(state, (board) => tickets.updateTicket(board, message.id, { assignedTo: assigned.name })); }
  else if (message.type === 'ticketAddTask') { const title = await vscode.window.showInputBox({ title: 'Add task to ticket', prompt: 'Enter one concrete, checkable task.' }); if (!title?.trim()) return; const choices = [{ label: 'Ticket owner / unassigned', name: '' }, ...state.ticketBoard.team.filter((member) => member.active).map((member) => ({ label: member.name, description: member.roles.join(', '), name: member.name }))], assigned = await vscode.window.showQuickPick(choices, { title: 'Assign task (optional)' }); if (!assigned) return; await saveTickets(state, (board) => tickets.addSubtask(board, message.id, title, assigned.name)); }
  else if (message.type === 'ticketTask') await saveTickets(state, (board) => tickets.updateSubtask(board, message.id, message.taskId, { done: message.done }));
  else if (message.type === 'ticketComment') { const text = await vscode.window.showInputBox({ title: 'Ticket comment', prompt: 'Record discussion, decisions, blockers, or review findings.' }); if (!text?.trim()) return; await saveTickets(state, (board) => tickets.addComment(board, message.id, text, actor)); }
  else if (message.type === 'ticketArchive') { const ticket = state.ticketBoard.tickets.find((item) => item.id === message.id), answer = await vscode.window.showWarningMessage(`Archive “${ticket?.title || message.id}”?`, { modal: true }, 'Archive'); if (answer !== 'Archive') return; await saveTickets(state, (board) => tickets.updateTicket(board, message.id, { archived: true })); }
  else if (message.type === 'ticketOpen') { if(drafts.has(state.ticketPath)||!fs.existsSync(state.ticketPath))await previewData(state.ticketPath,state.ticketBoard);else await openPath(state.ticketPath); return; }
  else if (message.type === 'status') {
    if (message.status === 'passed') {
      const eligibility = workflow.passEligibility(state.profile, state.progress, message.id);
      if (!eligibility.allowed) { vscode.window.showWarningMessage(`This step cannot pass yet: ${eligibility.reasons.join(' ')}`); return; }
    }
    await saveProgress(state, (progress) => workflow.setItem(progress, message.id, { status: message.status }, actor));
  }
  else if (message.type === 'note') { const current = state.progress.items[message.id]?.note || '', note = await vscode.window.showInputBox({ title: 'Workflow note', value: current, prompt: 'Record a blocker, exception, handoff, or review note.' }); if (note !== undefined) await saveProgress(state, (progress) => workflow.setItem(progress, message.id, { note }, actor)); else return; }
  else if (message.type === 'assign') { const current = state.progress.items[message.id]?.assignedTo || '', assignedTo = await vscode.window.showInputBox({ title: 'Assign workflow step', value: current, prompt: `Enter a team member name. Leave empty to return it to the unassigned queue. Current personal actor: ${actor}` }); if (assignedTo !== undefined) await saveProgress(state, (progress) => workflow.setItem(progress, message.id, { assignedTo: assignedTo.trim() }, actor)); else return; }
  else if (message.type === 'evidence') { const kind = await vscode.window.showQuickPick(['Reference a file', 'Add a text reference'], { placeHolder: 'What evidence should be attached?' }); if (!kind) return; let value = ''; if (kind === 'Reference a file') { const picked = await vscode.window.showOpenDialog({ title: 'Choose evidence', canSelectMany: false }); value = picked?.[0] ? path.relative(state.character.root, picked[0].fsPath).replace(/\\/g, '/') : ''; } else value = await vscode.window.showInputBox({ title: 'Evidence reference', prompt: 'Example: State 200 reviewed with JNP; logger report 2026-09-02.' }) || ''; if (value) await saveProgress(state, (progress) => workflow.addEvidence(progress, message.id, { label: kind === 'Reference a file' ? 'File' : 'Note', value }, actor)); else return; }
  else if (message.type === 'lesson') {
    const rule = await vscode.window.showInputBox({ title: 'Reusable lesson — proven rule', prompt: 'What behavior or process is now proven?' }); if (!rule?.trim()) return;
    const gameSpecificException = await vscode.window.showInputBox({ title: 'Game-specific exception', prompt: 'What differs by game? Leave blank when none is known.' }); if (gameSpecificException === undefined) return;
    const testProcedure = await vscode.window.showInputBox({ title: 'Test procedure', prompt: 'How can another coder reproduce and verify this result?' }); if (testProcedure === undefined) return;
    const evidence = await vscode.window.showInputBox({ title: 'Evidence', prompt: 'Report, screenshot, file, commit, or reviewed observation.' }); if (evidence === undefined) return;
    const knownLimitation = await vscode.window.showInputBox({ title: 'Known limitation', prompt: 'Engine, scope, source, or coverage limit. Leave blank if none.' }); if (knownLimitation === undefined) return;
    const ownerSignoff = await vscode.window.showInputBox({ title: 'Owner sign-off', prompt: 'Use JustNoPoint or JNP only after the owner actually approves it. Leave blank while awaiting review.' }); if (ownerSignoff === undefined) return;
    await saveProgress(state, (progress) => { workflow.addLesson(progress, { rule, gameSpecificException, testProcedure, evidence, knownLimitation, ownerSignoff }, actor); workflow.addEvidence(progress, message.id, { label: 'Structured lesson', value: rule }, actor); return progress; });
  }
  else if (message.type === 'action') { await runAction(state, message.action); return; }
  else if (message.type === 'openProgress') { if(drafts.has(state.progressPath)||!fs.existsSync(state.progressPath))await previewData(state.progressPath,state.progress);else await openPath(state.progressPath); return; }
  else if (message.type === 'openGuide') { await openPath(workflowGuide(context)); return; }
  else if (message.type === 'editProfile') { await createOrEditProfile(context, state); return; }
  else if (message.type === 'profileTools') { await profileTools(context, state); await refresh(context, session); return; }
  else if (message.type === 'chooseProfile') { await chooseProfile(context, state); }
  else if (message.type === 'refresh') { await refresh(context, session); return; }
  else if (message.type === 'chooseCharacter') { const def = await chooseCharacter(); if (!def||session.disposed) return;return openProductionWorkflow(context,vscode.Uri.file(def)); }
  await refresh(context, session);
}
async function openProductionWorkflow(context, uri,options={}) {
  const defPath = await chooseCharacter(uri); if (!defPath) return;
  const key=sessionKey(defPath),existing=workflowSessions.get(key);if(existing&&!existing.disposed){activeSession=existing;revealInViewerGroup(existing.panel,false,vscode.ViewColumn.Active);return existing.panel;}
  let state; try { state = loadState(context, characterContext(defPath)); } catch (error) { return vscode.window.showErrorMessage(`Could not open Production Workflow: ${error.message}`); }

  const panel = trackViewerPanel(vscode.window.createWebviewPanel('ikemenProductionWorkflow', `${state.character.name} — Production Workflow`, preferredViewerColumn(vscode.ViewColumn.Active), { enableScripts: true, retainContextWhenHidden: true })), session = { panel, state }; registerCharacterToolPanel(panel, defPath, state.character.name, [state.progressPath]); activeSession = session; panel.webview.html = require('./webview_policy').protect(html(state), panel.webview.cspSource); workflowSessions.set(key,session);
  require('./viewer_close').support(panel,{isBusy:()=>!!session.pendingCount});
  panel.webview.onDidReceiveMessage(message=>{
    if(session.disposed)return;
    session.pendingCount=(session.pendingCount||0)+1;
    if(message.type==='issueDraft'){session.issuePending=(session.issuePending||Promise.resolve()).catch(()=>{}).then(()=>handle(context,session,message)).catch(error=>vscode.window.showErrorMessage('The issue draft could not be stored: '+error.message)).finally(()=>{session.pendingCount--;});return session.issuePending;}
    actionQueue=actionQueue.catch(()=>{}).then(async()=>{
      if(session.disposed)return;
      // Separate panels can share a game board. Re-read staged work before each action.
      session.state=loadState(context,session.state.character);
      await handle(context,session,message);
    }).catch(async error=>{vscode.window.showErrorMessage(`Production Workflow could not complete that action: ${error.message}`);if(!session.disposed)await refresh(context,session);}).finally(()=>{session.pendingCount--;});
    session.pending=actionQueue;return actionQueue;
  });
  panel.onDidDispose(() => {session.disposed=true;if(workflowSessions.get(key)===session)workflowSessions.delete(key);if(activeSession===session)activeSession=null;});return panel;
}
function registerProductionWorkflow(context) { drafts=new WorkflowDrafts(context.workspaceState); context.subscriptions.push(vscode.commands.registerCommand('ikemen.productionWorkflow.open', (uri,options) => openProductionWorkflow(context, uri,options)), vscode.commands.registerCommand('ikemen.productionWorkflow.editProfile', async (uri) => { const defPath = await chooseCharacter(uri); if (!defPath) return; return createOrEditProfile(context, loadState(context, characterContext(defPath))); }), vscode.commands.registerCommand('ikemen.productionWorkflow.openGuide', () => openPath(workflowGuide(context)))); }

module.exports = { handle, registerProductionWorkflow, openProductionWorkflow, characterContext, progressPath, activeProfilePath, loadProfileFile, detections, loadState, html, workflowCharacterChoices, browseCharacterDef, chooseCharacter };
