'use strict';

const fs = require('fs');
const path = require('path');
const vscode = require('vscode');
const { launchControlsHtml, launchControlsClientScript, handleLaunchMessage } = require('./launch_controls');
const { parseSelectDef, insertionLine } = require('./select_def_model');
const { storyArcs, linearStoryLua, dialogueController } = require('./story_dialogue_model');
const { chooseFileOrFolder } = require('./open_target_picker');
const { preferredViewerColumn, trackViewerPanel, revealInViewerGroup } = require('./viewer_group');
const { FormDrafts } = require('./form_drafts');

const sessions = new Map();
let formDrafts = new FormDrafts();
const sessionKey = filename => path.resolve(filename).toLowerCase();
const draftKey = filename => `story-dialogue:${sessionKey(filename)}`;
const ownsSession = owner => Boolean(owner && sessions.get(sessionKey(owner.file)) === owner);
function cohesive(page) { return page.replace('</header>', `${launchControlsHtml('story_dialogue')}</header>`).replace('</script></body>', `${launchControlsClientScript()}</script></body>`); }
const safe = (value) => JSON.stringify(value).replace(/</g, '\\u003c').replace(/>/g, '\\u003e').replace(/&/g, '\\u0026');
const esc = (value) => String(value || '').replace(/[&<>"']/g, (c) => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;', "'":'&#39;' }[c]));

function gameRootFromSelect(filename) { return path.basename(path.dirname(filename)).toLowerCase() === 'data' ? path.dirname(path.dirname(filename)) : path.dirname(filename); }
async function resolveSelect(uri) {
  if (uri?.fsPath && path.basename(uri.fsPath).toLowerCase() === 'select.def') return uri.fsPath;
  const active = vscode.window.activeTextEditor?.document.fileName;
  if (active && path.basename(active).toLowerCase() === 'select.def') return active;
  for (const folder of vscode.workspace.workspaceFolders || []) {
    for (const candidate of [path.join(folder.uri.fsPath, 'data', 'select.def'), path.join(folder.uri.fsPath, 'select.def')]) if (fs.existsSync(candidate)) return candidate;
  }
  return await chooseFileOrFolder({ title: 'Choose select.def for Story Mode', filters: { 'IKEMEN select.def': ['def'] }, extensions: ['def'], predicate: (candidate) => path.basename(candidate).toLowerCase() === 'select.def', maxDepth: 4, invalidMessage: 'Choose a select.def roster definition.', emptyMessage: 'No select.def was found in that folder.' }) || null;
}

async function load(filename) {
  const document = await vscode.workspace.openTextDocument(vscode.Uri.file(filename)), select = parseSelectDef(document.getText());
  return { document, model: { file: filename, root: gameRootFromSelect(filename), arcs: storyArcs(select), portraitGroup: vscode.workspace.getConfiguration('ikemenZss', document.uri).get('story.portraitGroup', 9100), maxLines: 20, formDraft: formDrafts.read(draftKey(filename)) } };
}

function html(model, view = 'player') {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
:root{color-scheme:light dark}*{box-sizing:border-box}body{margin:0;font:13px var(--vscode-font-family);color:var(--vscode-foreground);background:var(--vscode-editor-background)}header,.tabs,.toolbar{display:flex;gap:7px;align-items:center;flex-wrap:wrap}header{padding:9px 12px;border-bottom:1px solid var(--vscode-panel-border)}.tabs{padding:8px 12px;border-bottom:1px solid var(--vscode-panel-border)}main{padding:14px;max-width:1500px}.view{display:none}.view.active{display:block}button,input,select,textarea{font:inherit;color:inherit;background:var(--vscode-input-background);border:1px solid var(--vscode-input-border);padding:6px 8px}button{cursor:pointer;background:var(--vscode-button-secondaryBackground)}button.primary,.tabs button.active{background:var(--vscode-button-background);color:var(--vscode-button-foreground)}.grow{flex:1}.badge{padding:2px 7px;border-radius:10px;background:var(--vscode-badge-background);color:var(--vscode-badge-foreground)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:10px}.card{padding:11px;border:1px solid var(--vscode-panel-border);border-radius:5px;background:var(--vscode-sideBar-background)}.card h3{margin:0 0 7px}.muted{color:var(--vscode-descriptionForeground)}.fields{display:grid;grid-template-columns:130px minmax(200px,1fr);gap:8px;align-items:center}.line{display:grid;grid-template-columns:70px 90px 95px minmax(240px,1fr) 75px 30px;gap:6px;margin:6px 0}.line input,.line select{min-width:0;width:100%}.callout{border-left:4px solid var(--vscode-focusBorder);padding:5px 11px;margin:10px 0}.warning{border-left-color:var(--vscode-charts-yellow)}code{font-family:var(--vscode-editor-font-family)}
</style></head><body><header><b>STORY & DIALOGUE BUILDER</b><span class="badge">IKEMEN 1.0 NATIVE</span><span class="muted">${esc(model.file)}</span><span class="grow"></span><button id="selectCode">select.def</button><button id="reload">Reload</button></header>
<nav class="tabs"><button data-view="player">Player Route</button><button data-view="dialogue">Dialogue</button><button data-view="creator">Creator</button></nav><main>
<section id="player" class="view"><h1>Story routes</h1><p class="muted">A route is an offline Lua progression script registered natively in select.def. The simple builder creates a readable linear route; it does not hide the generated files.</p><div class="toolbar"><button class="primary" id="createArc">+ Create story route</button><button id="menuModes">Ensure Story Mode menu entry</button></div><div class="grid" id="arcs"></div></section>
<section id="dialogue" class="view"><h1>Encounter dialogue</h1><div class="callout"><b>Native match dialogue</b><p>These lines generate the IKEMEN Dialogue controller for a character/common ZSS file. Story Mode launches the encounter; this controller supplies the conversation.</p><p id="draftStatus" class="muted"></p></div><div class="fields"><label>Label</label><input id="label" value="Rival encounter"><label>Enemy internal name</label><input id="enemy" placeholder="Ken"><label>When</label><select id="phase"><option value="pre">Before round 1</option><option value="post">After winning</option></select><label>Portrait group</label><input id="group" type="number" value="${model.portraitGroup}"><label>Hide lifebars</label><input id="hidebars" type="checkbox" checked></div><h2>Dialogue beats <span class="muted">(maximum ${model.maxLines})</span></h2><div class="line muted"><span>Speaker</span><span>Reaction</span><span>Wait ticks</span><span>Text</span><span>Sound G,I</span><span></span></div><div id="lines"></div><div class="toolbar"><button id="addLine">+ Add beat</button><button class="primary" id="copyDialogue">Copy native controller</button><button id="insertDialogue">Insert into open ZSS/CNS</button><button id="discardDialogue">Discard recovered draft</button><button id="portraitImport">Check/import portrait PNGs…</button></div><details><summary>Portrait convention and compatibility</summary><p>The suggested group is <code>${model.portraitGroup}</code>, indices 0–19, where 0 is neutral and the remaining reactions may be named per character. This is project-configurable, not an engine requirement. Each character owns its own portrait sprites, so the same group/index can safely be reused. Indexed/shared-palette and 32-bit portraits are both valid. Binary SFF changes still pass through the reviewed SprMaker2 source manifest.</p></details></section>
<section id="creator" class="view"><h1>Advanced native story authoring</h1><div class="toolbar"><button class="primary" id="newStoryboard">+ Create opening, ending, or storyboard</button><button id="openStoryboard">Open storyboard visual editor</button><button id="newOpening">New character opening</button><button id="newEnding">New character ending</button></div><div class="grid"><article class="card"><h3>Branching and hidden fights</h3><p>Use Lua conditions, match results, maps, and explicit opponents to build rivals, secret bosses, or alternate paths.</p></article><article class="card"><h3>Mixed battle formats</h3><p>Each <code>launchFight{}</code> may select single, simul, tag, or turns, team size, palettes, AI, rounds, time, stage, music, and presentation screens.</p></article><article class="card"><h3>Storyboards</h3><p><code>launchStoryboard(path)</code> can run before, between, or after fights. The visual storyboard editor creates and organizes scenes for openings, endings, credits, logos, loading, game-over, and interstitial sequences.</p></article><article class="card"><h3>Resume safety</h3><p>Use <code>matchNo()</code>, stop when <code>launchFight</code> returns false, and call <code>setMatchNo(-1)</code> only after the route is cleared.</p></article></div><div class="callout warning"><b>Online boundary</b><p>Story Mode Lua is intended for offline progression. Rollback/netplay match systems must not depend on it. Native Dialogue is character state logic, but online story authoring is outside this tool’s safe player workflow.</p></div><div class="toolbar"><button id="luaDocs">Open offline Story Mode docs</button><button id="dialogueDocs">Open offline Dialogue docs</button><button id="selectCode2">Open select.def</button></div></section>
</main><script>
const vscode=acquireVsCodeApi(),data=${safe(model)},$=id=>document.getElementById(id);let view=vscode.getState()?.view||'${view}',count=0,draftDirty=!!data.formDraft,draftRevision=0,pendingDrafts=new Set();
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setView(next){view=next;document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===view));document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===view));vscode.setState({view,file:data.file})}
function renderArcs(){$('arcs').innerHTML=data.arcs.map(a=>'<article class="card"><h3>'+esc(a.displayname)+'</h3><span class="badge">'+esc(a.name)+'</span><p><code>'+esc(a.path||'No path assigned')+'</code></p><p class="muted">Unlock: '+esc(a.unlock)+'</p><button data-open="'+esc(a.path)+'">Open route Lua</button></article>').join('')||'<p class="muted">No Story Mode routes are registered yet.</p>';document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>vscode.postMessage({type:'openArc',path:b.dataset.open}))}
function addLine(side='p1',value,stage=true){if(count>=data.maxLines)return;count++;const row=document.createElement('div');row.className='line';row.innerHTML='<select data-side><option value="p1">P1</option><option value="p2">P2</option></select><input data-face type="number" min="0" max="19" value="0" title="Portrait reaction index"><input data-wait type="number" min="0" value="0" title="Pause after this text, in game ticks"><input data-text placeholder="Dialogue text"><input data-sound placeholder="optional"><button data-remove title="Remove beat">×</button>';row.querySelector('[data-side]').value=value?.side||side;row.querySelector('[data-face]').value=value?.portrait??0;row.querySelector('[data-wait]').value=value?.wait??0;row.querySelector('[data-text]').value=value?.text||'';row.querySelector('[data-sound]').value=value?.soundGroup!==undefined&&value?.soundGroup!==''?value.soundGroup+','+(value.soundIndex??''):'';row.querySelector('[data-remove]').onclick=()=>{row.remove();count--;stageDraft()};$('lines').appendChild(row);if(stage)stageDraft()}
function dialogue(){return {label:$('label').value,enemy:$('enemy').value,phase:$('phase').value,group:Number($('group').value),hidebars:$('hidebars').checked,lines:[...document.querySelectorAll('#lines .line')].map(r=>{const snd=r.querySelector('[data-sound]').value.split(',');return {side:r.querySelector('[data-side]').value,portrait:r.querySelector('[data-face]').value,wait:r.querySelector('[data-wait]').value,text:r.querySelector('[data-text]').value,soundGroup:snd.length>1?snd[0]:'',soundIndex:snd.length>1?snd[1]:''}})}}
function draftStatus(text){$('draftStatus').textContent=text||(draftDirty?'Draft recovery is active for this roster.':'No recovered dialogue draft.')}
function stageDraft(){draftDirty=true;const revision=++draftRevision;pendingDrafts.add(revision);vscode.postMessage({type:'dialogueDraft',revision,draft:dialogue()});draftStatus('Keeping this dialogue draft…')}
function restoreDraft(){const draft=data.formDraft;if(!draft){addLine('p1',undefined,false);addLine('p2',undefined,false);draftStatus();return}$('label').value=draft.label??'Rival encounter';$('enemy').value=draft.enemy??'';$('phase').value=draft.phase==='post'?'post':'pre';$('group').value=Number.isFinite(Number(draft.group))?Number(draft.group):data.portraitGroup;$('hidebars').checked=draft.hidebars!==false;for(const line of draft.lines||[])addLine(line.side||'p1',line,false);if(!count)addLine('p1',undefined,false);draftStatus('Recovered an unsaved dialogue draft for this roster.')}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('createArc').onclick=()=>vscode.postMessage({type:'createArc'});$('menuModes').onclick=()=>vscode.postMessage({type:'menuModes'});$('reload').onclick=()=>vscode.postMessage({type:'reload'});$('selectCode').onclick=$('selectCode2').onclick=()=>vscode.postMessage({type:'selectCode'});$('addLine').onclick=()=>addLine(count%2?'p2':'p1');$('copyDialogue').onclick=()=>vscode.postMessage({type:'dialogue',...dialogue(),action:'copy'});$('insertDialogue').onclick=()=>vscode.postMessage({type:'dialogue',...dialogue(),action:'insert'});$('discardDialogue').onclick=()=>vscode.postMessage({type:'discardDialogueDraft'});$('portraitImport').onclick=()=>vscode.postMessage({type:'portraitImport'});$('luaDocs').onclick=()=>vscode.postMessage({type:'docs',topic:'lua'});$('dialogueDocs').onclick=()=>vscode.postMessage({type:'docs',topic:'dialogue'});$('newStoryboard').onclick=()=>vscode.postMessage({type:'storyboard',action:'create'});$('openStoryboard').onclick=()=>vscode.postMessage({type:'storyboard',action:'open'});$('newOpening').onclick=()=>vscode.postMessage({type:'storyboard',action:'opening'});$('newEnding').onclick=()=>vscode.postMessage({type:'storyboard',action:'ending'});$('dialogue').addEventListener('input',event=>{if(event.target.matches('input,select'))stageDraft()});$('dialogue').addEventListener('change',event=>{if(event.target.matches('input,select'))stageDraft()});addEventListener('message',event=>{const message=event.data;if(message.type==='dialogueDraftStored'){pendingDrafts.delete(message.revision);draftStatus()}else if(message.type==='dialogueDraftDiscarded'){pendingDrafts.clear();draftDirty=false;data.formDraft=null;draftStatus('Recovered draft discarded. Current fields remain visible until reload.')}else if(message.type==='storyDialogueSetView')setView(message.view)});globalThis.ikemenNavigationSelection=()=>({view});globalThis.ikemenCanRestoreNavigation=reference=>!!reference&&['player','dialogue','creator'].includes(reference.view);globalThis.ikemenRestoreNavigation=reference=>setView(reference.view);globalThis.ikemenIsBusy=()=>pendingDrafts.size>0;globalThis.ikemenHasUnappliedForms=()=>draftDirty;globalThis.ikemenCanKeepDraft=()=>draftDirty&&!pendingDrafts.size;renderArcs();restoreDraft();setView(view);
</script></body></html>`;
}

async function reveal(document, line = 0) { const editor = await vscode.window.showTextDocument(document, { preview: false }); const at = Math.max(0, Math.min(document.lineCount - 1, line)); editor.selection = new vscode.Selection(at, 0, at, 0); editor.revealRange(new vscode.Range(at, 0, at, 0), vscode.TextEditorRevealType.InCenter); }
async function replaceDocument(document, next) { const last = document.lineAt(document.lineCount - 1); const edit = new vscode.WorkspaceEdit(); edit.replace(document.uri, new vscode.Range(0, 0, last.lineNumber, last.text.length), next); return vscode.workspace.applyEdit(edit); }

async function appendStoryRegistration(owner, name, displayname, relativePath) {
  if (!ownsSession(owner)) return false;
  const parsed = parseSelectDef(owner.document.getText()), section = parsed.sections.find((x) => x.name === 'storymode');
  const eol = owner.document.getText().includes('\r\n') ? '\r\n' : '\n', block = [`name = ${name}`, `displayname = ${displayname}`, `path = ${relativePath.replace(/\\/g, '/')}`, 'unlock = true', ''].join(eol);
  if (!section) return replaceDocument(owner.document, `${owner.document.getText()}${eol}[StoryMode]${eol}${block}`);
  const lines = [...parsed.lines]; lines.splice(insertionLine(parsed, 'storymode'), 0, ...block.replace(/\r/g, '').split('\n')); return replaceDocument(owner.document, lines.join(eol));
}

async function createArc(owner) {
  const name = await vscode.window.showInputBox({ title: 'Story route ID', prompt: 'Unique internal name returned by GameMode.', validateInput: (v) => /^[A-Za-z][A-Za-z0-9_.-]*$/.test(v) ? null : 'Begin with a letter; use letters, numbers, dot, dash, or underscore.' }); if (!name) return;
  if (!ownsSession(owner)) return;
  const displayname = await vscode.window.showInputBox({ title: 'Player-facing story name', value: name.replace(/[_-]+/g, ' ') }); if (displayname === undefined) return;
  if (!ownsSession(owner)) return;
  const p1char = await vscode.window.showInputBox({ title: 'Player character', prompt: 'Character path/name used by launchFight, for example Ryu/Ryu.def.', placeHolder: 'Ryu/Ryu.def' }); if (p1char === undefined) return;
  if (!ownsSession(owner)) return;
  const root = gameRootFromSelect(owner.file), defaultUri = vscode.Uri.file(path.join(root, 'data', 'story', `${name}.lua`));
  const save = await vscode.window.showSaveDialog({ title: 'Save native Story Mode Lua route', defaultUri, filters: { Lua: ['lua'] } }); if (!save) return;
  if (!ownsSession(owner)) return;
  const relative = path.relative(root, save.fsPath).replace(/\\/g, '/'); if (relative.startsWith('../')) return vscode.window.showErrorMessage('Story Mode path must remain inside the game folder so select.def can use a portable relative path.');
  await fs.promises.mkdir(path.dirname(save.fsPath), { recursive: true }); await fs.promises.writeFile(save.fsPath, linearStoryLua({ p1char }), { encoding: 'utf8', flag: 'wx' }).catch((error) => { if (error.code === 'EEXIST') throw new Error('That story Lua file already exists. Choose a new name or open it for editing.'); throw error; });
  await appendStoryRegistration(owner, name, displayname || name, relative); await refresh(owner); await vscode.window.showTextDocument(save, { preview: false });
}

function docsPath(topic) { const root = path.resolve(__dirname, '..', 'data', 'offline-docs', 'reference', 'wiki-source'); return path.join(root, topic === 'dialogue' ? 'State-controllers-(new).md' : 'Lua.md'); }
async function handle(owner, message) {
  if (!ownsSession(owner)) return;
  if (await handleLaunchMessage(message, owner.file, 'story', owner.panel)) return;
  if (message.type === 'dialogueDraft') { await formDrafts.stage(draftKey(owner.file), message.draft); return owner.panel.webview.postMessage({type:'dialogueDraftStored',revision:message.revision}); }
  if (message.type === 'discardDialogueDraft') { await formDrafts.discard(draftKey(owner.file)); return owner.panel.webview.postMessage({type:'dialogueDraftDiscarded'}); }
  if (message.type === 'reload') return refresh(owner);
  if (message.type === 'selectCode') return reveal(owner.document);
  if (message.type === 'createArc') return createArc(owner);
  if (message.type === 'openArc') { if (!message.path) return vscode.window.showWarningMessage('This arc has no Lua path.'); const target = path.resolve(gameRootFromSelect(owner.file), message.path); if (!fs.existsSync(target)) return vscode.window.showWarningMessage(`Story Lua is missing: ${target}`); return vscode.window.showTextDocument(vscode.Uri.file(target), { preview: false }); }
  if (message.type === 'menuModes') return vscode.commands.executeCommand('ikemen.menuModes.openCreator', vscode.Uri.file(owner.file));
  if (message.type === 'portraitImport') return vscode.commands.executeCommand('ikemen.paletteImport.open', vscode.Uri.file(owner.file));
  if (message.type === 'storyboard') { const command = message.action === 'open' ? 'ikemen.storyboard.open' : message.action === 'opening' ? 'ikemen.storyboard.createOpening' : message.action === 'ending' ? 'ikemen.storyboard.createEnding' : 'ikemen.storyboard.create'; return vscode.commands.executeCommand(command); }
  if (message.type === 'docs') { const target = docsPath(message.topic); return fs.existsSync(target) ? vscode.window.showTextDocument(vscode.Uri.file(target), { preview: false }) : vscode.commands.executeCommand('ikemen.docs.openOffline'); }
  if (message.type === 'dialogue') {
    const text = dialogueController(message);
    if (message.action === 'copy') { await vscode.env.clipboard.writeText(text); return vscode.window.showInformationMessage('Copied the native IKEMEN Dialogue controller.'); }
    const editor = vscode.window.activeTextEditor;
    if (!editor || !/\.(zss|cns|st)$/i.test(editor.document.fileName)) { await vscode.env.clipboard.writeText(text); return vscode.window.showWarningMessage('Open the destination ZSS/CNS file and place the cursor first. The controller was copied instead.'); }
    await editor.edit((builder) => builder.insert(editor.selection.active, `${editor.selection.active.character ? '\n' : ''}${text}`));
  }
}

async function refresh(owner, requestedView = owner?.view) { if (!owner || sessions.get(sessionKey(owner.file)) !== owner) return; const loaded = await load(owner.file); if (sessions.get(sessionKey(owner.file)) !== owner) return; owner.document = loaded.document; owner.view = ['player','dialogue','creator'].includes(requestedView) ? requestedView : owner.view; owner.panel.webview.html = require('./webview_policy').protect(cohesive(html(loaded.model, owner.view)), owner.panel.webview.cspSource); }
async function openStoryDialogueWorkspace(uri, initialView = 'player') {
  const file = await resolveSelect(uri); if (!file) return;
  const key = sessionKey(file), existing = sessions.get(key);
  if (existing) { await refresh(existing, initialView); revealInViewerGroup(existing.panel, false, vscode.ViewColumn.Active); return existing.panel; }
  const loaded = await load(file);
  const panel = trackViewerPanel(vscode.window.createWebviewPanel('ikemenStoryDialogueWorkspace', 'IKEMEN Story & Dialogue', preferredViewerColumn(vscode.ViewColumn.Active), { enableScripts: true, retainContextWhenHidden: true }));
  const owner = { panel, file, document: loaded.document, view: initialView, busy: 0 }; sessions.set(key, owner); panel.webview.html = require('./webview_policy').protect(cohesive(html(loaded.model, initialView)), panel.webview.cspSource); require('./viewer_sessions').register(panel, file, 'story_dialogue'); require('./viewer_close').support(panel, {isBusy:()=>owner.busy>0,keepDraft:()=>formDrafts.flush()}); panel.webview.onDidReceiveMessage((message) => { owner.busy++; Promise.resolve(handle(owner, message)).catch((error) => vscode.window.showErrorMessage(`Story & Dialogue: ${error.message}`)).finally(()=>owner.busy--); }); panel.onDidDispose(() => { if (sessions.get(key) === owner) sessions.delete(key); }); return panel;
}
function registerStoryDialogueWorkspace(context) { formDrafts = new FormDrafts(context.workspaceState); context.subscriptions.push(vscode.commands.registerCommand('ikemen.storyDialogue.openPlayer', (uri, options) => openStoryDialogueWorkspace(uri, options?.preset ? options.reference?.view : 'player')), vscode.commands.registerCommand('ikemen.storyDialogue.openCreator', (uri, options) => openStoryDialogueWorkspace(uri, options?.preset ? options.reference?.view : 'creator')), vscode.workspace.onDidChangeTextDocument((event) => { for (const owner of sessions.values()) if (event.document.uri.toString() === owner.document.uri.toString()) refresh(owner).catch(() => {}); }), vscode.window.registerWebviewPanelSerializer('ikemenStoryDialogueWorkspace', { async deserializeWebviewPanel(panel, state) { panel.dispose(); if (state?.file) await openStoryDialogueWorkspace(vscode.Uri.file(state.file), state.view || 'player'); } })); }

module.exports = { registerStoryDialogueWorkspace, openStoryDialogueWorkspace, resolveSelect, gameRootFromSelect, html };
