'use strict';

const fs = require('fs');
const path = require('path');
const { transactionalWriteSet } = require('./mutation_safety');

const MODULE_RELATIVE = 'external/mods/IKEMaker_test_session.lua';
const SESSION_ROOT = '.ikemen/test-sessions';

function luaString(value) { return `'${String(value ?? '').replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\r/g, '').replace(/\n/g, '\\n')}'`; }
function luaValue(value) {
  if (value === null || value === undefined) return 'nil';
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (Array.isArray(value)) return `{${value.map(luaValue).join(', ')}}`;
  return luaString(value);
}
function luaRecords(records, fields) {
  return `{\n${records.map(record => `\t{${fields.map(field => `${field} = ${luaValue(record[field])}`).join(', ')}}`).join(',\n')}\n}`;
}
function runtimeLua(session) {
  const tests = luaRecords(session.tests || [], ['id', 'name', 'instruction', 'evidenceMask', 'suiteName']);
  const diagnostics = luaRecords(session.diagnostics || [], ['id', 'name', 'function', 'args', 'help']);
  const resultPath = `save/logs/IKEMaker-${String(session.id).replace(/[^a-z0-9_-]/gi, '_')}.json`;
  return `-- Generated by IKEMaker for one offline development launch.
-- The bootstrap removes itself after loading and must never ship with a game.
local bootstrapPath = ${luaString(MODULE_RELATIVE)}
local session = {
\tid = ${luaString(session.id)}, kind = ${luaString(session.kind)}, profile = ${luaString(session.profile)},
\tcharacter = ${luaString(session.character)}, stage = ${luaString(session.stage)}, createdAt = ${luaString(session.createdAt)},
\ttests = ${tests}, diagnostics = ${diagnostics}, resultPath = ${luaString(resultPath)}
}
os.remove(bootstrapPath)

local state = {visible = true, selected = 1, status = {}, notes = {}, diagnosticRuns = {}, lastMask = 0, written = false, keys = {}}
local font = fontNew(gameOption('Debug.Font'), 8)
local sprite = textImgNew()
textImgSetFont(sprite, font)
textImgSetScale(sprite, 0.5, 0.5)

local function pressed(key)
\tlocal down = getKey(key)
\tlocal edge = down and not state.keys[key]
\tstate.keys[key] = down
\treturn edge
end
local function hasBit(value, bit) return bit > 0 and math.floor(value / bit) % 2 == 1 end
local function containsMask(value, mask)
\tif mask <= 0 then return false end
\tfor bit = 0, 15 do local power = 2 ^ bit; if hasBit(mask, power) and not hasBit(value, power) then return false end end
\treturn true
end
local function currentMask()
\tlocal old = id(); local masks = {}
\tfor p = 1, 8 do if player(p) then table.insert(masks, var(59000)) end end
\tplayerId(old)
\tlocal union = 0
\tfor bit = 0, 15 do
\t\tlocal power = 2 ^ bit
\t\tfor _, value in ipairs(masks) do if hasBit(value, power) then union = union + power; break end end
\tend
\treturn union
end
local function jsonEscape(value)
\treturn tostring(value or ''):gsub('[%c"\\\\]', '_')
end
local function writeResults()
\tlocal file, err = io.open(session.resultPath, 'w')
\tif not file then printConsole('IKEMaker result write failed: ' .. tostring(err)); return end
\tfile:write('{\\n  "schemaVersion": 1,\\n  "sessionId": "' .. jsonEscape(session.id) .. '",\\n')
\tfile:write('  "kind": "' .. jsonEscape(session.kind) .. '",\\n  "profile": "' .. jsonEscape(session.profile) .. '",\\n')
\tfile:write('  "character": "' .. jsonEscape(session.character) .. '",\\n  "stage": "' .. jsonEscape(session.stage) .. '",\\n')
\tfile:write('  "completedAt": "' .. jsonEscape(tostring(getTimestamp())) .. '",\\n  "tests": [\\n')
\tfor index, test in ipairs(session.tests) do
\t\tlocal status = state.status[index] or 'not-run'
\t\tfile:write('    {"id":"' .. jsonEscape(test.id) .. '","name":"' .. jsonEscape(test.name) .. '","status":"' .. status .. '","evidenceMask":' .. tostring(test.evidenceMask or 0) .. ',"observedMask":' .. tostring(state.lastMask) .. '}')
\t\tif index < #session.tests then file:write(',') end
\t\tfile:write('\\n')
\tend
\tfile:write('  ],\\n  "diagnostics": [\\n')
\tlocal first = true
\tfor id, count in pairs(state.diagnosticRuns) do
\t\tif not first then file:write(',\\n') end; first = false
\t\tfile:write('    {"id":"' .. jsonEscape(id) .. '","executions":' .. tostring(count) .. '}')
\tend
\tfile:write('\\n  ]\\n}\\n'); file:close(); state.written = true
\tprintConsole('IKEMaker results: ' .. session.resultPath)
end
local function draw(x, y, text, color)
\ttextImgReset(sprite, {'pos', 'text', 'palfx'}); textImgSetAlign(sprite, 1)
\ttextImgSetColor(sprite, color[1], color[2], color[3], 255); textImgAddPos(sprite, x, y)
\ttextImgSetText(sprite, text); textImgDraw(sprite)
end
local function safeCall(name)
\tlocal fn = _G[name]
\tif type(fn) ~= 'function' then printConsole('IKEMaker diagnostic unavailable: ' .. tostring(name)); return end
\tlocal ok, err = pcall(fn); if not ok then printConsole('IKEMaker diagnostic failed: ' .. tostring(err)) end
end
local function runDiagnostic(item)
\tlocal ai = item.id:match('^ai%-(%d+)$'); local player = item.id:match('^player%-(%d+)$')
\tif ai then pcall(toggleAI, tonumber(ai))
\telseif player then pcall(togglePlayer, tonumber(player))
\telseif item.function == 'standAll' then for p = 1, 8 do pcall(stand, p) end
\telseif item.function == 'fullRestore' then for p = 1, 8 do pcall(full, p) end; pcall(setTime, getRoundTime())
\telseif item.function == 'killP2' then for _, p in ipairs({2,4,6,8}) do pcall(kill, p) end
\telseif item.function == 'killP1' then for _, p in ipairs({1,3,5,7}) do pcall(kill, p) end
\telseif item.function == 'lifeOneAll' then for p = 1, 8 do pcall(kill, p, 1) end
\telseif item.function == 'powerMax' then pcall(powMax, 1); pcall(powMax, 2)
\telseif item.function == 'timeZero' then pcall(setTime, 0)
\telseif item.function == 'trainingReset' then pcall(resetRound); pcall(trainingReset)
\telseif item.function == 'reload' then pcall(reload); pcall(trainingReset)
\telseif item.id == 'debug-next' then pcall(toggleDebugDisplay, nil, false)
\telseif item.id == 'debug-clsn' then pcall(toggleDebugDisplay, nil, true)
\telseif item.id == 'debug-all' then pcall(toggleDebugDisplay, true, nil)
\telseif item.id == 'speed-up' then pcall(changeSpeed, 0.01)
\telseif item.id == 'speed-down' then pcall(changeSpeed, -0.01)
\telse safeCall(item.function) end
\tstate.diagnosticRuns[item.id] = (state.diagnosticRuns[item.id] or 0) + 1
\twriteResults()
end
local function wrap(value, width)
\tlocal output, remaining = {}, tostring(value or '')
\twhile #remaining > width and #output < 3 do local cut = remaining:sub(1, width + 1):match('^.*()%s') or width; table.insert(output, remaining:sub(1, cut - 1)); remaining = remaining:sub(cut + 1) end
\tif remaining ~= '' then table.insert(output, remaining) end; return output
end

hook.add('loop', 'IKEMaker_test_session', function()
\tif not gameMode('training') then return end
\tif pressed('F8') then state.visible = not state.visible end
\tif not state.visible then return end
\tstate.lastMask = currentMask()
\tlocal items = session.kind == 'diagnostic' and session.diagnostics or session.tests
\tif #items == 0 then return end
\tif pressed('F9') then state.selected = state.selected % #items + 1 end
\tif pressed('F10') then
\t\tif session.kind == 'diagnostic' then runDiagnostic(items[state.selected]) else state.status[state.selected] = 'pass'; writeResults() end
\tend
\tif pressed('F11') and session.kind ~= 'diagnostic' then state.status[state.selected] = 'fail'; writeResults() end
\tif pressed('F12') then writeResults() end
\tlocal white, cyan, green, red, dim = {255,255,255}, {80,235,255}, {100,255,140}, {255,100,100}, {180,190,205}
\tdraw(8, 8, 'IKEMAKER ' .. string.upper(session.kind) .. ' SESSION  [' .. session.profile .. ']', cyan)
\tdraw(8, 16, string.format('%d/%d  %s', state.selected, #items, items[state.selected].name), white)
\tlocal description = session.kind == 'diagnostic' and items[state.selected].help or items[state.selected].instruction
\tfor line, text in ipairs(wrap(description, 86)) do draw(8, 16 + line * 8, text, dim) end
\tif session.kind == 'test' then
\t\tlocal status = state.status[state.selected] or 'not-run', mask = items[state.selected].evidenceMask or 0
\t\tlocal detected = containsMask(state.lastMask, mask)
\t\tdraw(8, 54, 'STATUS: ' .. string.upper(status) .. (detected and '  |  LOGGER EVIDENCE DETECTED' or ''), status == 'pass' and green or (status == 'fail' and red or white))
\t\tdraw(8, 64, 'F9 Next test   F10 Pass   F11 Fail   F12 Save results   F8 Hide', dim)
\telse
\t\tdraw(8, 54, 'F9 Next action   F10 Execute   F8 Hide', dim)
\t\tdraw(8, 64, 'Pause/Scroll Lock retain IKEMEN native pause and frame-step behavior.', dim)
\tend
end)
`;
}

function installSession(root, session) {
  const modulePath = path.join(root, ...MODULE_RELATIVE.split('/'));
  const recordPath = path.join(root, SESSION_ROOT, `${session.id}.json`);
  fs.mkdirSync(path.join(root, 'save', 'logs'), { recursive: true });
  transactionalWriteSet(fs, [[modulePath, runtimeLua(session)], [recordPath, `${JSON.stringify(session, null, 2)}\n`]], { label: 'prepare-ikemaker-test-session', journalRoot: root, backup: false, journal: false, allowExisting: true });
  return { modulePath, recordPath, resultPath: path.join(root, 'save', 'logs', `IKEMaker-${String(session.id).replace(/[^a-z0-9_-]/gi, '_')}.json`) };
}
function resultFiles(root) {
  const directory = path.join(root, 'save', 'logs');
  if (!fs.existsSync(directory)) return [];
  return fs.readdirSync(directory).filter(name => /^IKEMaker-.*\.json$/i.test(name)).map(name => path.join(directory, name)).sort((a, b) => fs.statSync(b).mtimeMs - fs.statSync(a).mtimeMs);
}
function removeBootstrap(root) {
  const filename = path.join(root, ...MODULE_RELATIVE.split('/'));
  if (fs.existsSync(filename)) fs.unlinkSync(filename);
}

module.exports = { MODULE_RELATIVE, SESSION_ROOT, luaString, runtimeLua, installSession, resultFiles, removeBootstrap };
