'use strict';
const KEY='ikemaker.viewerLayouts.v1';
const supported=new Set(['air','move_constants','snd','sff']);
let storage,layouts={},queue=Promise.resolve();
const panels=new Map();
function normalize(value){return {left:value?.left!==false,right:value?.right!==false,leftWidth:Math.max(160,Math.min(600,Number(value?.leftWidth)||280)),rightWidth:Math.max(180,Math.min(600,Number(value?.rightWidth)||320)),...(value?.groups!==undefined?{groups:value.groups!==false,groupsWidth:Math.max(160,Math.min(420,Number(value.groupsWidth)||220))}:{})};}
function spriteLayout(visibility={},widths={}){const defaults={left1:230,left2:270,right1:300,right2:250};return {panes:Object.fromEntries(Object.keys(defaults).map(id=>[id,{visible:visibility[id]!==false,width:Math.max(170,Math.min(420,Number(widths[id])||defaults[id]))}]))};}
function normalizeLayout(surface,value){if(surface!=='sff')return normalize(value);return spriteLayout(Object.fromEntries(Object.entries(value?.panes||{}).map(([id,pane])=>[id,pane?.visible])),Object.fromEntries(Object.entries(value?.panes||{}).map(([id,pane])=>[id,pane?.width])));}
function presets(surface,mode=require('./interface_mode').current()){if(surface==='sff')return {Default:spriteLayout((mode!=='workspace')?{right2:false}:{}),Animation:spriteLayout({right1:false,right2:false}),'Attack Editing':spriteLayout({right2:false}),'Sprite Cleanup':spriteLayout({right1:false})};return {
  Default:normalize(surface==='snd'?{groups:true,right:!(mode!=='workspace'),groupsWidth:220,leftWidth:300,rightWidth:340}:surface==='air'?{leftWidth:245,rightWidth:360}:{leftWidth:360,rightWidth:300}),
  Animation:normalize({leftWidth:200,rightWidth:280,right:false}),
  'Attack Editing':normalize({leftWidth:360,rightWidth:300}),
  'Sprite Cleanup':normalize({leftWidth:240,rightWidth:260,right:false})
};}
function configure(context){storage=context.globalState;layouts=storage?.get(KEY,{})||{};}
function html(surface){if(!supported.has(surface))return '';return '<button data-viewer-layout title="Show, hide, or resize this viewer’s side panels">Layout…</button><button data-viewer-layout-reset title="Restore this viewer’s default panel layout">Reset Layout</button>';}
async function handle(message,panel){
  if(!['viewerLayoutReady','viewerLayoutSave','viewerLayoutReset'].includes(message?.type))return false;
  if(!supported.has(message.surface)||!panel?.webview)return true;
  if(!panels.has(panel)){panels.set(panel,{surface:message.surface,mode:['player','simple','workspace'].includes(message.mode)?message.mode:require('./interface_mode').current()});panel.onDidDispose?.(()=>panels.delete(panel));}
  if(message.type==='viewerLayoutReady'&&['player','simple','workspace'].includes(message.mode))panels.set(panel,{surface:message.surface,mode:message.mode});
  const {surface,mode}=panels.get(panel),key=surface+':'+mode,defaults=presets(surface,mode).Default;
  const recordForMode=()=>layouts[key]||(mode==='workspace'?layouts[surface]:undefined);
  const send=(target,saved=false)=>target.webview.postMessage({type:'viewerLayoutState',surface,mode,current:normalizeLayout(surface,recordForMode()?.current||(mode==='workspace'&&message.type==='viewerLayoutReady'&&message.initial)||defaults),savedLayouts:recordForMode()?.saved||{},presets:presets(surface,mode),saved});
  if(message.type==='viewerLayoutReady'){await send(panel);return true;}
  queue=queue.catch(()=>{}).then(async()=>{
    if(!storage)throw Error('Layout storage is unavailable. Reopen the viewer.');
    const record={...(recordForMode()||{}),current:message.type==='viewerLayoutReset'?defaults:normalizeLayout(surface,message.layout)};
    if(message.type==='viewerLayoutSave'&&typeof message.name==='string'&&message.name.trim()){
      const name=message.name.trim().slice(0,60);
      record.saved={...(record.saved||{}),[name]:record.current};
    }
    const next={...layouts,[key]:record};await storage.update(KEY,next);layouts=next;
    for(const [target,kind] of panels)if(kind.surface===surface&&kind.mode===mode)await send(target,true);
  });
  try{await queue;}catch(error){await panel.webview.postMessage({type:'viewerLayoutError',mode,message:error.message});}
  return true;
}
function client(){
  const button=document.querySelector('[data-viewer-layout]');if(!button)return;
  const surface=document.querySelector('[data-toolbar-surface]')?.dataset?.toolbarSurface;
  if(!['air','move_constants','snd'].includes(surface))return;
  const root=document.querySelector(surface==='move_constants'?'.layout':'.workspace'),left=root?.querySelector(surface==='snd'?':scope > aside:nth-child(2)':':scope > .left'),right=root?.querySelector(':scope > .right'),groups=surface==='snd'?root?.querySelector(':scope > aside:first-child'):null;
  if(!root||!left||!right)return;
  const style=document.createElement('style');style.nonce=document.currentScript?.nonce||'';style.textContent='[data-layout-hidden]{display:none!important}.viewer-layout-dialog{max-width:min(440px,90vw);color:var(--vscode-foreground);background:var(--vscode-editor-background);border:1px solid var(--vscode-panel-border)}.viewer-layout-dialog label{display:block;margin:10px 0}.viewer-layout-dialog input[type=number]{width:90px}.viewer-layout-dialog button{margin:4px}.viewer-layout-dialog select,.viewer-layout-dialog input[type=text]{max-width:100%}@media(min-width:1100px){[data-custom-viewer-layout]{grid-template-columns:var(--viewer-left-width) minmax(240px,1fr) var(--viewer-right-width)!important}[data-custom-viewer-layout]>.center{grid-column:2!important;grid-row:1!important}[data-custom-viewer-layout]>.left{grid-column:1!important;grid-row:1!important}[data-custom-viewer-layout]>.right{grid-column:3!important;grid-row:1!important}}@media(min-width:481px) and (max-width:1099px){[data-viewer-layout-surface=air]{grid-template-columns:minmax(0,min(var(--viewer-left-width),280px)) minmax(240px,1fr)!important;grid-template-rows:390px auto!important;overflow:auto;align-content:start}[data-viewer-layout-surface=air]>.left{grid-column:1!important;grid-row:1!important}[data-viewer-layout-surface=air]>.center{grid-column:2!important;grid-row:1!important}[data-viewer-layout-surface=air]>.right{grid-column:1 / -1!important;grid-row:2!important;overflow:visible}}@media(min-width:651px) and (max-width:1099px){[data-viewer-layout-surface=move_constants]{grid-template-columns:minmax(0,min(var(--viewer-left-width),300px)) minmax(240px,1fr)!important;grid-template-rows:minmax(500px,1fr) auto;overflow:auto;align-content:start}[data-viewer-layout-surface=move_constants]>.left{grid-column:1!important;grid-row:1!important}[data-viewer-layout-surface=move_constants]>.center{grid-column:2!important;grid-row:1!important}[data-viewer-layout-surface=move_constants]>.right{display:block;grid-column:1 / -1!important;grid-row:2!important;min-height:240px;max-height:320px;overflow:auto}}@media(max-width:650px){[data-viewer-layout-surface=move_constants]{display:flex!important;flex-direction:column;overflow:auto}[data-viewer-layout-surface=move_constants]>.center{order:-1;height:500px;min-height:500px;flex:none}[data-viewer-layout-surface=move_constants]>.rail{flex:none;max-height:360px;overflow:auto}}';document.head.append(style);
  const dialog=document.createElement('dialog');dialog.className='viewer-layout-dialog';dialog.setAttribute('aria-label','Viewer layout');dialog.innerHTML='<h2>Viewer layout</h2><p>Side panels can be hidden without clearing edits. Widths apply when there is room for columns.</p><label>Preset or saved layout <select id="viewer-layout-preset"></select></label><label><input id="viewer-layout-left" type="checkbox"> Show left panel</label><label>Left width <input id="viewer-layout-left-width" type="number" min="160" max="600"> px</label><label><input id="viewer-layout-right" type="checkbox"> Show right panel</label><label>Right width <input id="viewer-layout-right-width" type="number" min="180" max="600"> px</label><label>Save as (optional) <input id="viewer-layout-name" type="text" maxlength="60"></label><p role="status" id="viewer-layout-status"></p><button id="viewer-layout-apply">Apply</button><button id="viewer-layout-cancel">Cancel</button>';document.body.append(dialog);
  if(groups){
    dialog.innerHTML=dialog.innerHTML.replace('Show left panel','Show sounds panel').replace('Left width','Sounds width').replace('Show right panel','Show profile and tools').replace('Right width','Profile/tools width');
    const fields=document.createElement('div');fields.innerHTML='<label><input id="viewer-layout-groups" type="checkbox"> Show groups panel</label><label>Groups width <input id="viewer-layout-groups-width" type="number" min="160" max="420"> px</label>';dialog.insertBefore(fields,dialog.querySelector('p'));
    const soundStyle=document.createElement('style');soundStyle.nonce=document.currentScript?.nonce||'';soundStyle.textContent='[data-sound-layout]{grid-template-columns:var(--viewer-groups-width) var(--viewer-left-width) minmax(240px,1fr) var(--viewer-right-width)!important}[data-sound-layout]>aside:first-child{grid-column:1!important;grid-row:1!important}[data-sound-layout]>aside:nth-child(2){grid-column:2!important;grid-row:1!important}[data-sound-layout]>.center{grid-column:3!important;grid-row:1!important}@media(min-width:651px){[data-sound-layout]{grid-template-rows:minmax(0,1fr)!important}[data-sound-layout]>*{min-height:0;overflow:auto!important}}[data-sound-layout]>.right{grid-column:4!important;grid-row:1!important}@media(min-width:651px) and (max-width:1099px){[data-sound-layout]{grid-template-columns:minmax(0,min(var(--viewer-groups-width),180px)) minmax(0,min(var(--viewer-left-width),230px)) minmax(240px,1fr)!important;grid-template-rows:minmax(400px,1fr) auto!important;align-content:start}[data-sound-layout]>.right{grid-column:1 / -1!important;grid-row:2!important;min-height:240px;max-height:320px}}@media(max-width:650px){[data-sound-layout]{display:flex!important;flex-direction:column;height:auto!important;flex:1;min-height:0}[data-sound-layout]>.center{order:-1;min-height:360px;flex-shrink:0}[data-sound-layout]>aside{max-height:320px;flex-shrink:0}}';document.head.append(soundStyle);
  }
  const get=id=>dialog.querySelector('#viewer-layout-'+id);let current,options={};
  function fill(value){if(groups){get('groups').checked=value.groups!==false;get('groups-width').value=value.groupsWidth||220;}get('left').checked=value.left;get('right').checked=value.right;get('left-width').value=value.leftWidth;get('right-width').value=value.rightWidth;}
  function apply(value){if(groups){root.dataset.soundLayout='';groups.toggleAttribute('data-layout-hidden',value.groups===false);root.style.setProperty('--viewer-groups-width',value.groups===false?'0px':(value.groupsWidth||220)+'px');}root.dataset.customViewerLayout='';root.dataset.viewerLayoutSurface=surface;left.toggleAttribute('data-layout-hidden',!value.left);right.toggleAttribute('data-layout-hidden',!value.right);root.style.setProperty('--viewer-left-width',value.left?value.leftWidth+'px':'0px');root.style.setProperty('--viewer-right-width',value.right?value.rightWidth+'px':'0px');}
  button.onclick=()=>{if(!current)return;fill(current);get('preset').value='';get('name').value='';get('status').textContent='';dialog.showModal();};
  document.querySelector('[data-viewer-layout-reset]').onclick=()=>vscode.postMessage({mode:document.querySelector('[data-toolbar-surface]')?.dataset?.mode,type:'viewerLayoutReset',surface});
  get('preset').onchange=()=>{if(options[get('preset').value])fill(options[get('preset').value]);};
  get('cancel').onclick=()=>dialog.close();get('apply').onclick=()=>{get('status').textContent='Saving…';vscode.postMessage({mode:document.querySelector('[data-toolbar-surface]')?.dataset?.mode,type:'viewerLayoutSave',surface,name:get('name').value,layout:{...(groups?{groups:get('groups').checked,groupsWidth:Number(get('groups-width').value)}:{}),left:get('left').checked,right:get('right').checked,leftWidth:Number(get('left-width').value),rightWidth:Number(get('right-width').value)}});};
  addEventListener('message',event=>{const m=event.data;if(m.mode&&m.mode!==document.querySelector('[data-toolbar-surface]')?.dataset?.mode)return;if(m.type==='viewerLayoutError'){get('status').textContent=m.message;return;}if(m.type!=='viewerLayoutState'||m.surface!==surface)return;current=m.current;options={...m.presets,...m.savedLayouts};get('preset').replaceChildren();const placeholder=document.createElement('option');placeholder.value='';placeholder.textContent='Current arrangement';get('preset').append(placeholder);for(const name of Object.keys(options)){const option=document.createElement('option');option.value=name;option.textContent=name;get('preset').append(option);}apply(current);if(m.saved)dialog.close();});
  vscode.postMessage({mode:document.querySelector('[data-toolbar-surface]')?.dataset?.mode,type:'viewerLayoutReady',surface});
}
function spriteClient(){
  const adapter=globalThis.ikemenSpriteLayout;if(!adapter)return;
  const button=document.querySelector('[data-viewer-layout]');if(!button)return;
  const labels={left1:'Groups',left2:'Sprites',right1:'Inspector',right2:'Tools'},dialog=document.createElement('dialog');
  dialog.className='sprite-layout-dialog';
  const style=document.createElement('style');style.nonce=document.currentScript?.nonce||'';style.textContent='.sprite-layout-dialog p{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin:12px 0}.sprite-layout-dialog label{display:inline-flex;align-items:center;gap:6px;max-width:100%}.sprite-layout-dialog input[type=checkbox]{width:16px!important;height:16px!important;min-height:16px!important;margin:0}.sprite-layout-dialog input[type=number]{width:80px!important}.sprite-layout-dialog input,.sprite-layout-dialog select,.sprite-layout-dialog button{color:var(--vscode-input-foreground);background:var(--vscode-input-background);border:1px solid var(--vscode-input-border);padding:6px;font:inherit;max-width:100%}.sprite-layout-dialog button{margin:4px}.sprite-layout-dialog :focus-visible{outline:2px solid var(--vscode-focusBorder);outline-offset:2px}';document.head.append(style);
  dialog.setAttribute('aria-label','Viewer layout');dialog.style.cssText='max-width:min(460px,90vw);max-height:85vh;overflow:auto;background:var(--vscode-editor-background);color:var(--vscode-foreground);border:1px solid var(--vscode-panel-border);padding:18px';
  dialog.innerHTML='<h2>Viewer layout</h2><label>Preset or saved layout <select id="sprite-layout-choice"></select></label><div id="sprite-layout-panes"></div><label>Save as (optional) <input id="sprite-layout-name" maxlength="60"></label><p role="status" id="sprite-layout-status"></p><button id="sprite-layout-save">Apply</button><button id="sprite-layout-cancel">Cancel</button>';
  document.body.append(dialog);const get=id=>dialog.querySelector('#sprite-layout-'+id);let options={},applying=false;
  for(const [id,label] of Object.entries(labels)){const row=document.createElement('p');row.innerHTML='<label><input type="checkbox" data-visible="'+id+'"> '+label+'</label> <label>Width <input style="width:80px" type="number" min="170" max="420" data-width="'+id+'"> px</label>';get('panes').append(row);}
  const read=()=>({panes:Object.fromEntries(Object.keys(labels).map(id=>[id,{visible:dialog.querySelector('[data-visible="'+id+'"]').checked,width:Number(dialog.querySelector('[data-width="'+id+'"]').value)}]))});
  function fill(layout){for(const id of Object.keys(labels)){dialog.querySelector('[data-visible="'+id+'"]').checked=layout.panes[id].visible;dialog.querySelector('[data-width="'+id+'"]').value=layout.panes[id].width;}}
  button.onclick=()=>{fill(adapter.read());get('choice').value='';get('name').value='';get('status').textContent='';dialog.showModal();};
  get('choice').onchange=()=>{const value=options[get('choice').value];if(value)fill(value);};
  get('cancel').onclick=()=>dialog.close();get('save').onclick=()=>{get('status').textContent='Saving…';vscode.postMessage({mode:document.querySelector('[data-toolbar-surface]')?.dataset?.mode,type:'viewerLayoutSave',surface:'sff',name:get('name').value,layout:read()});};
  document.querySelector('[data-viewer-layout-reset]').onclick=()=>vscode.postMessage({mode:document.querySelector('[data-toolbar-surface]')?.dataset?.mode,type:'viewerLayoutReset',surface:'sff'});
  globalThis.ikemenSpriteLayoutChanged=()=>{if(!applying)vscode.postMessage({mode:document.querySelector('[data-toolbar-surface]')?.dataset?.mode,type:'viewerLayoutSave',surface:'sff',layout:adapter.read()});};
  addEventListener('message',event=>{const m=event.data;if(m.mode&&m.mode!==document.querySelector('[data-toolbar-surface]')?.dataset?.mode)return;if(m.type==='viewerLayoutError'){get('status').textContent=m.message;return;}if(m.type!=='viewerLayoutState'||m.surface!=='sff')return;options={...m.presets,...m.savedLayouts};get('choice').replaceChildren();const placeholder=document.createElement('option');placeholder.value='';placeholder.textContent='Current arrangement';get('choice').append(placeholder);for(const name of Object.keys(options)){const option=document.createElement('option');option.value=name;option.textContent=name;get('choice').append(option);}applying=true;try{adapter.apply(m.current);}finally{applying=false;}if(m.saved)dialog.close();});
  vscode.postMessage({mode:document.querySelector('[data-toolbar-surface]')?.dataset?.mode,type:'viewerLayoutReady',surface:'sff',initial:adapter.read()});
}
module.exports={normalize,normalizeLayout,presets,configure,html,handle,clientScript:()=>`(${client.toString()})();(${spriteClient.toString()})();`};
